### ISSUE TITLE
Cobblestone cauldron doesn't accept cobblestone to make lava

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#1]
Trying to make lava for the cobblegen. Made a cobblestone cauldron, placed over a torch, but it won't accept cobblestone per JEI's recipe for lava (1 cobble = 250mB lava).
![2018-09-18_21 32 57](https://user-images.githubusercontent.com/29290246/45725835-af8e0000-bb8a-11e8-8536-24e377afa68f.png)

Looking at the inspirations.cfg file, perhaps a torch doesn't count as fire?
```
       # List of blocks to act is fire below a cauldron. Format is modid:name[:meta]. If meta is excluded all states of the block will count as fire
        S:fires <
            minecraft:fire
            minecraft:magma
            minecraft:lava
         >
```
Don't have iron at this stage to make a flint&steel. Unsure other ways to make fire at this point.

Not sure if I'm just misreading the advancement/JEI recipe. The cobblegen advancement is tiered from creating your first cobble so that leads me to think this is the intended route.
![2018-09-18_21 34 19](https://user-images.githubusercontent.com/29290246/45725844-bb79c200-bb8a-11e8-8470-c3224cb2fad0.png)

SFIIII 0.0.9
Forge-14.23.4.2760
More Cauldrons 1.4.2.1
Inspirations 1.12.2-0.2.2

**Comment by MongoTheElder** [comment]
After cheating in a bucket of lava, the next advancement for the lava bucket appeared and says that it requires fire, magma block, or lava under the cauldron.  The lava bucket advancement has 'cobblegen' as a parent, seems reversed.
![2018-09-18_23 04 21](https://user-images.githubusercontent.com/29290246/45728733-57112f80-bb97-11e8-9173-98b0f6973256.png)

**Comment by Darkosto** [comment]
Added torches to this file to allow the progression. Thanks!
