### ISSUE TITLE
Unable to alloy ingots with TC

### ISSUE THREAD

**Issue by OELEWOELE** [Darkosto/SkyFactory4Issues#1001]
//I could not find a template so if anyone has a link for me I would greatly appreciate it so I can edit the post correctly.

I've got the TC setup to make alloy's but it doesn't seem to be working. I've even tried topping up the tanks to full so that I'm sure it has enough liquid resources but it just doesn't want to work.
![image](https://user-images.githubusercontent.com/45320874/58260152-3a587780-7d76-11e9-8a66-0e338a9d4d61.png)
![image](https://user-images.githubusercontent.com/45320874/58260078-1b59e580-7d76-11e9-859b-9a165901910a.png)
![image](https://user-images.githubusercontent.com/45320874/58260060-109f5080-7d76-11e9-929f-f7c6b0b3d931.png)
![image](https://user-images.githubusercontent.com/45320874/58259997-fbc2bd00-7d75-11e9-9ee1-732746d02b50.png) 
![SF4SC](https://user-images.githubusercontent.com/45320874/58259961-e8175680-7d75-11e9-8565-7e09656e1e13.png)

**Comment by LezChap** [comment]
Make sure you have a Seared Heater under the Alloy Tank, and have a furnace fuel (coal, charcoal, etc) in it.  Make sure both are placed from your inventory (often moving them via CarryOn will cause them not to "reform").

**Comment by OELEWOELE** [comment]
> Make sure you have a Seared Heater under the Alloy Tank, and have a furnace fuel (coal, charcoal, etc) in it. Make sure both are placed from your inventory (often moving them via CarryOn will cause them not to "reform").

Well... I guess I'm just retarded... Thanks...

**Comment by LezChap** [comment]
It's the only two things I couldn't tell from your screenshots and you didn't mention in your post...making sure all the bases were covered to rule out "known issues". :)
