### ISSUE TITLE
Sugar cane growing ultra fast

### ISSUE THREAD

**Issue by Thorjimbo90** [Darkosto/SkyFactory4Issues#1010]
Using a Redstone clock from Cyclic to automate my tinkers smeltery, I have snad next to it, with sugar cane on top of it. Every tick cycle from the Redstone clock is causing the Sugar Cane to grow.
I have no idea how to fix it, other then to just not have this set up.

##Log
This isn't a crash issue

## World Information

* Preset: Basic sky island for SF4

* Prestige: No

* Modpack Version world created in: 14.23.5.2831

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.5
* Java Version: 1.8.0_211-b12
* Launcher Used: Twitch
* Memory Allocated: 8GBs
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: Yes

**Comment by Sabster** [comment]
Do you mean the snad is several blocks away?

The snad/redstone growth is a feature - not a bug.  If you move the snad, I'm assuming the problem is fixed?

**Comment by loliconxdd** [comment]
![ssssdsa](https://user-images.githubusercontent.com/51015136/58382159-6f283100-7ff9-11e9-9f29-5a4eb6272d48.png)
you get the idea yourself

**Comment by sk2048** [comment]
This isn't a bug.
