### ISSUE TITLE
Witherproof glass

### ISSUE THREAD

**Issue by ChristooMC** [Darkosto/SkyFactory4Issues#1012]
I had a box with witherproof glass to kill a wither and i spawn it and it is working. And randomly it goes through the box because its agressive to a animal. 
I tested this on a creative to find out if it was doing the same there too and it did.
I couldn't upload it here so I uploaded it to youtube
https://www.youtube.com/watch?v=Q04j27yoQ34

**Comment by Kynotzib** [comment]
Your box is one block to small. Has to be at least 4 blocks tall. Wither is 3.5 tall so can escape a 3 tall

**Comment by Darkosto** [comment]
Looks like you need to have a larger box since the entity size glitches out. Either use a larger box or double the thickness of your cage.
