### ISSUE TITLE
Water Bottle crafting recipe

### ISSUE THREAD

**Issue by Furious2014** [Darkosto/SkyFactory4Issues#1021]
## Context

I would like to have a crafting recipe with water essence and an empty bottle to make a full water bottle. This would help a lot when setting up brewing stand recipes since the other methods would require multiple steps with filling the cauldron and right clicking with an empty bottle to fill it. This would make automatic brewing a lot easier and so it would be easier to autocraft the different growth crystal tiers.

~Furious_2014

**Comment by BanzaiRun** [comment]
... or use the potion brewer?

**Comment by Darkosto** [comment]
The potion brewer from Industrial Foregoing automatically creates potions in 1 block.
