### ISSUE TITLE
Server Crashes After Loading World. No mod usage change since last load.

### ISSUE THREAD

**Issue by Djarcn** [Darkosto/SkyFactory4Issues#1022]
## Bug Report
Server crashes after "Forge Mod Loader has successfully loaded 200 mods" but then crashes immediately after. Have restarted PC but have not messed with the server itself. Had stopped and restarted the server to unban friend who was banned as a joke. 

## Expected Behaviour
Server Crashes instead of launching after loading mods

## Possible Solution
I believe it may have something to do with the playerlist and maybe the server somehow corrupted a players item data. Lead to believe this due to lines 31 and 32 in crash report and because player was banned then unbanned, but unsure if ban can mess with player data.

## Steps to Reproduce (for bugs)
1. Run Provided "LaunchServer.Bat"
2. Wait for server to load mods, takes a bit over a minute
3. Server crashes after mods load

## Logs
* Server Log: https://gist.github.com/Djarcn/18ae9cb88893cde6b90ac4dbff60ae72
* Crash Log: https://pastebin.com/gccZ7E5j

## World Information

* Preset: Classic Sky Factory

* Prestige: Off

* Modpack Version world created in: 4.0.5

* Additional Content Installed: Veinminer

## Client Information

* Modpack Version: 4.0.5
* Java Version: 8u211
* Launcher Used: ATLauncher
* Memory Allocated: 2G
* Server/LAN/Single Player: Server, Online
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: 8u211
* Operating System: Windows 10
* Hoster/Hosting Solution: Port-Forwarded
* Sponge (Non-Vanilla Forge) Server: ATLauncher default server install

**Comment by sk2048** [comment]
Using MCP mapping names, your crash report puts the smoking gun firmly in the hand of your ban list editing: 
`at net.minecraft.server.dedicated.DedicatedPlayerList.loadPlayerBanList`

You do know the `/pardon` command exists right?

Delete the `banned-players.json` file and allow it to regenerate, or make it a valid json file. An empty ban list should look like:

```
[]

```
