### ISSUE TITLE
Wooden cauldrons causing fires when filled with blood

### ISSUE THREAD

**Issue by Gunner76th** [Darkosto/SkyFactory4Issues#1024]
## Bug Report

While using the wooden cauldrons, placing blood in them is causing fires to be spawned in the world. 
Link to bug report filed with More Cauldrons mod: https://github.com/Mrbysco/MoreCauldrons/issues/5

## Expected Behaviour

Because blood when placed in the world acts exactly like water, it should not be causing fires when placed in a wooden cauldron. 

## Possible Solution

At present none is known as this appears to be a bug with the More Cauldrons mod. A bug report has been filed with the mod directly, this bug report is being filed for administrative purposes to help track the progress of the issue filed with More Cauldrons, as well as allow others who encounter the issue to know it has already been reported. 

## Steps to Reproduce (for bugs)

1. Place a wooden cauldron in the world (Any type will do, in so long as it is a wooden variant.)
![image](https://user-images.githubusercontent.com/5566872/58387381-adaef300-7fdb-11e9-8a79-2bd04f91f5d1.png)

2. Take a bucket of blood and pour it into the cauldron
![image](https://user-images.githubusercontent.com/5566872/58387374-9b34b980-7fdb-11e9-81d4-8f372cf088d3.png)

3. Observe the fires being spawned around and on the cauldron. 
![image](https://user-images.githubusercontent.com/5566872/58387361-5dd02c00-7fdb-11e9-902b-b2f6fc65091d.png)

## Logs

* Client/Server Log: Not applicable as this is not a crash issue. 
* Crash Log:

## World Information

* Preset: Skiiisland

* Prestige: No

* Modpack Version world created in: 4.0.5

* Additional Content Installed: FTB Utilities

## Client Information

* Modpack Version: 4.0.5
* Java Version: 1.8 u121
* Launcher Used: Twitch
* Memory Allocated: 6G
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 1.8 u121
* Operating System: Ubuntu Linux
* Hoster/Hosting Solution: N/A
* Sponge (Non-Vanilla Forge) Server: NO

**Comment by Mrbysco** [comment]
Why is the temperature of blood higher than lava 😦

**Comment by Gunner76th** [comment]
As a work around until the issue of blood's temperature is resolved, changing this setting will prevent the issue, however it also disables fire from appropriate sources as well (such as lava)

`        # When true wooden cauldrons will be set on fire if a hot liquid is inside (when Inspirations is installed) [default: true]
        B:woodBurning=true
`

**Comment by Gunner76th** [comment]
This is confirmed to happen with only the following mods installed:
Mantle 1.12-1.3.3.55
Tinkers Construct 1.12.2-2.12.0.135
More Cauldrons 1.4.3

All configs used are default, unedited config files. I have confirmed this issue exists by recreating it in a new single player world using only the mods listed above.
