### ISSUE TITLE
Nether Portal wont light.

### ISSUE THREAD

**Issue by kiwiblueyes** [Darkosto/SkyFactory4Issues#1028]
So I have been trying to make a Neither Portal. I know that the frame is correct (had multiple people look at it and try to light it). I have tried to light it with lava and wood as well the flint and steel. The only thing that happens is the obsidian has fire on it. I ended up using the cake but i would like to have a portal. 

I am using 4.0.5 modpack and the world was sky factory that has one tree and one piece of dirt. It has islands as well but far out.
I am not really for sure how much memory that has been allocated. 

prestige not enabled on my world

Version: 4.0.5

Minecraft Version: 1.12.2

(modded) forge-14.23.5.2831

**Comment by ThePoet444** [comment]
Working as intended. Nether portals are disabled. Check out the mod: TelePastries.  (IE: Go bake a cake :) )

**Comment by sk2048** [comment]
ThePoet444 is correct
