### ISSUE TITLE
Ability to recombine slabs

### ISSUE THREAD

**Issue by 3nforcer** [Darkosto/SkyFactory4Issues#103]
Noticed slabs can't be recombined back into blocks (ie 2 stacked oak slabs = 1 oak plank) but didn't know if it was intended or just something to be worked on.

**Comment by Darkosto** [comment]
@justinrusso may have some tools left over from sevtech to set this up much quicker than I can.

**Comment by Darkosto** [comment]
Added in and will be released in next pack update. Thanks!
