### ISSUE TITLE
Sky Factory 4 Crash on Forge Finishing.

### ISSUE THREAD

**Issue by Gamekidcap** [Darkosto/SkyFactory4Issues#1036]
Game client crashes after loading SF 4 modpack. Once the forge client finishes doing its thing, the client crashes. This started after making a stone jetpack and attempting to open a chest. subsequent crashes occur after attempting multiple times.

Once I start the client and have the forge finish sorting the mods, the minecraft menu will crash and return me to the launcher. The text says "It looks like you're using an unsupported modified version of the game."

## Logs

* Client/Server Log: https://pastebin.com/ds3tXnEN
* Crash Log: https://pastebin.com/4gw4seMG

* Preset: Skyfactory 4
* Prestige: Enabled
* Modpack Version world created in: SF 4 v14.23.5.2831
* Additional Content Installed: None

## Client Information

* Modpack Version: SF 4 v14.23.5.2831
* Java Version: 1.8.0_51
* Launcher Used: Twitch TV
* Memory Allocated: 514807440 bytes (490 MB) / 3193962496 bytes (3046 MB)
* Server/LAN/Single Player: Single Player
* Optifine Installed: True
* Shaders Enabled: False

**Comment by sk2048** [comment]
This looks like a vanilla issue caused by the version of LWJGL used to power version 1.12.2 of Minecraft. You cannot bind non-standard keys e.g. additional mouse buttons, or you will experience this crash. 

Delete your options.txt file and restart the game.

**Comment by Gamekidcap** [comment]
That was the problem. Thx, Mr/Ms. sk2048.
