### ISSUE TITLE
Hello game???

### ISSUE THREAD

**Issue by loliconxdd** [Darkosto/SkyFactory4Issues#1039]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: latest
* Java Version: 1.8.0
* Launcher Used: AT launcher
* Memory Allocated: 
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:
![2019-05-30_15 05 23](https://user-images.githubusercontent.com/51015136/58615045-b01b9080-82ec-11e9-89c5-7f6b40dc7304.png)
![2019-05-30_15 05 26](https://user-images.githubusercontent.com/51015136/58615051-b3af1780-82ec-11e9-8b8e-50dcfcc64398.png)

**Comment by ThePoet444** [comment]
Change the name and you should be able to engrave it.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/Darkosto/SkyFactory4Issues/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
