### ISSUE TITLE
primitive crafting vs normal crafting ender dragon module

### ISSUE THREAD

**Issue by jaredlll08** [Darkosto/SkyFactory4Issues#104]
![image](https://user-images.githubusercontent.com/5553605/50930145-d9d03a00-1467-11e9-8086-f5f33a92d2a7.png)
![image](https://user-images.githubusercontent.com/5553605/50930155-e48acf00-1467-11e9-8bf3-18606c8579ee.png)

Also using the dragon egg in the primitve crafting did not consume the dragon egg

**Comment by Tschipp** [comment]
I will look into it on the weekend.

**Comment by jaredlll08** [comment]
Seems to be "fixed" or atleast the recipe has been removed.
