### ISSUE TITLE
Nether terrain generation is not consistent

### ISSUE THREAD

**Issue by timotheusd** [Darkosto/SkyFactory4Issues#1041]
## Bug Report

Nether terrain generation is inconsistent

## Expected Behaviour

as I understand it, the terrain generation in the nether should resemble tendrils. in the "Lost Cities" mode, nether terrain generation appeared to be Vanilla

## Possible Solution

make nether generation consistent across game types

## Steps to Reproduce (for bugs)

1. open "Lost cities" game type and go to nether, then go back to main menu
2.open "Lava Factory" game type and go to nether, compare terrain generation

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: "Lava Factory" vs "Lost Cities"

* Prestige: Yes

* Modpack Version world created in: 4.0.3

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.3
* Java Version: version 8 update 25
* Launcher Used: twitch
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Single player
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Darkosto** [comment]
This is not a bug. Every world does not generate the same nether. The Lost Cities world type nether generates as intended.
