### ISSUE TITLE
Shift-click any recipe in a pattern for AE2 autocrafting 

### ISSUE THREAD

**Issue by ivohuisjes** [Darkosto/SkyFactory4Issues#1048]
Allow creating AE2 patterns for any recipe, without the requirement to have all the items in the recipe. just shift-click using JEI

## Context
When you are making a pattern for AE2 autocrafting, you must have all the items used in the recipe. Often you don't have all the items, which is a hastle to create a pattern.

From the mod author: "This mod removes that functionality and allows the player to use JEI's transfer system (the [+] button) to create patterns whether or not the player possesses the items required by the recipe."

Example from Direwolf20's lets play:
https://youtu.be/Mg58QrJyCHo?t=19m32s

## Mod Details
* Name: Just Enough Energistics (JEE)
* CurseForge Link: https://minecraft.curseforge.com/projects/just-enough-energistics-jee

**Comment by ktole1999** [comment]
then just wait till you have all the items.

**Comment by FireJadian** [comment]
Should probably change the issue title to make it clear that this is a feature request (mod addition) rather than a problem with the modpack.

**Comment by ichbinonline** [comment]
For this function you have to install ae2stuff which brings extra stuff such as a pattern encoder.....or even better JustEnoughEnergistics, with this mod you can you use shiftrightklick on ae2consoles.

**Comment by mkleiman312** [comment]
AE2Stuff Pattern Encoder.

**Comment by Mementh** [comment]
> 
> 
> AE2Stuff Pattern Encoder.

this is the correct answer.. it does what you want :)

**Comment by justinrusso** [comment]
You can use the AE2Stuff pattern encoder for this if you want this feature.
