### ISSUE TITLE
I need help with the Launch Configuration Not Saving

### ISSUE THREAD

**Issue by LethalLocust** [Darkosto/SkyFactory4Issues#1049]
My computer monitor is 1920x1080 and it doesnt save the fact that i changed it in the launch options and continues with a resolution way smaller so i cant see anything thats in my inventory when i open one of the enlarged chests. And I keep on trying to deligate 8GB of RAM so my game doesnt lag but it keeps bringing it back to Xmx3228m whenever i load up instead of the Xmx8628m that Im requesting for it to deligate. Plz Help and ty.

**Comment by ktole1999** [comment]
this is a launcher issue not a pack issue. might ask for help in discord.

**Comment by sk2048** [comment]
Really not enough details here. Taking a wild stab at your setup.. Twitch launcher resets the profile when it starts whichever Mojang launcher you specify (use jar launcher and up to date java). You can change both assigned RAM and display settings in Twitch App -> Settings -> Minecraft.
