### ISSUE TITLE
bounding blocks glitch and won't break

### ISSUE THREAD

**Issue by Syrianguy2** [Darkosto/SkyFactory4Issues#1052]
![bug](https://user-images.githubusercontent.com/51285341/58758832-4959cb00-84d6-11e9-9243-73976878b81b.png)

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
Not enough detail here to consider this a bug report - you have not told us how these blocks ended up in the world.

To remove them, use `/setblock`
