### ISSUE TITLE
Wither Crumbs crash on server startup with 4.0.5 server

### ISSUE THREAD

**Issue by Alacard** [Darkosto/SkyFactory4Issues#1056]
## Bug Report
Server Crash on startup with a fresh install

## Steps to Reproduce (for bugs)
1. Download/Extract SkyFactory 4 - 4.0.5 server files
2. Run Install
3. Run ServerStart
4. Agree to eula
5. Run ServerStart

## Logs
Crash Log: https://pastebin.com/ndPaYrzX
Server Log: [debug.log](https://github.com/Darkosto/SkyFactory4Issues/files/3245925/debug.log)

## World Information
* Preset: generator-settings={"Topography-Preset":"ObservaTree"}
* Prestige: disabled

## Server Information
* Java Version: 1.8.0_171
* Operating System: Linux
* Hoster/Hosting Solution: Self

**Comment by sk2048** [comment]
This is an intermittent issue that I have been unable to reproduce (seen previously and assumed to be isolated to #962) - where did you download the server files?

The issue relates to the custom withers config in `config/WitherCrumbs/CustomWithers.json`

Some users seem to have this initialised to `[]` - an empty JSON array, though the mod is expecting a JSON object, an empty object would be denoted by `{}`

To fix your install, replace the contents of the config file mentioned above with `{}` - or delete it and hope it regenerates correctly.

**Comment by Alacard** [comment]
> This is an intermittent issue that I have been unable to reproduce (seen previously and assumed to be isolated to #962) - where did you download the server files?

I downloaded the files from https://minecraft.curseforge.com/projects/skyfactory-4/files

> The issue relates to the custom withers config in `config/WitherCrumbs/CustomWithers.json`
> 
> Some users seem to have this initialised to `[]` - an empty JSON array, though the mod is expecting a JSON object, an empty object would be denoted by `{}`
> 
> To fix your install, replace the contents of the config file mentioned above with `{}` - or delete it and hope it regenerates correctly.

That fixed the problem (edited the file and replace the "[]" with "{}"), thank you for everything you done for the minecraft community.

**Comment by sk2048** [comment]
Right, no problem with the source of your server files so there's something more subtle going on here. Glad it worked though!
