### ISSUE TITLE
Game freezing on world creation when Project EX is installed.

### ISSUE THREAD

**Issue by Furious1964** [Darkosto/SkyFactory4Issues#1059]
## Bug Report
Adding Project EX to Modpack freeze the game on world creation.

## Expected Behaviour
I expected it to run normally...it didn't.

## Possible Solution
Disabling Project EX.

## Steps to Reproduce (for bugs)
1. Add Project EX.
2. Launch game and start world.

## Logs
https://pastebin.com/p1QaYMpQ

## World Information
Void World
* Preset:
* Prestige: Yes
* Modpack Version world created in: 4.0.5
* Additional Content Installed:
EnviromentalTech
EnderIO
Equivalent Integrations
Expanded Equivalence
Ender Rift
Fast Leaf Decay
Mekanism Tools
Optifine
Project RED (all except World)
Project EX
Project Intelligence
ProjectE Integration
Thaumcraft
Thaumic Equivalence
Thaumic Inventory Scanning
Thaumic JEI
Thaumic Terminal
Thaumic Tinkerer
Tinker IO
Tinker JEI
Advanced X-Ray (for SP ONLY)

*NOTE* All mods run perfectly except when adding Project EX, which freezes the game on world creation.

## Client Information
* Modpack Version: 4.0.5
* Java Version: 1.8.0_211
* Launcher Used: Twitch
* Memory Allocated: MAX 12288MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

Game freezes as soon as I create a world when I have Project EX installed. It doesn't freeze when it's disabled and all the new added mods work and cause no issues.

Can you let me know when is the cause, please?

**Comment by sk2048** [comment]
We do not offer support for modified packs; we're busy enough supporting the default install.
