### ISSUE TITLE
JEI not showing all recipes

### ISSUE THREAD

**Issue by TGlees45** [Darkosto/SkyFactory4Issues#1065]
All i know is that the JEI won't show all the recipes. I have no idea for a solution

**Comment by sk2048** [comment]
Not every item has a recipe. Not every recipe is unlocked in all world types. Some recipes are locked if you're playing prestige.

There's not enough information here to have any idea what your issue might be.

**Comment by TGlees45** [comment]
sorry, I've never used this website. What information do you need?
