### ISSUE TITLE
Cyclic's Auto Crafter ruined Jared's life.

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SkyFactory4Issues#107]
The Cyclic auto crafter has two realllllllly huge issues. 

1. If the recipe uses an item with durability, the item must have the full durability to be used. For example, the Prudentium Essence recipe uses an infusion crystal. If the infusion crystal is damaged, it can not craft the item. This recipe works when the player tries to craft it. 
2. If the recip uses an item with durability, and the item has the full durability, it is completely consumed rather than being damaged. The same example from the first issue can be used. Normally crafting with an infusion crystal causes the item to become damaged and lose durability, but with the auto crafter it will completely use the crystal.

**Comment by Darkosto** [comment]
These are Cyclic issues that would need to be reported to the dev of Cyclic since this is a mod issue.

@Lothrazar

**Comment by Lothrazar** [comment]
Fix on the way for durability, should address both. Only tested with essence so far

![jared](https://user-images.githubusercontent.com/621529/51511839-c0a88100-1db7-11e9-8105-6b35984835b0.gif)

**Comment by darkhax** [comment]
@Darkosto Sorry, I thought you wanted all the bugs here so you had an idea of what was going on. Will post directly to the mod issue trackers moving forward. Would you still like a copy of the issue linked here?

**Comment by triffman33** [comment]
It could be fixed temporarily by making the crafting recipe create with 1 less duribility instead of full i think

**Comment by sk2048** [comment]
This was resolved before the pack was released, are you experiencing it now @triffman33?

**Comment by triffman33** [comment]
Woops, been setting up a server so was looking through all the issues from the beginning :P probably best to close the ones that're resolved  ^_^

**Comment by sk2048** [comment]
It probably just got overlooked, closing it now.
