### ISSUE TITLE
Optifine Won't Let Game Start Up

### ISSUE THREAD

**Issue by ZachTGC** [Darkosto/SkyFactory4Issues#1073]
**Bug Report:**
Trying to fix the game freezing up a lot by getting Optifine, but Optifine doesn't let the game even start. 

**Logs:**
Crash Log: [https://pastebin.com/qHcfJ0Xx](url)

**Java Version:**
1.8.0.151

**Launcher Used:**
Twitch

**Memory Allocated:**
4470MB

**Optifine version:**
OptiFine_1.12.2_HD_U_D3

**Comment by sk2048** [comment]
That's a really old version of Optifine, try 1.12.2_HD_U_E3 or E4pre4

**Comment by ZachTGC** [comment]
Thanks sk2048, I wasn't aware a newer version existed. The game has opened once again.
