### ISSUE TITLE
Bottoms Up is broken

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SkyFactory4Issues#108]
I have a black hole tank with 2147483647 (which is the actual max value). Looking at your config script in triumph you have the max set to `2147483000` which is rounded and not correct. 

![image](https://user-images.githubusercontent.com/2250798/51446308-911d4a00-1ccd-11e9-95d3-cf77915f6ac4.png)

**Comment by Darkosto** [comment]
Fixed, requires at least 2147483000mb
