### ISSUE TITLE
Morpheus-1.12.2-3.5.106 declares a dependency on Forge-14.23.5.2808

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#110]
During startup, Morpheus is declaring a dependency on a newer version of Forge (14.23.5.2808), 14.23.5.2807 is included in the pack.

SkyFactory4-0.2.6

**Comment by Darkosto** [comment]
I forgot to update forge in the tester version, you'll have to update manually for the time being. I'll make sure to update next time. Thanks!
