### ISSUE TITLE
Placing a AE2 crafting terminal into another AE2 crafting terminal, crashes the pack out completely

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#118]
Placing a AE2 crafting terminal into a AE2 crafting terminal , crashes the pack out completely. This was with trying to make the wireless universal with crafting, so the wireless grid + the crafting grid
I crashed the pack doing this, and so did Mhykol - he was going to report this issue.

**Comment by JackRuby1** [comment]
Crash report: https://pastebin.com/BTZBec6k

**Comment by Darkosto** [comment]
Posted the issue over here at: https://github.com/ExtraCells/ExtraCells2/issues/638

**Comment by JackRuby1** [comment]
Fixed with a patch mod.

**Comment by orblazer** [comment]
Hello,
I have try this issue with the last build of ExtraCells 2 (2.6.3a9) and this is perfecly work.

For mods i have SkyFactory 4 (V4.0.3) and i have replace ExtraCells 2 (2.6.2 > 2.6.3a9)
And i have add WirelessCraftingTerminal (3.11.88),  p455w0rdslib (2.1.44) and  AE2WTLib (1.0.6)

Thanks.
