### ISSUE TITLE
Cannot craft Flux Network items in AE2 storage system

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#119]
Flux network items are no craftable in the AE2 system, crafting table works perfectly.

**Comment by Darkosto** [comment]
Hey @justinrusso this may be because of containers not having stages? We need to figure this out.

**Comment by justinrusso** [comment]
Ah yeah... Thats likely the issue.

**Comment by mhykolcom** [comment]
Also found these other mods having the issue:
-- Statues mod (Core only - maybe Deep Mob Learning?)
-- Mystical Agriculture

**Comment by justinrusso** [comment]
Should be fixed!
