### ISSUE TITLE
Many errors on server when placing a shipping container

### ISSUE THREAD

**Issue by darkphan** [Darkosto/SkyFactory4Issues#12]
Server logs go nuts: https://gist.github.com/darkphan/50fa74aff177a50259a89dd8b7f69163

Also can not seem to break the shipping container properly, 

Oh, and placing other containers from the mod seems to crash the server: https://pste.me/#/sqHSg

**Comment by Darkosto** [comment]
I think we're good on this, closing for now! Thanks!
