### ISSUE TITLE
DeepMobLearning doesn't recognize WitherCrumbs Withers as actual Withers

### ISSUE THREAD

**Issue by mhykolcom** [Darkosto/SkyFactory4Issues#120]
When holding the Deep Mob Learning device with a Wither card in it killing WitherCrumbs withers doesn't give credit for killing withers.  Likely due to the WitherCrumbs wither having a different mob id that needs to be added to Deep Mob Learning

**Comment by Darkosto** [comment]
Should be fixed in the next version. Keep me posted if you find any more mobs that do not trigger the device.
