### ISSUE TITLE
You're a Hairy Wizzard structure is missing floor and walls

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#123]
![2019-02-12_19 24 18](https://user-images.githubusercontent.com/29290246/52677468-f397ed80-2efb-11e9-95cb-ce78c3d6063f.png)

SkyFactory4-0.2.8

**Comment by MongoTheElder** [comment]
This is the log when creating the world type.

[latest.log](https://github.com/Darkosto/SkyFactory4Issues/files/2858536/latest.log)

**Comment by darkphan** [comment]
Thaumcraft was removed. Captain Q is making a new structure that is Astral based and it will replace that world type/structure

**Comment by Darkosto** [comment]
Yep, Thaumcraft was removed and I did not remove this world type just yet. It's going to be replaced with another type as soon as it's ready. Thanks!
