### ISSUE TITLE
Game crash entering hunting dimension - v0.3.0

### ISSUE THREAD

**Issue by mhykolcom** [Darkosto/SkyFactory4Issues#124]
Full crash log:
https://pastebin.com/K0uKjsAj

**Comment by mhykolcom** [comment]
More information on this - it was first time entering hunting dimension.  Going in every time after that caused no issues.

**Comment by Darkosto** [comment]
We'll have to try this out to see if it still exists. I haven't run into this personally so it's possible it was a 1 time crash?

**Comment by TheCodedOne** [comment]
Has this been reproducible in the same dimension, and other dimensions?

**Comment by Darkosto** [comment]
I haven't been able to replicate this after some testing. I'm going to close this and we can reopen if it happens again.
