### ISSUE TITLE
[Suggestion] Avoid getting stranded in the Nether

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#125]
Chunk Norris:
If entering the nether using a vanilla portal, there is no corresponding portal in the nether leaving the player stranded. The advancement text doesn't warn that Overworld cake would be needed when using a vanilla portal.

Suggest altering the advancement text to provide a warning or generating the portal in the nether chunk.

SkyFactory4-0.2.8

**Comment by Darkosto** [comment]
Hey @Blargerist is there any way we can confirm vanilla portals will show up on the other side?

**Comment by Blargerist** [comment]
Not if you're capturing teleports. You could add a nether portal to the structure itself, or I could try to find a workaround.

**Comment by Darkosto** [comment]
I think we've solved this with the new cake system. Although, players will still probably try and build a vanilla style portal which isn't covered still. I wonder if we need to do something about that?

**Comment by justinrusso** [comment]
I feel like we should...

Maybe we can get something to prevent the portals from forming?

**Comment by justinrusso** [comment]
Resolved with the new cakes system.
