### ISSUE TITLE
Apotheosis anvils not compatable with Cooking With Blockheads Cow in a Jar recipe

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#126]
Anvils from the Apotheosis mod that replace vanilla anvils do not trigger creation of Cow in a Jar in Cooking For Blockheads. Vanilla anvils work OK (disabling Apotheosis).

Reported to Apotheosis issues: https://github.com/Shadows-of-Fire/Apotheosis/issues/5

SkyFactory4-0.2.8
Apotheosis-1.12.2-1.0.0 (3)
CookingForBlockheads_1.12.2-6.4.69

**Comment by Shadows-of-Fire** [comment]
Resolved as of Apotheosis 1.4.1

**Comment by Darkosto** [comment]
Looks to be fixed in the newest pack version. Thanks!
