### ISSUE TITLE
[Suggestion] Remove Animal Seeds from market

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#131]
The ability to get animal seeds in the market make the animal advancement way too easy. 

SkyFactory4-0.2.8

**Comment by Darkosto** [comment]
I made a compromise: I removed all the enemy seeds but left in the passive. I also adjusted a couple of the costs to be higher. This should accomplish what I was looking to do with the market but not make the advancement too easy. Although, I did make the advancement simply to alert players of their existence. Will be fixed for next version! Thanks!
