### ISSUE TITLE
Unable to progress in Twilight Forest when Android

### ISSUE THREAD

**Issue by mhykolcom** [Darkosto/SkyFactory4Issues#133]
Due to not being able to eat food as an Android with the Zero Calories feature unlocked you cannot progress in Twilight Forest since you can't eat the Meef Stroganoff to clear that advancement.

**Comment by Blargerist** [comment]
All Twilight Forest advancements other than twilightforest:experiencement_115_115 have been changed from consuming the food items to just having them in your inventory.
