### ISSUE TITLE
Can't left click Minecraft Gunpowder into BDS&M crate

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#137]
Left clicking with gunpowder in main hand doesn't place it into an empty BDS&M crate. Piping and hoppering the item works. Once gunpowder is in the crate, clicking with an empty hand puts any additional gunpowder from your inventory into the crate as expected.

When clicking, there is no main hand animation, indicating that maybe it is an issue with gunpowder and not the crate. Is this interference with the Fused mod?

SkyFactory4-0.2.8

**Comment by darkphan** [comment]
This is because of the Fused mod, which lets you place gunpowder down on the ground light redstone, and you can light it with flint and steel.

**Comment by Darkosto** [comment]
I talked with Jared and we decided to remove the mod which should fix this interaction. Thanks!
