### ISSUE TITLE
Can't exit any world, MC just hard locks up and needs to be force closed.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#139]
I can't seem to exit any worlds without MC just locking up and forcing me to close it, this is not with open to Lan. This is happening with old worlds and new.

**Comment by MongoTheElder** [comment]
Not experiencing any issues exiting new worlds (SF4, Compactsky, ObservaTree) with and without Prestige enabled.

**Comment by JackRuby1** [comment]
Now it's not doing it anymore? darkoWut
