### ISSUE TITLE
Cancel buttons not functioning as-intended on Create World menus

### ISSUE THREAD

**Issue by 3nforcer** [Darkosto/SkyFactory4Issues#141]
If you perform the following:

SF4 Main Menu > Single Player > Create New World > Cancel (which takes you back to Single Player menu listing any existing worlds you already have) choosing Cancel again (to get back to the SF4 Main Menu) it takes you back into the Create New World menu screen.

Pressing Esc/Escape will always close out/go back in any menu you're in, all the way back to the SF4 main menu

**Comment by Blargerist** [comment]
Fixed.
