### ISSUE TITLE
Advancements based on the root parent are not registering for the SF4 tree

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#142]
Advancements that have addParent("sf4:age1/root") as the parent are not triggered - shows the root advancement has not being completed (see image)
Affected advancements:
Dir-tree, Captain Hook, Dirty Dancing, Air Fryer, I Love Lucy, Bubble Bubble, and Sticky Keys

![2019-03-21_17 45 23](https://user-images.githubusercontent.com/29290246/54787117-29b64480-4c01-11e9-9894-6883e149823f.png)

Maybe setting the root criteria to "minecraft:impossible" makes this, um, impossible?

SkyFactory4-0.3.3

**Comment by Blargerist** [comment]
sf4:age1/root is now properly completed by an initial function. Will make the advancements on the page actually able to be completed. 😛
