### ISSUE TITLE
Cannot fill More Cauldron Cauldron's via Water Bottles.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#144]
If you try to fill a More Cauldron's Cauldron with a water bottle, it makes the sound and pops the bottle like it filled it, but doesn't use the water in the bottle, nor does it put any water in the cauldron. This is in survival, in creative you can fill it with a water bottle.

**Comment by JackRuby1** [comment]
This is in survival, in creative you can fill it with a water bottle.

**Comment by Darkosto** [comment]
Still waiting to see if @Mrbysco found a fix for this as it's still not working correctly.

**Comment by Darkosto** [comment]
Fixed! Should be available next version.
