### ISSUE TITLE
Can not craft BDSM drums or metal crates.

### ISSUE THREAD

**Issue by darkphan** [Darkosto/SkyFactory4Issues#153]
Unable to craft a BDS&M drum in Simple Storage Network. See screenshots:

Crafting Station: https://i.imgur.com/jNOKJ9a.png

Storage Request Table: https://i.imgur.com/FZquRfJ.png

**Comment by darkphan** [comment]
Correction, can not craft in the crafting station as well.

**Comment by JackRuby1** [comment]
I just crafted a drum in a crafting station on the server.

**Comment by darkphan** [comment]
Odd, it would not let me pull the drum out of a crafting station.

**Comment by JackRuby1** [comment]
I cannot craft the shipping container in SSN now https://gyazo.com/4c1ad4e13483d3e37e505faa946996a1
or pull the finished product from the crafting table

**Comment by JackRuby1** [comment]
Somehow metal crates just broke just now. https://gyazo.com/b882b0a1d749296ce467bacc8a67ae34 I crafted 3 in SSN, then the recipes no longer worked, didn't log out in that time.

**Comment by Darkosto** [comment]
I believe this issue is fixed. If it happens again please let me know and reopen the issue.

**Comment by VallenFrostweaver** [comment]
Can't craft shipping container if the metal crate ingredient has been placed previously. Fresh made metal crate that wasn't placed is fine to use to craft it. Checked with BDSM and they state it's a SF4 issue.
![bug](https://user-images.githubusercontent.com/13642054/56821146-8088ec80-6845-11e9-9c8c-4e696d02a995.png)

**Comment by OldManCraft** [comment]
This is still an issue on server. 4.0.5
