### ISSUE TITLE
Eating 115 Everyday, 115 Years, Forever Advancement triggering when not having Twilight Forest unlocked, I ate a baked potato.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#154]
Eating 115 Everyday, 115 Years, Forever Advancement triggering when not having Twilight Forest unlocked, I ate a baked potato.
By gaining this advancement, I have unlocked the Twilight Forest tab in the advancements
https://gyazo.com/c9e40e7aa2324549d9f71d3ed8fdbaf7

**Comment by Blargerist** [comment]
Fixed.
