### ISSUE TITLE
Crafting table item repair can eat other items

### ISSUE THREAD

**Issue by onlybentley** [Darkosto/SkyFactory4Issues#158]
When repairing an item in a crafting table, and using the needed repair item, any item placed additionally into the crafting area doesn't remove the repaired item from the export slot and will still consume any items in the crafting grid upon repair.

**Comment by JackRuby1** [comment]
Also happens in the personal crafting grid. https://gyazo.com/8f972ce46975285bda7d97028d18b55d

**Comment by Darkosto** [comment]
This is a @blakebr0 issue. I can confirm it happens still.

**Comment by BlakeBr0** [comment]
Should be fixed in release 2.1.3

**Comment by Darkosto** [comment]
Will add into next update

cc: @justinrusso and @sk2048
