### ISSUE TITLE
[Question] Cobalt/Ardite missing in the Lost Cities preset nether.

### ISSUE THREAD

**Issue by Blargerist** [Darkosto/SkyFactory4Issues#159]
The nether in the Lost Cities preset doesn't appear to contain cobalt/ardite. Is this intended?

**Comment by Blargerist** [comment]
Yes, because we can't do anything about it.

**Comment by fuelhauler** [comment]
Can we get a warning for this on the creation screen so someone doesn't get to ardite and cobalt saplings  being the only thing left in the Age of Farming before finding this out?

**Comment by fuelhauler** [comment]
And Darkosto indicated that the Age of Exploration achievements for the 2 ores shouldn't appear with Lostcities but they do. Wouldn't have helped me if they hadn't appeared though because I was following JEI for the respective saplings.
