### ISSUE TITLE
Dimensional Edibles Cakes keep sending me back to spawn on server

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#168]
Dimensional Edibles Cakes keep sending me back to spawn on server, is this the way it's suppose to be, should it not be the player's personal spawn point, aka a bed?

**Comment by Darkosto** [comment]
@Blargerist is it possible the player can be sent back to their spawn point instead of world spawn? It may solve potential multiplayer issues.

**Comment by JackRuby1** [comment]
fixed thanks @Blargerist!
