### ISSUE TITLE
Parabox energy cost may be too low.

### ISSUE THREAD

**Issue by Blargerist** [Darkosto/SkyFactory4Issues#169]
It currently takes 20 minutes for each point, and requires 100k FE + 100k FE for each point generated. 20 minutes is 72000 ticks. That's 1.388888888888889 FE/t.

A piece of coal in a Combustion Generator produces 32000 FE.
A bucket of lava in a Geothermal Generator produces 30000 FE.

**Comment by Darkosto** [comment]
updated to a higher value. Should be a bit better now!
