### ISSUE TITLE
Mega Torch Mob Spawns

### ISSUE THREAD

**Issue by onlybentley** [Darkosto/SkyFactory4Issues#174]
Androids still spawn like crazy within the radius of the torch in Lost cities world type.  Headcrumbs maybe as well but unsure of those as much as the Androids.

**Comment by Electrofried** [comment]
Just to update that this is still an issue as of version 4.0.2
Androids are not affected by the no spawning radius of the mega torch and will spawn in the darkness.
This is world type independant.

**Comment by justinrusso** [comment]
Going to continue this in #253
