### ISSUE TITLE
Both Cookie Advancements are unobtainable.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#185]
I tried to do the cookies in the cookie jar advancement and it didn't trigger, blargerist tried it as well and nothing happened. I then tested on single player and neither cookie advancement triggered.

**Comment by Darkosto** [comment]
Fixed!

**Comment by JackRuby1** [comment]
@Darkosto was this fixed in version 0.3.13? If so, it's still broken.

**Comment by Darkosto** [comment]
This should have been fixed in the latest dev build. I'll check it out.

**Comment by JackRuby1** [comment]
Blargerist looked at one of them last night, I believe he pushed a fix? Might need to check.

**Comment by JackRuby1** [comment]
Cookie one works, but I haven't tried the Singularity version yet.

**Comment by JackRuby1** [comment]
They both work now, thank you! 👍
