### ISSUE TITLE
Cannot use resin or acorns from Bacon, Cookie, and Donut trees to make liquid (Amber is fine)

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#186]
The resin and acorns from Bacon, Cookie, and Donuts trees are not able to be melted down by themselves for liquid, it doesn't match the rest of the trees resin and acorns.

**Comment by justinrusso** [comment]
Fixed in Darkosto/SkyFactory4@525cdc2ca4115c0fa35b85c4e5305fec0e7f19ea
