### ISSUE TITLE
Advancements "Ore Processing" and ""Ore Processing Part 2" need setRequirements("any")

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#19]
Both "Ore Processing" and "Ore Processing Part 2" in Age of Enhancement want either the Porcelain or Seared Brick versions of the Melter and Tank but are missing setRequirements("any") (unless you want both then the text should be updated)

SkyFactory4-0.0.11

**Comment by Darkosto** [comment]
Added in! Thanks!
