### ISSUE TITLE
Advancement "Cobblestone Generator" in Age 1 doesn't trigger when inventory is full of cobblestone

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#20]
I have tried different variations of filling my inventory with cobblestone (Just the 27 stacks in the main inventory as the advancement says, filling the hot bar as well, moving one row from inventory to hot bar) and the advancement is being stubborn and won't trigger

SkyFactory4-0.0.11

**Comment by Darkosto** [comment]
Fixed this by converting the advancement to filling a vanilla chest and opening it. Should be good. Thank you!
