### ISSUE TITLE
ProjectE not unlocked, but can still interact with transmutation table + put items in and pull out even though I can't tell what has emc.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#202]
ProjectE not unlocked, but can still interact with transmutation table + put items in and pull out even though I can't tell what has emc.

**Comment by justinrusso** [comment]
I think this isn't really an issue. It encourages working as a team to obtain different goals and still be able to use stuff their teammates have unlocked, while also still depending on them for the crafting or information needed to use them.
