### ISSUE TITLE
Making filled Filing Folders is making Air Filled ones.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#203]
Making filled Filing Folders is making Air Filled ones in SSN, personal crafting grid, and vanilla crafting table. AE2, tinkers' crafting station work as normal.

**Comment by Darkosto** [comment]
These need to go to the dev. At this point it's taking more time because I have to relay them.

**Comment by JackRuby1** [comment]
Fixed in realfilingcabinet-1.12.1-0.1.80
