### ISSUE TITLE
Advancements in the Compact Machine tab not honoring parentage completion

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#21]
With the root advancement not completed, still getting credit (and rewards) for the later advancements that should be dependent on the root.

![2018-09-30_13 13 18](https://user-images.githubusercontent.com/29290246/46260366-dc0f1980-c4b2-11e8-8152-e3cc94f6b83c.png)

SkyFactory4-0.0.11

**Comment by Darkosto** [comment]
Should be fixed, I happened to fix this up yesterday. You'll need to be in only that world type to complete. Thanks!
