### ISSUE TITLE
Crashing when clicking on Singleplayer

### ISSUE THREAD

**Issue by zippoking** [Darkosto/SkyFactory4Issues#210]
When i start the pack and click on the Singeplayer button, the pack crashes.

Here is the crashlog: https://pastebin.com/GaREGXHN

**Comment by Loine** [comment]
Same here.

**Comment by Wolosmedrah** [comment]
Here is mine crashlog, same problem https://pastebin.com/tUxTdmE9

**Comment by MJRLegends** [comment]
Darkosto knowns seem to be a syncing issue, so works for some people and some people it doesn't. Time should fix it once curseforge server all sync up

**Comment by JohnAxae** [comment]
Replacing Topography 1.4.4 with 1.4.3 fixes this issue.

**Comment by sk2048** [comment]
We know what is causing this, it will be fixed as soon as is possible.

**Comment by JohnAxae** [comment]
Topography 1.4.5 is working!

**Comment by zippoking** [comment]
I downgraded to 1.4.3 as suggested and it fixed it for me.
