### ISSUE TITLE
crashed with prestige by hitting p

### ISSUE THREAD

**Issue by Studio528** [Darkosto/SkyFactory4Issues#214]
I hit "P" and my game crashed. pretty sure that's the button to open the prestige menu. it's not a ram issue, I have 8GB allocated.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by Studio528** [comment]
ah, I clicked the link in darko's discord, which did not give me any template. I will redo this now
