### ISSUE TITLE
Broken main menu texture on linux

### ISSUE THREAD

**Issue by cpw** [Darkosto/SkyFactory4Issues#216]
## Bug Report

The main menu should have a graphic. It does not. It has missing texture.

## Expected Behaviour

It should have a graphic.

## Possible Solution

BG_FULL.png is not a valid resource name, and will never work on case sensitive filesystems like Linux and Mac.

## Steps to Reproduce (for bugs)

1. Load pack in linux.
![2019-04-15_19 35 22](https://user-images.githubusercontent.com/1217211/56172032-a72d6480-5fb5-11e9-91b8-c1676245dada.png)

**Comment by sk2048** [comment]
Duplicate #211
