### ISSUE TITLE
OreExcavation won't work

### ISSUE THREAD

**Issue by XDefeatCreepers** [Darkosto/SkyFactory4Issues#219]
## Bug Report
OreExcavation doesn't work with full hunger and proper usage of the mod.

## Expected Behaviour
 Should veinmine an entirety of a tree with proper usage of the mod, but it only mines the single block.

## Possible Solution
Possibly interacting with a different mod.

## Steps to Reproduce (for bugs)

1. Try using OreExcavation as normal.
2. Results?

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 4.0.0
* Java Version: Most recent 64-bit Java
* Launcher Used: Twitch Native (not JAR)
* Memory Allocated: 6GB
* Server/LAN/Single Player: SinglePlayer
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 4.0.0

* Additional Content Installed:

**Comment by sk2048** [comment]
Are you in a world with prestige enabled?

**Comment by XDefeatCreepers** [comment]
Nope

> Are you in a world with prestige enabled?

**Comment by XDefeatCreepers** [comment]
Checked the mod config for OreExcavation, the mod was disabled for some reason.

**Comment by XDefeatCreepers** [comment]
Figured it out, mod was disabled for some reason.
