### ISSUE TITLE
Quartz Block and Quartz Amber have the same recipe using Quartz Acorn/Quartz Resin

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#22]
![2018-09-30_14 02 19](https://user-images.githubusercontent.com/29290246/46260849-88ec9500-c4b9-11e8-8c04-0e3cbd6ae90a.png)

![2018-09-30_14 02 22](https://user-images.githubusercontent.com/29290246/46260850-8d18b280-c4b9-11e8-9bb9-59c87e89838f.png)

The recipe when crafted yields Quartz Block. It looks like Quartz Amber has no current use yet.

SkyFactory4-0.0.11

**Comment by Darkosto** [comment]
Changed to using 9 resin instead, should be good! Thanks!
