### ISSUE TITLE
pack won't load at all the first couple of times.

### ISSUE THREAD

**Issue by fEdlbV9IdW50ZXJ8** [Darkosto/SkyFactory4Issues#222]
## Bug Report

the pack shows incompatibilites when first launching it. it was 17 first, then 14, then none. sorry if i didn't provide the correct crash log files, first time posting here.
## Steps to Reproduce (for bugs)

1. i have a intel i3 2nd gen 2.5ghz processor. i use integrated graphics.
2.re-install the pack from the launcher, and launch it.

## Logs

* Client/Server Log: https://pastebin.com/RyBZEYU8 , https://pastebin.com/jCdkR0aj
* Crash Log:

## Client Information

* Modpack Version: 1.0.1
* Java Version: version 8 update 191
* Launcher Used: Twitch
* Memory Allocated: 8192MB
* Server/LAN/Single Player: single player
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by xerminator** [comment]
Here is your issue most likely
    Java Version: 1.8.0_51, Oracle Corporation
Try updating to atleast 1.8.0_200 .../201 ../202
Most of the mods have been created in a newer java version

**Comment by fEdlbV9IdW50ZXJ8** [comment]
to clarify, the pack loaded properly the third launch, it just showed errors the first few times.
i will update the Java version ASAP. Thank you!

**Comment by sk2048** [comment]
As pointed out above, you should switch your java version to something more recent. 1.8.0_51 is the version bundled with the native launcher, on Twitch you have to switch to the jar launcher to be able to change your java version.

The actual issue you seem to have run into here though seems to be that you managed to start the pack before the download completed. In both logs it complains about missing mods. There are fewer missing mods in the second log. I suspect it was still downloading in the background, by your third attempt it had completed.
