### ISSUE TITLE
Advancement Book Stand breaks instantly and drops nothing

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SkyFactory4Issues#225]
## Bug Report

When breaking the advancement book stand it breaks instantly, and when trying to break it dropped nothing, basically voiding the book
## Expected Behaviour

The block should probably have a hardness or at least drop an item
## Possible Solution

Add a hardness to the stand and make it drop a stand when broken
## Steps to Reproduce (for bugs)

1. Place Advancement Book Stand
2. Try to break it

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 4.0.1
* Java Version: 1.8.0_171
* Launcher Used: MultiMC
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: N/A

## World Information

* Modpack Version world created in: 4.0.1

* Additional Content Installed: N/A

**Comment by ParkerMc** [comment]
Fixed here. https://gitlab.com/parkermc/advancement-book/commit/3cd13a5e6ea853e644df9d4aad294d075cdbf1a3
Version 1.0.3 has the fix and will be out as soon as curse approves it.

Thanks for the report :)

**Comment by Marioluigi7896** [comment]
This seems to be fixed in 4.0.2
