### ISSUE TITLE
Advancements not showing for first page

### ISSUE THREAD

**Issue by TooEze** [Darkosto/SkyFactory4Issues#227]
## Bug Report
Advancements - SkyFactory 4 not completing, with the get it while its hot, wet feet and tree harder advancements not showing on the tree at all

## Steps to Reproduce (for bugs)

1.https://cdn.discordapp.com/attachments/527695342867841024/567539113998286848/unknown.png
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:4.0.0
* Java Version:
* Launcher Used:twitch launcher
* Memory Allocated:8 GB
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information
skiiiilands world type

* Modpack Version world created in: 4.0.0

* Additional Content Installed:

## Server Information
* Java Version:Java SE 12 ?
* Operating System: windows 
* Hoster/Hosting Solution: home hosted

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by sk2048** [comment]
You have added information to this after I closed it. When I closed it, you just had a title.

The solution to your problem is to update to 4.0.1, the completion advancement is fixed in that version.
