### ISSUE TITLE
advancements not appearing for the you win! task on Advancements - SkyFactory 4 page

### ISSUE THREAD

**Issue by TooEze** [Darkosto/SkyFactory4Issues#229]
## Bug Report
the advancements for get it while its hot, wet feet and tree harder are not appearing on my advancements tab, however are required to complete the You Win! advancement for the prestige point. hopefully this is formatted correctly, but there is no way for me to provide a log unless you would like a picture of the advancements page, but it doesnt say that so i dont want to post it if its not a good idea.

## Expected Behaviour
for it to show the advancements and complete them for me.

## Possible Solution
make the advancements show?

## Steps to Reproduce (for bugs)

1.complete all shown advancements on tree
2.see that the final advancement is 52/55 leaving out the 3 listed above

## Logs

* Client/Server Log: i have no logs for this, none are made because just simply nothing is there
* Crash Log: i have no logs for this, none are made because just simply nothing is there

## World Information

* Preset: Skiiiilands

* Prestige: yes

* Modpack Version world created in:4.0.0

* Additional Content Installed:

## Client Information

* Modpack Version:4.0.0
* Java Version: java 8 update 201
* Launcher Used: twitch launcher
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: java 8 update 201
* Operating System: windows
* Hoster/Hosting Solution: hosting through a home server
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by Geerawh** [comment]
https://imgur.com/a/ff1Wosl

**Comment by Geerawh** [comment]
Having same problem

**Comment by sk2048** [comment]
Update the pack to 4.0.1, this is already fixed
