### ISSUE TITLE
[Suggestion] Glassential

### ISSUE THREAD

**Issue by Lykrast** [Darkosto/SkyFactory4Issues#241]
## Context
Among the things Extra Utilities add, there are a couple of great utility glasses, such as glass that makes light, glass that blocks light, glass that only lets players through and so on. This mod adds those glasses (and a few more) and a tool to pick up glass, and that's it.

Since Extra Utilities is not in the pack, and things like dark glass or a glass cutter would be really helpful for people, I'm suggesting this mod. All of its features can also be individually disabled, if anything it adds is already in the pack (such as the clear glass that is provided by TiCon already or the light blocking glass Cyclic and PickleTweaks provide as JackRuby1 said).

## Mod Details
* Name: Glassential
* CurseForge Link: https://minecraft.curseforge.com/projects/glassential

**Comment by JackRuby1** [comment]
PickleTweaks and Cyclic both have a light blocking glass, maybe you should try them out.
