### ISSUE TITLE
Crash in inventory

### ISSUE THREAD

**Issue by ShadowSans55** [Darkosto/SkyFactory4Issues#242]
## Bug Report
Crash when opening inventory

## Expected Behaviour
Whenever I open my inventory and try to do something with it, the entire game crashes

## Steps to Reproduce (for bugs)
1-Open inventory

## Logs
[Crash report](https://pastebin.com/AmU56KfT)

## World Information
* Preset: SkyFactory 4
* Prestige: Enabled
* Modpack Version world created in: 4.0.1
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.0.1
* Java Version: 1.8.0.201 64 bit
* Launcher Used: Twitch Launcher
* Memory Allocated: 7168MB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment]
This looks like a known bug in vanilla Minecraft, have you bound the key to open your inventory (or any other) to a non-standard key, such as a mouse button?

There is a bug in the LWJGL that causes Minecraft to crash if such a key is used.

**Comment by ShadowSans55** [comment]
I'll check my key bindings rn and tell you if it stopped crashing. Thanks!

**Comment by ShadowSans55** [comment]
It seems that it fixed the issue. Thanks again!
