### ISSUE TITLE
[Suggestion] Adding FTB Utilities

### ISSUE THREAD

**Issue by letsgameyoulp** [Darkosto/SkyFactory4Issues#243]
The mod should be added to help the server owners to give the user the safety to create a team and only allow users to build if they are added to the claim.
If you don't like the chunk loading it can be disabled by the config.

Second mod Team islands is an addon to the Ftb Utilities that allows the user to instantly join an island when they create a team. With these islands will be created.

## Mod Details
* Name:FTB Utilities
* CurseForge Link: https://minecraft.curseforge.com/projects/ftb-utilities

## Mod Details
* Name: Team Islands
* CurseForge Link: https://minecraft.curseforge.com/projects/team-islands

**Comment by AshZification** [comment]
This is not an FTB pack, therefore FTB mods won't be added. 
Together Forever was added for teams, and I believe the weirding gadget allows you to control access permissions (I'm not sure about that one though)

**Comment by Explosivee** [comment]
A lot of NON FTB modpacks are using FTBU in their packs, let's face it FTBU is really useful mod for a lot of people, it would improve the gameplay.

**Comment by justinrusso** [comment]
If you really want it, add it. No one is stopping you.

We have a mod that does teams.

We have a mod that controls islands.
