### ISSUE TITLE
Vein Miner Broken

### ISSUE THREAD

**Issue by TomB42376** [Darkosto/SkyFactory4Issues#246]
Vein miner only vein mines 3 blocks including the block you are breaking. When I started up my world Vein miner was working just fine and then I had a break, started up my laptop again and bam it was broken. My brother has had this issue as well on a pc.

**Comment by TSM-Evo2** [comment]
vein miner is not in this pack.

**Comment by Bartman8989** [comment]
He means Ore Excavator. They are virtually the same mod with slight differences.

Would also like to mention that my friend was also experiencing this issue, so I +1 this

**Comment by mcoffma1** [comment]
Default 'Z' Key will change the size of your vein miner, from 0 -> 3x3 -> 5x5....
0 is normal vein miner.

Hope this helped

**Comment by draconickage** [comment]
for me ore excavator doesn't work even if i changed it to 5x5
ive tried rebinding it and using tools to break blocks but nothing works

**Comment by cnordbakk** [comment]
Same for me, doesn't excavate at all no matter what shape or tool.

**Comment by tempme123** [comment]
if you're doing a prestige run you have to unlock ore excavation before you can use it with prestige points

**Comment by Studio528** [comment]
> if you're doing a prestige run you have to unlock ore excavation before you can use it with prestige points

This is correct, if you are in a prestige world, you won't be able to use VeinMiner/OreExcavation
 I also had the problem in a non-prestige world, I reset the size of the mining and it fixed itself.

**Comment by TomB42376** [comment]
Ahh cheers guys. You people are legends.
