### ISSUE TITLE
Carryon conflict with Slab Machines

### ISSUE THREAD

**Issue by Patrick1358** [Darkosto/SkyFactory4Issues#248]
## Bug Report

Picking up the block and having a weird texture, not being able to place down after picking up.

## Expected Behaviour

Placing the full block down and giving the items back.

## Possible Solution

Add the slab crafting tables to the Carryon blacklist for entities/blocks

## Steps to Reproduce (for bugs)

1. Place a "block" of crafting table slabs ( 2 tables on top of each other) and add any item(s) in the crafting table.
2. Pick up the "block" with Carryon.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Skiiiilands

* Prestige: enabled

* Modpack Version world created in: 4.0.1 (latest by this time)

* Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.1 (latest by this time)
* Java Version: 1.8.0.201 (64 Bit)
* Launcher Used: Twitch
* Memory Allocated: 8 Gb (java argument)
* Server/LAN/Single Player: Single Player
* Optifine Installed: no 
* Shaders Enabled: no

**Comment by zigackly** [comment]
Can confirm, also after experiencing this bug with a slab furnace, I executed "/carryon clear" and afterwards placing a furnace slab would consistently crash my game.

**Comment by justinrusso** [comment]
Same as https://github.com/Darkosto/SkyFactory4Issues/issues/233

**Comment by happybandit360** [comment]
I also have discovered this issue with the slab chests
