### ISSUE TITLE
Server crashes when loading official server files

### ISSUE THREAD

**Issue by thejackening** [Darkosto/SkyFactory4Issues#249]
## Bug Report
 The console crashes without loading at all, stating there are library files missing. When looking at the files from the twitch launcher, it appears there IS no file named library at all.

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
