### ISSUE TITLE
Duping infinity sticks in 3 easy steps [0.13]

### ISSUE THREAD

**Issue by Demlou6** [Darkosto/SkyFactory4Issues#25]
1: Have infinity sticks inside a connected storage, have a recipe that uses sticks

https://gyazo.com/60a67a702bfd38353d547f4158969c38

2: ???

3: Click recipe and profit!

https://gyazo.com/d7a2fea2b8c26073a11c7f241fee4ec4

**Comment by Demlou6** [comment]
Here is some more information:

https://gyazo.com/9e54a99e26fbd81d29841a6aa333b6c6 test world, with set up

https://gyazo.com/f22bcd2e83fd73306b2fe99ba12256f3 the initial recipe

https://gyazo.com/7c17368bd80cd6d00c563a3d6e61187c the result

**Comment by Darkosto** [comment]
Should be fixed in new version!
