### ISSUE TITLE
Recipe| Rustic|Wooden Stake

### ISSUE THREAD

**Issue by xxerra** [Darkosto/SkyFactory4Issues#251]
Version 4.0.1
Crafting a Wooden stake from rustic gives a Thin Wall Open from the chinese mod.
![chinese thing](https://user-images.githubusercontent.com/49688983/56222688-c1764980-606c-11e9-86de-120305b7db22.jpg)
![Rustic stake](https://user-images.githubusercontent.com/49688983/56222689-c20ee000-606c-11e9-9aa0-8eb58abf56bd.jpg)

**Comment by remclave** [comment]
Optional potential solution: Make Oak Planks the only source for Chinese Workshop recipes and all other wood-type planks useable by NON-Chinese Workshop recipes.

**Comment by TobyTechGames** [comment]
You can use all wood types to craft the Thin Wall-Wooden so even if you make the planks from rustic you still can't make the Wooden Stake

**Comment by remclave** [comment]
> You can use all wood types to craft the Thin Wall-Wooden so even if you make the planks from rustic you still can't make the Wooden Stake

That's why I was suggesting limiting Chinese Workshop to use Oak Planks so other mods could USE any planks other than Oak Planks...

**Comment by TheKellith** [comment]
Other possible crafting alternates for thin wooden wall could be two vertical lines of wooden plank slabs (same resource cost, just 1 extra step), or setting both to a shaped craft in different columns.

**Comment by remclave** [comment]
This issue has not been fixed in the 4.0.3 version according to the change log... or has it?

**Comment by sk2048** [comment]
It has not. When it is fixed we will close the issue and likely include a reference to the commit in which the fix was made.

**Comment by Wolf68k** [comment]
My temp fix
recipes.remove(<rustic:crop_stake>);
recipes.remove(<chineseworkshop:thin_wall_w> * 18);
recipes.addShaped(<chineseworkshop:thin_wall_w> * 18, [[null, null, <ore:plankWood>],[null, null, <ore:plankWood>], [null, null, <ore:plankWood>]]);
recipes.addShaped(<rustic:crop_stake>, [[<ore:plankWood>, null, null],[<ore:plankWood>, null, null], [<ore:plankWood>, null, null]]);
The Rustic stakes are 3 planks down on the left, while the Thin Walls are on the right.

**Comment by TheKellith** [comment]
TBH, I just cheated in a stack, then threw a stack of logs to the void. The way my tree resources are, wood's not hard to get
