### ISSUE TITLE
Parabox Dupe

### ISSUE THREAD

**Issue by BlueAgent** [Darkosto/SkyFactory4Issues#252]
## Bug Report
Parabox loop allows items to be duplicated due to not resetting player data.

## Expected Behaviour
Parabox loop should also reset player data on closing preventing the dupe

## Possible Solution
Making sure playerdata is reverted on loop close

## Steps to Reproduce (for bugs)
[Video Demonstration](https://www.youtube.com/watch?v=9xpdWUwLB4Y)
1. Create new world with prestige and cheats enabled
2. Place a creative cube with a Parabox on top
3. Place a chest with diamond blocks inside
4. Activate the parabox and start the loop
5. Take diamond blocks out of the chest and place into your inventory
6. Close the loop
7. Open the world and check chest to see diamond blocks in both the chest and player inventory

## Logs
* Client/Server Log: [latest.log](https://gist.github.com/BlueAgent/16ba9306b7f3af873b2a571004888cdf)
* Crash Log: N/A

## World Information
* Preset: Sky Factory 4
* Prestige: Yes
* Modpack Version world created in: 4.0.1
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.0.1
* Java Version: 1.8.0.201 (64 bit)
* Launcher Used: Twitch / Curse Launcher
* Memory Allocated: 4 GB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by justinrusso** [comment]
This is actually not a bug, rather, it is an intended feature.

**Comment by Saereth** [comment]
So when you do the loop players are meant to be able to clone entire Ae systems worth of stuff as an intended mechanic? Interesting

**Comment by BlueAgent** [comment]
Yeah just heard from Shadows it was intended as well.

**Comment by Rongmario** [comment]
I love this feature, its really one of the only reasons I play SF4 for.

**Comment by Waisse** [comment]
Retarded but ok.

**Comment by Bagabundoman** [comment]
Sky Dupetory 4
