### ISSUE TITLE
Androids are ignoring anti spawn mechanics

### ISSUE THREAD

**Issue by Saereth** [Darkosto/SkyFactory4Issues#253]
## Bug Report

hostile Androids from matter overdrive completely ignore anti spawning mechanics such as lucerna ritual and mega torches. This leaves them the only hostile able to spawn and soon you've got yourself a robot uprising firing squad ready to murder any player that spawns into your world. 

## Expected Behaviour

I would expect hostile mobs to be prevented by anti hostile mob spawning mechanics

## Possible Solution

no idea..

## Steps to Reproduce (for bugs)

1. set worldtype to lost cities
2. install mega torches and lucerna ritual, tons of angry robots will spawn

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Lost cities

* Prestige: no

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.1
* Java Version: 201
* Launcher Used: Twitch
* Memory Allocated: 5gb
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: no

## Server Information
* Java Version: 201
* Operating System: debian
* Hoster/Hosting Solution: OVH
* Sponge (Non-Vanilla Forge) Server: Vanilla

**Comment by Darkosto** [comment]
The MO devs are aware of this and we are awaiting a fix from them.

**Comment by Xalcon** [comment]
I dont think this is an issue with Matter Overdrive since Thermal Foundation Mobs spawn as well. It seems InControl is the culprit here. See https://github.com/McJtyMods/InControl/issues/125
