### ISSUE TITLE
Stuck in the sky after falling into void

### ISSUE THREAD

**Issue by Jomeaga** [Darkosto/SkyFactory4Issues#254]
## Bug Report
Fell of my island and into the void. Forgiving void put me at the top of the world after reaching the bottom. I am now stuck at Y300 and cannot look around, camera is stuck in that position. Disconnecting/reconnecting does not fix the issue.

## Expected Behaviour
After falling into the void and being put at the top of the world I should have continued falling downwards.

## Steps to Reproduce (for bugs)
1. Fall into void

## World Information

* Preset: Default single tree with dirt

* Prestige: Yes

* Modpack Version world created in: 4.0.1

## Client Information
* Modpack Version: 4.0.1
* Java Version: 1.8.0.161
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Unsure
* Operating System: Unsure
* Hoster/Hosting Solution: Unsure
* Sponge (Non-Vanilla Forge) Server: Unsure

**Comment by justinrusso** [comment]
From our experience, if you give it about 30 seconds it should then drop you finally. We're looking into this issue though.

**Comment by justinrusso** [comment]
This issue appears to be isolated to just multiplayer. We have been unable to find the cause of this issue, so server logs would be helpful. PLEASE BE CAUTIOUS OF THE CONTENTS OF THE LOG! Remove IPs if they exist.

**Comment by RANGER428** [comment]
I have the same issue, took almost 5min to reset

**Comment by tjsd** [comment]
What server logs are you interested in? I looked at debug.log and latest.log , nothing mentioning the players name in there at all.

They contain a lot of data so no super eager to post them public.

**Comment by SakkraDosh** [comment]
I have exactly the same as the original post. It's on an MP server, which I have no access to logs. was knocked off by a mob and sitting at Y300. I've been here about 20 minutes. No reset happening.

**Comment by jessigaming** [comment]
any update am now stuck in this bug myself and very annoying

**Comment by justinrusso** [comment]
Ask an OP to teleport you.

**Comment by henrydog4** [comment]
I am also stuck in the air after falling into the void. Correction of this issue would definitely be appreciated

**Comment by blay09** [comment]
A fix is now up and can be put on servers without needing clients to update:
https://minecraft.curseforge.com/projects/forgiving-void/files/2701427
