### ISSUE TITLE
[Pacifist route] Noexisting advancement NonPacific

### ISSUE THREAD

**Issue by Doppelganker** [Darkosto/SkyFactory4Issues#255]
## Bug Report

I have completed all advancements on first page, but You win! advancement still requires a advancement NonPacifist for completion.

![javaw_2019-04-16_18-01-18](https://user-images.githubusercontent.com/17344502/56226023-b58d8600-6072-11e9-93ad-ec74f633cd80.png)

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Pacifist

* Prestige: Yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.1
* Java Version: 1.8.0 201
* Launcher Used: Twitch
* Memory Allocated: 8 Gb
* Server/LAN/Single Player: SinglePlayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Stonjie** [comment]
This also happened in the ObservaTree (Astral Sorcery Observatory) world gen for me

**Comment by sk2048** [comment]
Somehow I missed someone had made an issue about this. I've resolved the issue for both ObservaTree (player should have NonPacifist on that map now) and Pacifist Mode (player no longer needs it). This fix will be incorporated into the next release.
