### ISSUE TITLE
Iron amber does not smelt in porcelain melter.

### ISSUE THREAD

**Issue by Davey876** [Darkosto/SkyFactory4Issues#256]
Steps to replicate:
1-porcelain melter on top of a porcelain heater. 
2- put clay bucket filled with lava in the fuel slot of the melter
3- put iron amber into input of melter
4- iron amber says there is not enough heat to melt.

![image](https://user-images.githubusercontent.com/27825010/56228207-3f265f00-6045-11e9-8ccc-ed45b2e64ed9.png)

**Comment by tempme123** [comment]
your fuel is 200 degrees, if you look in JEI iron amber requires 291 degree heat source

**Comment by Davey876** [comment]
> your fuel is 200 degrees, if you look in JEI iron amber requires 291 degree heat source

That is the bug. The advancements that @Darkosto wrote say to use the Melter to melt the iron amber, but you can't do that because of the temp requirements.

![image](https://user-images.githubusercontent.com/27825010/56234762-fc1fb800-6053-11e9-8e69-4d3ccc2bdbc1.png)

![image](https://user-images.githubusercontent.com/27825010/56234823-1c4f7700-6054-11e9-8daa-873200e72acd.png)

**Comment by sk2048** [comment]
You're using the solid fuel heater. If you put a tank (porcelain or seared) below the melter, it will use the lava as a fluid source instead, which is hotter.
