### ISSUE TITLE
Hopping Bonsai recipe doesn't work

### ISSUE THREAD

**Issue by bokipp22** [Darkosto/SkyFactory4Issues#258]
Hey, after unlocking 1 Prestige point and unlocking "Zen Garden" (Hopping Bonsai), you can't craft the Hopping Bonsai, there is no recipe, neither in the JEI

**Comment by Envoci** [comment]
Same problem for me

**Comment by xerminator** [comment]
Works fine for me though

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
