### ISSUE TITLE
[Bug/Feature request] Topography Island command creates new islands everytime

### ISSUE THREAD

**Issue by TheonlyTazz** [Darkosto/SkyFactory4Issues#259]
## Context
Topography Island command always creates new islands instead of teleporting to existing island

## Details
it would be great to make a spawn "island" with a command block which would trigger the `/topography island @p`
intended behavior:
if no island exists for that name, create new one
if island exist, teleport to that one  (which doesnt do it atm)

at the moment it always creates a new island instead of teleporting to the already existing one

**Comment by remclave** [comment]
May I ask the progress on this issue? We are unable to get players back to their islands.

**Comment by sk2048** [comment]
The command syntax was updated, the kind of behaviour desired can be attained using `/topography island home @p`. From Topography's changelog:
/topography island is now a command tree
 * Added /topography island home [player] - Teleports the player to their spawn point or island. If they do not have an island, it will generate one for them and teleport them to it.
 * Added /topography island new [player] - Generates the player a new island, and teleports them to it.
 * Added /topography island set [player] x z - Sets the provided coordinates as the players island and teleports them to it.
 * Added /topography island info [player] - Gets the coordinates of the players island.
 * Moved /topography invite to /topography island invite
 * Moved /topography accept to /topography island accept
