### ISSUE TITLE
Lava Bucket advancement not detecting clay bucket with lava

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#26]
Using a clay bucket to pick up lava from the cauldron is not being detected for the advancement

![2018-10-04_20 02 27](https://user-images.githubusercontent.com/29290246/46509429-aea6d080-c810-11e8-9726-3ff7037e54eb.png)

Vanilla bucket works as intended

SkyFactory4-0.0.13

**Comment by Darkosto** [comment]
Fixed! Looks like was missing a parentheses. Thanks!
