### ISSUE TITLE
Chest Slab - Carry on bug

### ISSUE THREAD

**Issue by Reudo** [Darkosto/SkyFactory4Issues#262]
## Bug Report
Picking up two chest slabs will "create" a bugged block. 
I can't place it back into the world and need to delete it.

## Steps to Reproduce (for bugs)

https://imgur.com/a/2uPv8p8

## Logs

* Client/Server Log: https://gist.github.com/Reudo/2949443338391ef381bba7639ab3df5f
* Crash Log: /

## World Information

* Preset: Default

* Prestige: No

* Modpack Version world created in: 4.0.1

## Client Information

* Modpack Version: 4.0.1
* Java Version: V8 Update 201
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: NO
* Shaders Enabled: NO

## Server Information
* Java Version: V8 Update 201
* Operating System: Win 10

**Comment by justinrusso** [comment]
Similar to https://github.com/Darkosto/SkyFactory4Issues/issues/233

Will be resolved in 4.0.2
