### ISSUE TITLE
Sky Factory 4 Claims unrealistic amounts of ram that it does not Use.

### ISSUE THREAD

**Issue by leumasme** [Darkosto/SkyFactory4Issues#263]
Had 3 People on different Setups, Different launchers and different Operating Systems confirm this.
Setup 1: Windows 10 ATLauncher 4-6GB allocated
Setup 2: Windows 10 Twitch Launcher 3gb Allocated
Setup 3: Linux MultiMC Launcher 8gb Allocated +Optifine+Shaders

When looking in the Task Manager / Process Explorer while we are on a standard Skyfactory 4 Forge Server the javaw process of the game claims between 10 and 35 gb of Ram, Much more than allocated and available.
It takes it so far that on windows and Linux the game and other programs randomly crash for OutOfMemory because even the ram swap file on the hard drive is maxed out.
![procexp64_fPPXKExV6J](https://user-images.githubusercontent.com/29953391/56234900-900a7780-6086-11e9-8bb8-5fd198da3e8e.png)

Important: Opening the f3 screen ingame, the ram usage looks completely normal, and is usually about 2-3GB

THIS SHOULD BE HIGH PRIORITY
As i have confirmed this on 3 different setups it is to be expected that most people are experiencing this, and currently it greatly affects playability and crashes other programs on the Device.

**Comment by leumasme** [comment]
Additional Note: the amount of ram it claims seems to be increasing over time.

**Comment by Espergium** [comment]
High priority of what? You've given no information about the systems affected, their launch arguments, their system variables (if any). Java won't use that much RAM unless it's told to.

**Comment by AshZification** [comment]
Setup 1: valid. What are the arguments/parameters you have set up? 
Setup 2: valid. What are the arguments/parameters you have set up? 
Setup 3: invalid. Why the would you report this as evidence when you added optifine to the instance? 

For setups 1&2, what is the progression of events?

**Comment by leumasme** [comment]
I have listed multiple systems with different setups to demonstrate that this is most likely not an error in the setup.
I do not believe that this is an error with the Launch Parameters. They were not changed from the launcher defaults except for the Xmx and Xms ram values (wich my launcher even automatically did for me so i didnt even touch them)
This is confirmed by the observation in the f3 screen that i stated before - the maximum ram is the max ram allocated and the current ram is always relatively far below that.

**Comment by leumasme** [comment]
Going to get the Map File from the Hoster and test if it only happens on that map.

**Comment by leumasme** [comment]
I have found the Cause @sk2048 @Espergium @AshZification 
While a "Statues Mod" Player Statue ("Bauble Head") is Rendered it rapidly increases.
These are automatically placed on players heads when they open their graves and were also placed on our Islands, wich is what caused this.
https://streamable.com/cjqd4 < Video Showing this, including my full start arguments at the beginning when i hover over the process.

**Comment by Espergium** [comment]
-Xms1024M -Xmx4096M -XX:Metaspace Size=256M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:UseAdaptiveSizePolicy

Is what I'm barely able to see from the video. Have you experienced this issue after only using the Xms/Xmx flags?

The increase on your ram is negligible when placing down the statue. This isn't a solid indicator that an item is doing it. You're using procexp so the rundown of those two columns is not a solid indicator of RAM usage. It's a "guesstimate"
Private means a process asked for an amount and was permitted an allowance but doesn't mean the process is actually using it. 
Working set is non-paged private plus memory mapped files.

**Comment by leumasme** [comment]
"The increase on your ram is negligible when placing down the statue. This isn't a solid indicator that an item is doing it"
This is not true. Maybe it wasnt really clear in the first video so im making a second one.
Whenever the Statue is Placed or Dropped in the World or on another Players Head, private bytes increases in a constant speed.
"Private means a process asked for an amount and was permitted an allowance but doesn't mean the process is actually using it." Wich is why i said "Claims" in the Issue Title.
"Have you experienced this issue after exclusively using the Xms/Xmx flags?" The other flags were all automatically set by my Launcher and i am not able to remove Flags, only add them in the atlauncher, however as said, i have noticed this with 3 different launchers, wich most likely have very different default start flags (i can check that later if it is still relevant then)

New Video where it is Clearer that not only Placing the Statue increases ram usage but also just it existing:
>> Read at the End
Sidenote: Ever since we removed the statues from our Island and burned them whenever we got them, this has not been a problem anymore.
Sidequestion: From your reaction i am to assume that you could not reproduce it with player statues, or have you not tried? @Espergium

Last Word: After Removing the mod from the server but then readding it as no mobs spawned without it, statues are no longer created when opening a gravestone.
I have not been able to reproduce this in singleplayer, so i guess if noone else can reproduce this, this is the end of this issue.
