### ISSUE TITLE
Steel blocks don't turn into ingots

### ISSUE THREAD

**Issue by Nazta** [Darkosto/SkyFactory4Issues#265]
## Bug Report
Tinkers smeltery gives thermal block of steel when alloying, as expected. But they turn into a "tcomplement:materials" item with a missing texture instead of steel ingots. 

[JEI screenshot](https://i.imgur.com/JW1jmTv.pngl)
 
## Expected Behaviour
Normally it would turn into thermal steel ingots, but even JEI shows the bugged conversion. 

## Possible Solution
Use CraftTweaker to fix the recipe. 

## Steps to Reproduce (for bugs)
Install SF4 4.0.1 and try to turnn steel blocks into ingots.

**Comment by Fourmiant** [comment]
I would like to add you cannot turn ingots into nuggets also. Are all ingot/block/nugget recipes affected?
