### ISSUE TITLE
Console spam from gamestage

### ISSUE THREAD

**Issue by LemADEC** [Darkosto/SkyFactory4Issues#267]
## Bug Report
gamestage is spamming console.

## Expected Behaviour
no spam

## Possible Solution
disable debug data logs in the mod's configuration

## Steps to Reproduce (for bugs)
1. play the modpack
2. observe console

## Logs
n/a

## World Information
n/a

## Client Information
* Modpack Version: 1.0.1

## Server Information
n/a

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by LemADEC** [comment]
I did follow the template and gave more than enough to explain the issue, including how to fix it.

**Comment by sk2048** [comment]
You reported an issue where something is producing spam in your logs without providing said logs.

It's unclear to me whether your complaint is in regard to the "Saved x stages..." messages that appear at most once every 30 seconds, or some other issue.

Disabling the debug information is something that will happen when the team is happy with not needing that information to troubleshoot bugs.
