### ISSUE TITLE
 Wooden hoppers do not hop from casting basin or casting table to compact storage chest. [0.13]

### ISSUE THREAD

**Issue by Demlou6** [Darkosto/SkyFactory4Issues#27]
Regular hoppers do, not seeing anything any issue reported for this on any of the 3 mods githubs.

**Comment by Darkosto** [comment]
Yes, this is due to the same Compact Storage bug that does not allow interaction with other inventories. We'll have to wait on them to update or I'll remove the mod.

**Comment by jaredlll08** [comment]
Just ran into this myself, I am frustrated enough that I am willing to rewrite the mod if you're interested @Darkosto, just let me know.

**Comment by Darkosto** [comment]
This is fixed now. A mod has been created to force Compact Storage to use the new inventory system and works with all mods/connections.
