### ISSUE TITLE
"cannot find addon dependency 244651" this is on the twitch launcher

### ISSUE THREAD

**Issue by ShyShutaii** [Darkosto/SkyFactory4Issues#270]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
This is Twitch's fault, not much we can do, you just have to be patient with Twitch sometimes. You can get the pack through ATLauncher, or download the zip file from the link below and import it into MultiMC if you don't have the time to be patient with Twitch :)
