### ISSUE TITLE
Can't Sleep When in CompactSky

### ISSUE THREAD

**Issue by RsTornado** [Darkosto/SkyFactory4Issues#271]
## Bug Report
 When trying to complete the achievement/advancement "Nap Time," this doesn't seem possible when in CompactSky Map. Such that you cannot sleep in that map mode, only the option to set re-spawn point.
 

## Possible Solution
Allow sleeping, crafting a bed, or when clicking on bed it should complete "Nap Time"
 Change activation of the achievement/advancement

## Steps to Reproduce (for bugs)

1.
2.

## World Information

* Preset: CompactSky

* Prestige: Enabled

* Modpack Version world created in: 4.0.1

* Additional Content Installed: None

**Comment by tmorrish** [comment]
I was going to report this as well but you got to it first

**Comment by cfalzone** [comment]
Is there any workaround or way to "admin" complete the advancement?

**Comment by sk2048** [comment]
Advancements can be awarded to any player by any player with op.

`/advancement grant @p only sf4:age1/sleep` to give it to yourself, replace `@p` with a player name to give it to someone else.

**Comment by yosomith** [comment]
I was able to sleep in the hunting dimension
