### ISSUE TITLE
Can't get Prestige to work on a MP server

### ISSUE THREAD

**Issue by sLpFhaWK** [Darkosto/SkyFactory4Issues#272]
I just setup a MP server for me and my buddies, but we want to start in Prestige mode. I tried forcing it server side with /prestige force enabled and it took the command but ore excavation was still working. I restarted the server thinking that would work but it's still working. Do i need to delete the world folder and start again? I haven't done much so this isn't an issue.

I tried looking in the server properties, options etc and i can't find anything.

**Comment by darkphan** [comment]
You need to follow the instructions at the bottom of the Sky Factory 4 Multiplayer Instructions document. It specifically tells you what config file to change. I would stop the server, edit that file, delete the world, then restart.

**Comment by sLpFhaWK** [comment]
> You need to follow the instructions at the bottom of the Sky Factory 4 Multiplayer Instructions document. It specifically tells you what config file to change. I would stop the server, edit that file, delete the world, then restart.

I'm looking over the PDF for the third time, and it mentions nothing about prestige.  At the bottom of the PDF it says stuff about Compact Sky and 16 Machines, 64 Machines and 256 Machines.

If I'm still not seeing what I need to see please let me know.

**Comment by Priess08** [comment]
where can I find the Sky Factory 4 Multiplayer Instructions document?

**Comment by sk2048** [comment]
You should find it in the zip folder from Curseforge. They are also now published online here: https://github.com/Darkosto/SkyFactory4Issues/wiki/Multiplayer-Instructions

Do not use the server files from ATLauncher. We have no control over them and ATLauncher makes modifications to them that do not help.
