### ISSUE TITLE
Seared Heater + Seared Alloy Tank not triggering Advancements

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#273]
## Bug Report
Seared Heater + Seared Alloy Tank not triggering Advancements - Didn't trigger with me holding it nor FirstNecron

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: 401
* Java Version: Latest
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Durandle** [comment]
can confirm this is an issue the porcelain version work fine for the advancements but not the seared versions  despite the seared versions working for the other 2 advancements
"I'll Be Your Alloy" and "Getting Warmer" are the effected advancements

steps to reproduce
create seared version of the alloy tank and heater from tinkers complement

this should be an easy fix as it seems that the seared versions were missed in setting up the advancement

**Comment by JackRuby1** [comment]
Fixed in 4.0.2
