### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by mrmano841** [Darkosto/SkyFactory4Issues#274]
Petrified sapling recipes were missing from the game

**Comment by TheForceteam** [comment]
@mrmano841 I do have the recipe on my side try to reinstall the modpack maybe it missed some files !

**Comment by AshZification** [comment]
Define "missing from the game" 
Have you restarted the pack? 
Have you ensured it's installed properly? 
Did you check JEI for all of the potential options?

**Comment by RsTornado** [comment]
It might be on your end because I do see a recipe for petrified saplings.

**Comment by Darkmift** [comment]
I second this issue....mulch recipes are not accessible as well as some others.
one example:fertile soil can be crafted tough just not in JEI.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by Darkmift** [comment]
Try to be a little more coteous towards people who take the time to help
you with your work.
