### ISSUE TITLE
Cannot complete "SkyFactory 4" advancements for prestige

### ISSUE THREAD

**Issue by JayJay1989** [Darkosto/SkyFactory4Issues#283]
## Bug Report
Cannot complete following stages:
- Wet Feet (break water source block)
- Get It While It's Hot (Break lava source block)
- Tree Harder (Obtain a sapling)
[Screenshot1](http://prntscr.com/ncywc5) [Screenshot2](http://prntscr.com/ncywik)

## Steps to Reproduce (for bugs)
1. Create a new world (Skyfactory Default map)
2. Complete all the advancements on the "SkyFactory 4" page
3. Prestige cannot be unlocked because 3 advancements hasn't popped

## World Information
* Preset: "Sky Factory 4"
* Prestige: yes
* Modpack Version world created in: 4.0.1
* Additional Content Installed: Laggoggles

## Client Information
* Modpack Version: 4.0.1
* Java Version: 8
* Launcher Used: twitch & multimc
* Memory Allocated: 12gb
* Server/LAN/Single Player: MP & SP
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: OpenJDK 8
* Operating System: Ubuntu 16.04.6
* Hoster/Hosting Solution: Pterodactyl
* Sponge (Non-Vanilla Forge) Server: no

**Comment by sk2048** [comment]
This should have been resolved in 4.0.1, is it possible you haven't updated the config folder on your server?

**Comment by JayJay1989** [comment]
i have now replaced "configs" and "scripts" directory. Give you more information in a bit.
