### ISSUE TITLE
[Suggestion]  Void Island Control

### ISSUE THREAD

**Issue by kreezxil** [Darkosto/SkyFactory4Issues#284]
## Context

Void Island Control allows a server and even single player to have a new island for each player that joins the game. The server as it stands now puts everyone on the same island.

## Mod Details
* Name: Void Island Control
* CurseForge Link: https://minecraft.curseforge.com/projects/void-island-control

**Comment by sk2048** [comment]
This is completely incompatible with topography, which the pack is built around, not to mention it already allows this.

`/topography island <player_name>`

**Comment by kreezxil** [comment]
yes, but how do you automatically create an island for a new player without
telling them to do that command at spawn?
