### ISSUE TITLE
Observatree map "Complted Non-Pacifist" Advancement

### ISSUE THREAD

**Issue by twschutz** [Darkosto/SkyFactory4Issues#289]
## Bug Report

On the observatree map, non pacifist run, the "completed non-pacifist" advancement prevents the user from earning the prestige point for completing the first run. No mobs were killed and yet it still is blocking progression. Seems to only be on this map for me?
## Expected Behaviour

It should award the prestige point after completing all 52 advancements
## Possible Solution

I did not set the map to pacifist. I completed three world before this (different maps) with the same settings and was able to earn the first page completion prestige point
## Steps to Reproduce (for bugs)

1. Create a world on Observatree map
2. Complete all first page advancements
3. Observe lack of prestige point awarded to user

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Observatree

* Prestige: Yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed: N/A

## Client Information

* Modpack Version: 4.0.1
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 16MB 
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by justinrusso** [comment]
As a temporary solution, you can run `/gamestage add playername non_pacifist`

**Comment by justinrusso** [comment]
In addition, run `/advancement grant playername only sf4:age1/nonpacifist`
