### ISSUE TITLE
'Water You Waiting For?' Advancement Misinformation

### ISSUE THREAD

**Issue by Crackerhead22** [Darkosto/SkyFactory4Issues#293]
## Bug Report
The advancment currently reads as 
> "Collect Rain Water in a Cauldron or by jumping on a Sapling in a Crushing Tub. Collect it using a Clay Bucket or Iron Bucket"  Jumping on Saplings gives Sap, not Water.

## Expected Behaviour
It should read as 
> ""Collect Rain Water in a Cauldron or by jumping on _Leaves_ in a Crushing Tub. Collect it using a Clay Bucket or Iron Bucket"

## Possible Solution
Change Sapling to Leaves.

## World Information

* Preset: ObservaTree

* Prestige: Yes

* Modpack Version world created in: 4.0.1

## Client Information

* Modpack Version: 4.0.1
* Java Version: 211
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Sing Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by JackRuby1** [comment]
Sap is made by jumping on acorns, not saplings. Are you sure you didn't have some sap in there earlier?

**Comment by drakkensong21** [comment]
Jumping on saplings does give water can confirm

**Comment by sk2048** [comment]
Looks like a mistake, if it turns out that this is not the case feel free to reopen.
