### ISSUE TITLE
two steps back? where is Storage Drawers.

### ISSUE THREAD

**Issue by Layarion** [Darkosto/SkyFactory4Issues#295]
The barrels and crates mod is like a cheap knock-off of the storage drawers mod, and i hate grinds.

where to get started? well my first question is, why is the crates mod competing with storage drawes? sure i wished storage drawers had 3by3 drawers but why in the love of god are you making me look at this box, that only holds 1 fricken item, ...this mod looks like it's trying ot replace something it's doing a half-assed attempt at replaceing. i hate it.

**Comment by JackRuby1** [comment]
Have you tried a shipping container, it can hold multiple of those crates, most power storage blocks or even drums/liquid containers. :)

**Comment by Layarion** [comment]
i messed around with it in creative, and the only thing i've been able to figure out about that shipping crate is that I can take other crates, and manually put them inside it...but that seems to be all it really does? 

like, i can't double right-click to store all matching items in it? as in, this shipping crate is not meant for MC characters to interact with, but it's sole purpose is for other systems to auto-store stuff in it and pull from it?

i haven't tried using machines to put and get items from it, but i'm assuming that it lets that happen, because it certainly doesn't let the player do it, and if it does there's no documentation anyway about this mod other than the overview page...which has very little info...

listen if the shipping container is only for machine to work with, then that helps the mod sure...but frankly...my original point still stands. why is it half-assed competing with storage drawers? so far, it does literally everything that mod does, and nothing more...and the problem with that is, it does a shit job at it.

**Comment by AVileIdiot** [comment]
I was thinking that maybe storage drawers could be added, and if its thought to be too overpowered it could be a prestige reward. that way its still in for those of us who prefer it but also would take some work if it was considered too overpowered.

**Comment by Studio528** [comment]
I do like storage drawers but sometimes I like things changed up, I'm pretty sure this mod was meant for this pack, btw, right click adds what is in your and double right click adds whole inventory, left click takes a stack out, shift left click takes out one, also these drawers seem to be a little more pleasing to the eye

**Comment by darkphan** [comment]
The crates, barrels and drums retain their inventory when broke and they can all be placed into a shipping container. You can also place energy storage such as the mekanism energy cubes. You can then pipe all of that in and out of the shipping container. You can also hook a shipping container up to a storage system such as simple storage networks and AE2.

**Comment by darkphan** [comment]
I also would like to add that a mod not being in the pack has nothing at all to do with whether the mod author wanted it in the pack or not. The Barrels, Crates, Drums and More mod is an alternative storage mod like Storage Drawers, YABBA, Real Filing Cabinets (which is also in the pack, maybe you should check that out instead), Charset Storage - Barrels just to name a few.

**Comment by Lothrazar** [comment]
Perhaps there could be some reminder to link big crates and simple storage network, that is my ideal use case.

But the best part of learning new modspacks is discovering new mods isnt it?

**Comment by Layarion** [comment]
i'm not complaining about trying new things, i'm complaining about what looks like a clone doing a poor imitation instead of bringing something to the table. also, the drawers looks ugly with the massive pixilated 2d grid items blown above their usual size. like really ugly, takes more space, and i haven't figured out yet how to pick one up without an item coming out of it. the documentation is lacking.

**Comment by darkphan** [comment]
I guess you should look at other storage options that are in the pack then, or maybe Sky Factory 4 just isn't for you. I personally love the fact that with the shipping containers I can put fluid and energy containers into them. With power piped into it, you can even power items that need to be charged such as the building gadgets or the guns from Matter Overdrive.
