### ISSUE TITLE
Can't get prestige to work on new server.

### ISSUE THREAD

**Issue by Shindur** [Darkosto/SkyFactory4Issues#297]
## Steps to Reproduce (for bugs)

1. Download the server files
2. Change the prestige config to enable prestige > save
3. Upload all applicable files to server host
4. Start up the world, starts fine.
5. Join world and then get this error:
Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@4cd6f08b) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@7efa366)

Both client and server have the same configs. Both server and client have the prestige setting set to true.

## Logs

* Client/Server Log: https://gist.github.com/Shindur/ca0c73271e1d9b2952434deb16068236
* Crash Log:

## World Information

* Preset: Sky Factory 4

* Prestige: Trying to..

* Modpack Version world created in: 4.0.1

* Additional Content Installed:
Content Creator Integration
Chance Cubes
Player Skin Mob
VanillaFix
(All latest versions of the mods above)

## Client Information

* Modpack Version: 4.0.1
* Java Version: 1.8.0.201
* Launcher Used: MultiMC and Twitch Launcher
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Latest? (unsure, host is MelonCube.)
* Operating System: Unsure, host is MelonCube
* Hoster/Hosting Solution: MelonCube
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by nzminecraftDOTcom** [comment]
Are all your configs/scripts similar on both server and client copies?

**Comment by Shindur** [comment]
Yup, all config files are the same. I could try pulling the config folder I have on my client and uploading it to the server to see if that works

**Comment by Shindur** [comment]
Can close this... I figured it out. Not only do you need to have prestige=true client side, but we also re-enabled channels so that needed to be changed client side..

My bad, can close this. Thank you for your time!

**Comment by nzminecraftDOTcom** [comment]
Shouldn't need to set prestige to true for clients?

Not having the issue with my servers where clients are false and server is true.

**Comment by Shindur** [comment]
@nzminecraftDOTcom I dunno. We tried everything, but changing the settings in both client and server worked so /shrug
