### ISSUE TITLE
Sky Factory Tutorial hiding/removing first prestige advancements

### ISSUE THREAD

**Issue by Skyswimsky** [Darkosto/SkyFactory4Issues#300]
![ripprogress](https://user-images.githubusercontent.com/8056740/56281950-33eb3600-610e-11e9-828c-8d8fe7bba2ce.png)
## Bug Report
Starting SkyFactory4 on the tutorial map hides, or completely replaces, the "Advancements - SkyFactory 4" advancements tab that the other maps have. Making it not possible to get the first prestige point for bonsai hopper.

## Expected Behaviour
The "Advancements - SkyFactory 4" tab should either appear or replace the tutorial advancements after completing them, or be there in the first place like the other "Age of" tabs.

## Steps to Reproduce (for bugs)

1. Start a new world on the Tutorial Skyblock map.
2. Press L, or whatever keybind opens the advancements.
3. Check the advancements to see that the crucial Advancements - SkyFactory4 tab missing. 

## Logs

* Client Log: https://gist.github.com/Skyswimsky/27490d32bf5467cc16d649da495232a2

## World Information
* Preset: Tutorial
* Prestige: Yes
* Modpack Version world created in: 4.0.1

## Client Information

* Modpack Version: 4.0.1
* Java Version: 1.8.0.201 (64bit)
* Launcher Used: Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment]
Darkosto has no intention of adding a prestige advancement to the tutorial world.
