### ISSUE TITLE
Squeezer + Coal = Crash

### ISSUE THREAD

**Issue by OfficialZygorg** [Darkosto/SkyFactory4Issues#301]
When trying to do pulverized coal in the squeezer, it crash.
Crash types:
-Single player: Client crashes.
-Multiplayer: Server crashes or host crashes

Can be replicated by other players? -Yes

**Comment by sk2048** [comment]
You reported an issue where something is producing spam in your logs without providing said logs.

It's unclear to me whether your complaint is in regard to the "Saved x stages..." messages that appear at most once every 30 seconds, or some other issue.

Disabling the debug information is something that will happen when the team is happy with not needing that information to troubleshoot bugs.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
