### ISSUE TITLE
Add a warning when Prestige mode is enabled in world selection.

### ISSUE THREAD

**Issue by sajhino** [Darkosto/SkyFactory4Issues#303]
## Context

I've seen a lot of people who don't understand what prestige is/does, me included. I initially thought it was a cool new way to get rewards, so I enabled it, but I didn't know it also gates a bunch of stuff like an expert modpack does. Of course you can always change it back with a command but it would be nice to see a warning that says it gates stuff and only meant for experienced players or something when enabling prestige in world selection.

**Comment by justinrusso** [comment]
![image](https://user-images.githubusercontent.com/25138621/56303366-bde4d000-6109-11e9-9eb4-341bd920359d.png)

**Comment by sajhino** [comment]
Oh, it's in a tooltip. No wonder I completely missed that. I just clicked the button instantly. Whoops lol.
