### ISSUE TITLE
Invalid Meta Type - Bungeecord Server Disconnections

### ISSUE THREAD

**Issue by Yorkforce** [Darkosto/SkyFactory4Issues#307]
## Bug Report
Bungeecord is currently catching a Unknown Meta Type 14 error which causes a server disconnect.
The disconnections are somewhat random, there is no particular action ingame thats appears to be triggering it, there are no mob entities spawning, its occurring if a player is chopping down a tree or stood still doing nothing. However they are frequent, usually causing a server kick within 5-15 mins.

This is not a new problem, as can be seen here:
https://github.com/SpigotMC/BungeeCord/issues/2294

Essentially, a mod (Astral Sorcery) in the pack is changing vanilla protocol when it shouldn't be?

This is a tough issue to track down, with 200+ mods in the pack, it's very difficult to single out the mod causing the problem, perhaps one of the modpack team might have a better idea what mods change vanilla protocols?
Edit: Narrowed down to Astral Sorcery

## Expected Behaviour
There should be no Unknown Meta Type errors.

## Possible Solution
Track down offending mod (Astral Sorcery) and push for an update/fix.

## Steps to Reproduce (for bugs)
Unable to reproduce reliably.

## Logs
* Server Log: https://pastebin.com/5RRyJR7A

## World Information
* Preset: Sky Factory Default
* Prestige: No
* Modpack Version world created in: 4.0.1
* Additional Content Installed: None

## Server Information
* Java Version: 1.8
* Operating System: Debian 9
* Hoster/Hosting Solution: Hetzner - Direct Host
* Sponge (Non-Vanilla Forge) Server: SpongeForge

**Comment by Yorkforce** [comment]
We have narrowed this down (exhaustively), the cause is Astral Sorcery, once disabled the error and disconnections stop occurring.

**Comment by i9hdkill** [comment]
Try that for now:
```shooting_stars {
        # Set to true to make shooting stars do a little explosion where they land [default: true]
        B:doExplosion=false  <- set this to false

        # Set to false to disable shooting stars from spawning [default: true]
        B:enabled=false <- set this to false
    }
Sadly there are still some stubborn mod authors out there :(
