### ISSUE TITLE
Putting Cooked Porkchop in Squeezer Hard Crashes games

### ISSUE THREAD

**Issue by SasquatchThomas** [Darkosto/SkyFactory4Issues#311]
AS Title says, trying to make bacon in the Squeezer using the cooked pork chop, as soon as you do the last jump to finish the squeezing process, the game freezes then force closes.

**Comment by SasquatchThomas** [comment]
Reproduced this several times, also consumes porkchop but does not give the bacon as recipe shows.

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
