### ISSUE TITLE
Skyfactory 4 crashes on startup.

### ISSUE THREAD

**Issue by Danchovesko** [Darkosto/SkyFactory4Issues#313]
Here is my log: https://gist.github.com/Danchovesko/f47287465c950ad834ea9a267cd25bdf

I don't understand whats the problem at all.
What i've tried so far:
-Reinstalling the modpack
-Repairing the modpack
-Updating both 32 and 64 bit java
-Allocating 4 gb of ram.
None of it has worked

Edit:
So i thought i had already downloaded the 1.12.2 jar but apparantly i downloaded something else. Anyways running the normal 1.12.2 fixed it for me, sorry for opening this thread.

**Comment by sk2048** [comment]
This isn't really an issue with the pack - your game isn't reaching the point where it starts loading mods.

As we're trying to keep the issue tracker here focussed on issues we can fix, I'm going to close this.

If you join the Discord you should get some help with this, https://discord.gg/darkosto
