### ISSUE TITLE
Command to create new island is not working.

### ISSUE THREAD

**Issue by deudyscout** [Darkosto/SkyFactory4Issues#316]
I have just made a new SF4 server and I was trying to create a new island for my main account as i was using m spare for the main spawn island and the /typography command was not working, i then tried to use the help the command and it wasnt working either.
Pastebin: https://pastebin.com/HYE9tSS1

Using normal island
no prestige version 4.0 for server and 4.0.1 for client
Server is running in on linux centos in a proxmox container on my own servers, 4gb of ram allocated.
not sure of the java version at the moment but it should be at least java 8

**Comment by sk2048** [comment]
What command did you try exactly?

From the logs it looks like you didn't substitute a name into the command.

`/topography island sChiaVo_` might well be what you want. You need to be opped to run that command.

**Comment by deudyscout** [comment]
if you keep looking at the logs i did sub the name in the command

**Comment by deudyscout** [comment]
both accounts are opped as well

**Comment by sk2048** [comment]
The logs don't show the commands you entered, only the commands that failed. Telling me to keep looking at the logs is making this needlessly difficult.

**Comment by deudyscout** [comment]
ok...no need to have an attitude

**Comment by deudyscout** [comment]
the command i used was /typography island kaimacaw

**Comment by sk2048** [comment]
Attitude? No, merely an accurate description of the situation.

What version of Topography have you got on the server? My guess is you need to update it as you probably downgraded it to get 4.0.0 working. The version you have installed probably doesn't have the island command.

**Comment by deudyscout** [comment]
well i didnt downgrade anything, the files are as downloaded last night and the mod version...which came with the server files is 1.12.2-1.4.5

**Comment by deudyscout** [comment]
and the server version i just checked is 4.0.1

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
