### ISSUE TITLE
Mekanism x3 Production

### ISSUE THREAD

**Issue by MaccaPakka** [Darkosto/SkyFactory4Issues#322]
## Bug Report

The Purification Chamber -> Crusher = Mekanism Dust which can only be used in a Nuclear Craft "Melter" 

## Expected Behaviour

Dust should be able to be smelted in the Mekanism Energized Smelte

**Comment by justinrusso** [comment]
You get mekanism's dirty dust in the crusher. You need to enrich the dirty dust to get normal dust which can then be used to turn into ingots

**Comment by mlegault55** [comment]
If you put iron amber directly in the crusher, it give an iron dust (not dirty dust) that can only be used in the melter and alloy furnace.

**Comment by justinrusso** [comment]
@mlegault55 this report specifically includes the purification chamber, which would mean that this is not the same as putting them directly in the crusher.

**Comment by mlegault55** [comment]
@justinrusso Sorry I assume it was the same issue a.k.a. the mekanism's crusher producing a dust that can only be used in the nuclearcreaft's melter.
