### ISSUE TITLE
How do I obtain ender pearls? (Compact World)

### ISSUE THREAD

**Issue by JohnBatts** [Darkosto/SkyFactory4Issues#331]
I've visited the hunting dimension and searched on JEI for hours, and I can't find any conceivable way to get ender pearls without first having an ender pearl, and I can't get any mobs to spawn, much less enderman... please advise.

**Comment by bokipp22** [comment]
Enderman seed?

**Comment by darkhax** [comment]
Enderman seeds should work for this. Also please post questions about the pack on the [Discord](https://discord.gg/darkosto).
