### ISSUE TITLE
Sync not working in hardcore Presets

### ISSUE THREAD

**Issue by EchoingZen** [Darkosto/SkyFactory4Issues#332]
## Bug Report
When playing on either the 'Hardcore' or 'Are you Afraid of the Dark?' world types, you spawn with a Sync setup. This sync setup does not appear to work since those world types are forced into vanilla's Hardcore mode.

## Expected Behavior
It appears that the intention is to allow for reconstruction of the player, provided the Sync setup is fully charged.

## Possible Solution
If Sync was not intended, it should be removed from the starting structure as to not mislead players who enter that mode.

## Steps to Reproduce (for bugs)
1. Create a new world with either the 'Hardcore' or 'Are you Afraid of the Dark?' world type.
2. Right-Click on the setup, and it should begin to create a clone.
3. Wait until the clone is complete.
4. Die, you will not be able to respawn in the newly created clone.

(NOTE: I thought it was because a redstone signal needed to be running to the block where you respawn, but I threw an item on it and jumped into the void and still wasn't able to respawn.)

## Logs
N/A

## World Information
* Preset:  'Hardcore' and 'Are you Afraid of the Dark?'
* Prestige: Yes and No
* Modpack Version world created in: 4.0.1
* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.1
* Java Version: 1.12.2 (modded) forge-14.23.5.2831
* Launcher Used: Twitch
* Memory Allocated: 6114MB
* Server/LAN/Single Player: SP
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Darkosto** [comment]
https://clips.twitch.tv/PuzzledHonorablePeanutGrammarKing

The sync mod is working correctly. 

Having said that, it’s probably better to let players know through advancements how the mod works so they don’t get confused and lose their world.

**Comment by EchoingZen** [comment]
Thanks for the comment! Looks like I was just using it incorrectly. Appreciate the response

**Comment by skermajo** [comment]
On the topic of 'how to use the sync mod' another thing that caught me out and lost my world is that if a populated shell storage receives but then loses the redstone signal (which is easy to do when it's a pressure plate in the build in maps), the shell is deleted and is not recoverable.

See: https://github.com/iChun/Sync/issues/140

**Comment by Darkosto** [comment]
We've added in some advancements to help guide players in how the sync mod works. This should help you not lose your worlds :) Will be out for 4.0.2
