### ISSUE TITLE
Magnesium Diboride Solenoid recipe doesn't work

### ISSUE THREAD

**Issue by Blargerist** [Darkosto/SkyFactory4Issues#335]
Literally unplayable.

By "doesn't work" I literally mean doesn't work. It's in JEI just fine. If you put it into a crafting grid though, it just doesn't work. Doesn't show a result, can't be crafted. Tried on both server and client.

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by Darkosto** [comment]
Just tried this on Single Player and it works for me.

**Comment by Blargerist** [comment]
I'm dumb.
