### ISSUE TITLE
Bonus Cows? - Animal Crops 1.12.2-0.2.0

### ISSUE THREAD

**Issue by Romsil123** [Darkosto/SkyFactory4Issues#336]
Animal Crops 1.12.2-0.2.0
Skyfactory 4.0.1

When bone meal cow seeds on grass blocks. I was unsure if you are supposed to get cow seeds that stay planed after freeing the Mature cow. 

Please let me know if this is bug, or working as designed with random chance for seed to stay planted to get another bonus animal.

**Comment by Romsil123** [comment]
I recreated I seem to be getting unlimited cows on one blocking using bone meal over and over again.

**Comment by Romsil123** [comment]
I recreated I seem to be getting unlimited cows on one blocking using bone meal over and over again.[logs.txt](https://github.com/Darkosto/SkyFactory4Issues/files/3092254/logs.txt)

**Comment by Romsil123** [comment]
After about the 6-7 cow spawned it stopped spawning from the same seed. Is this working correctly?

**Comment by Darkosto** [comment]
This is not a bug. They have a chance to stay planted. You do not have to plant a new one every time.
