### ISSUE TITLE
Crash from Simple Storage "Remote"

### ISSUE THREAD

**Issue by mcoffma1** [Darkosto/SkyFactory4Issues#341]
Pack Version: 4.0.1

The simple storage mod was working fine, until I crafted and used the "Remote" item to remotely access the storage.

Right clicking to 'use' the remote resulted in Instant Crash.

Forgot to copy clipboard, but if it repeats I will upload.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
