### ISSUE TITLE
Cobblestone Generator does not accept vanilla buckets for crafting

### ISSUE THREAD

**Issue by dsabecky** [Darkosto/SkyFactory4Issues#345]
## Bug Report
Cobblestone Generator cannot be crafted using vanilla iron Bucket.

## Expected Behaviour
Vanilla buckets be a valid fluid container for Cobblestone Generator.

## World Information
* Preset: Skyfactory 4
* Prestige: No
* Modpack Version world created in: 4.0.1

**Comment by Darkosto** [comment]
Cannot reproduce the bug. Make sure you're using the correct items in the correct slots and not mixing clay and iron buckets.
