### ISSUE TITLE
No chests in End cities

### ISSUE THREAD

**Issue by Coin75** [Darkosto/SkyFactory4Issues#351]
When exploring end city i found that there where no chests but the loot was just lying around. it only happens in the building but not the ships.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
