### ISSUE TITLE
Wooden Stakes conflict with Thin Wall-Wooden

### ISSUE THREAD

**Issue by llhilton** [Darkosto/SkyFactory4Issues#353]
## Bug Report
Currently, you cannot craft the wooden stakes from rustic. The recipe is in conflict with the Chinese Workshop recipe for Thin Wall-wooden. 

## Expected Behaviour
It would be expected to be able to make both. Perhaps the stakes could use logs instead of planks? So many logs. Need things to do with logs!

**Comment by sk2048** [comment]
Duplicate of #251
