### ISSUE TITLE
Breaking Mekanism Thermal Evaporation Blocks crash

### ISSUE THREAD

**Issue by Dr-Turtle** [Darkosto/SkyFactory4Issues#358]
When placing a "Thermal Evaporation Block" from Mekanism, the client times out, and the server crashes

[crash-2019-04-18_14.06.42-server.txt](https://github.com/Darkosto/SkyFactory4Issues/files/3095655/crash-2019-04-18_14.06.42-server.txt)

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
