### ISSUE TITLE
vein miner doesn't work for me

### ISSUE THREAD

**Issue by symendepymen** [Darkosto/SkyFactory4Issues#359]
when i try to use vein miner it doesn't work, it just mines like normal. i don't know if this is a personal problem or if more people have experienced this, it seems to work just fine for my friends but i can't get it to work. if anyone knows how to fix this, i would like to know.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by sk2048** [comment]
Also, go to the discord when you're not sure if it's a bug or not. https://discord.gg/darkosto

**Comment by symendepymen** [comment]
i don't really know how this works yet
