### ISSUE TITLE
missing recipes, smeltery drain and absorption hopper

### ISSUE THREAD

**Issue by Cujoplays** [Darkosto/SkyFactory4Issues#361]
i generated my world with prestige mode turned off and have found a couple blocks with no recipe associated with them the tinkers smeltery drain and mob grinding utilities absorption hopper.  a mod in the discord asked me to run /gamestage info and this was the result. just an update the Smeltery controller also does not have a recipe. 
![image](https://user-images.githubusercontent.com/49764587/56384399-1f23a680-61d1-11e9-9b9a-8628feb3dce4.png)

**Comment by Darkosto** [comment]
I'm not able to replicate this on a brand new world with prestige off. Could you try making a new world and confirming it's not just that one world?

**Comment by Cujoplays** [comment]
when i create a new world the recipes are there so something must have just got bugged in my world gen is there a command to unlock all the prestige items so i don't need to start over?

**Comment by justinrusso** [comment]
No, you would have to just match up the stages you are missing.
