### ISSUE TITLE
Completed Prestige tab1 but no prestige point

### ISSUE THREAD

**Issue by misterhampton** [Darkosto/SkyFactory4Issues#364]
I have completed the first tab on prestige mode but have received no prestige point, it says 51/52 completed in non pacifist mode. This is my second play through of tab1 today, started a new world new map, the first time round there was no issue. i was already updated to 4.0.1 before the first playthrough.
Bacon_Donut had this issue yesterday on stream, and spoke to darkosto about it and confirmed it as a bug, could not find any entry on here about it!!! sorry if it is duplicated.

![prestige](https://user-images.githubusercontent.com/49765945/56387910-82d3c100-621d-11e9-93e0-b0c0681ccd77.PNG)

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
