### ISSUE TITLE
Animals Cropping advancement issue

### ISSUE THREAD

**Issue by benchwarmer014** [Darkosto/SkyFactory4Issues#366]
## Bug Report
The advancement calls them "squid seeds" and "guardian seeds", but they are actually squid lily and guardian lily.
Also recipe for squid lily requires "uncraftable potion" (any potion works)...should update JEI to indicate that any potion works.

## Possible Solution
Should call them squid lily and guardian lily in the advancement so users know what they need to craft. Should update squid lily recipe to indicate that any potion works.

**Comment by sk2048** [comment]
Fixed in Darkosto/SkyFactory4@1f5b2e6
