### ISSUE TITLE
Prestige does not complete on second play through

### ISSUE THREAD

**Issue by misterhampton** [Darkosto/SkyFactory4Issues#371]
## Bug Report
 Completing prestige for a second time does not give the 1 point reward.

## Expected Behaviour
 Nothing happens once diamond obtained and all other quests are complete. This was my second play through today on a different map, the first time round went without any issue. The second time round once all quest were complete the "You Win" tab said 51/52 completed non pacifist mode. There was no changes made before, during or after the 2 play through's.

## Steps to Reproduce (for bugs)

1. Would need another play through of first tab,as mentioned this was my second playthrough.
2.

## Logs

* Client/Server Log: 
* Crash Log: https://gist.github.com/misterhampton/bd86e96deccd6ce69668792eb75ffedd

## World Information

* Preset: observatree
 
* Prestige: yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.1
* Java Version: 1.8.0.51
* Launcher Used: Twitch
* Memory Allocated: 10240mb
* Server/LAN/Single Player: singleplayer
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sk2048** [comment]
Known issue on ObservaTree, duplicates #289
