### ISSUE TITLE
Compact Chests items are visually not showing

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#372]
## Bug Report
The items inside of the compact chests are visually not showing up when you take items out or place them inside of it. It's just a visual bug, if you exit and reenter the chest, they are all there.

## Expected Behaviour
Visible items

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkiiLands

* Prestige: Y
4.0.0
* Modpack Version world created in:
 4.0.1.2 beta
* Additional Content Installed: Topography beta

## Client Information

* Modpack Version: 4.0.1.1
* Java Version: Latest
* Launcher Used: Twitch
* Memory Allocated: 8
* Server/LAN/Single Player: Server
* Optifine Installed:N
* Shaders Enabled:N

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by DingoX3** [comment]
Having the same issue after updating to 4.0.2. Gif below showing example.
![items sf4](https://user-images.githubusercontent.com/16032841/56448664-220cbd00-62df-11e9-9d7d-11d92a727254.gif)

**Comment by Davey876** [comment]
Let's get this to the top.
SUPER annoying

**Comment by wanybae** [comment]
I just updated to 4.0.2 then I have this issue too.

**Comment by bretterer** [comment]
This is happening to me as well, on a non-prestige world  in the Obsivertree world type.

**Comment by sk2048** [comment]
Please see #468 for a fix

**Comment by JackRuby1** [comment]
Fixed in 403
