### ISSUE TITLE
Infinitely regrowing Mob Plants when using Watering Can

### ISSUE THREAD

**Issue by vailreth** [Darkosto/SkyFactory4Issues#377]
## Bug Report

When using the Tiny Progressions Watering Can on a mob seed until it is mature the Seed will revert to its just planted state instead of despawning completely

## Expected Behaviour
After Harvesting the Mob Seed plant despawns as normal when harvested.
## Possible Solution
if this behavior can not be altered making it so that the Tiny Progressions watering can does not affect the mob seeds. 

## Steps to Reproduce (for bugs)

1. plant a mob seed, in my testing i used a cow seed, on grass

2. activate the Tiny progressions Watering Can and aim it at the mob seed until its mature.

3. harvest the mob seed and it will revert to its just planted phase

4. repeat the watering and harvesting when mature and it will continue to release mobs

## Logs

* Client/Server Log: https://gist.github.com/vailreth/fd20e67d45f77b67d6c56e9061e180c9.js
* Crash Log:

## World Information

* Preset: SkyVillage

* Prestige: enabled

* Modpack Version world created in:4.0.0

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version: jre1.8.0_201
* Launcher Used: ATLauncher
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Single player
* Optifine Installed:No
* Shaders Enabled:none

**Comment by sk2048** [comment]
There is a chance the seed will stay planted and regrow every time. You're probably just getting lucky when using the watering can :)

**Comment by ArbitraryHubris** [comment]
I planted two pig seeds, and used the Tiny Progressions watering can.  One disappeared after the first pig.  The other gave me 3 pigs.  So, can confirm it's RNG
