### ISSUE TITLE
Data model from Deep Mob Learning has no crafting recipe 

### ISSUE THREAD

**Issue by ferrium42** [Darkosto/SkyFactory4Issues#388]
## Bug Report
mod Deep mob learning ,no recipe from the data model is show in the Jei and the normal recipe isn´t working , example zombie , black model with an zombie head 
the only recipes i see is from the dragon and android 

## Expected Behaviour
show an craftable recipe

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
skyfactory 4 tutorial world
* Preset:
* Prestige: no

* Modpack Version world created in:
4.0.1
* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.1
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by roulito** [comment]
news?

**Comment by CharCharthemonkey** [comment]
im having the same issue on the tutorial world for SF4 on versions 4.0.1 4.0.2 and 4.0.3 with a new world created the recipes dont show for atleast half of the deep learning mod  but on other world types they do so and i am in prestiege mode (cause imo makes SF more fun)
