### ISSUE TITLE
Some way to find/generate villages?

### ISSUE THREAD

**Issue by NicholasRC7** [Darkosto/SkyFactory4Issues#391]
## Context

The mod "Matter Overdrive" requires a village, specifically a Mad Scientist, to progress in the mod. Without that, progress in that mod is impossible, or would require cheats (spawning in the mad scientist with a spawn egg).

**Comment by RetAlex** [comment]
You always can cure zombie villager with emerald egg and then breed them to spawn mad scientist, no?

**Comment by NicholasRC7** [comment]
Oh right, that must be a vanilla thing, then.
