### ISSUE TITLE
Allow access to all mods and game features

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Darkosto/SkyFactory4Issues#397]
## Context

Currently the prestige system still seems to control access to some mods and items even when it has never been enabled. I would like some way of turning this completely off unless prestige is actually enabled and has been asked to restrict based on progress. 
Unless there already is a way, how does one do this.

**Comment by nzminecraftDOTcom** [comment]
For example project E - players can't access it unless they unlock it. This is all with prestige off.

**Comment by sk2048** [comment]
ProjectE is disabled for all players at the moment because there is an issue that prevents it generating EMC for a large proportion of the items in the pack.

It will be reenabled as soon as ProjectE put out the fix.

**Comment by nzminecraftDOTcom** [comment]
Thanks that answers my question.
