### ISSUE TITLE
I was able to create a server but the world is default, how do I make it so it is normal skyfactory? 

### ISSUE THREAD

**Issue by Coolaid15972** [Darkosto/SkyFactory4Issues#408]
## Bug Report
Default world instead of skyfactory (the mods are implemented just the world isn't)

**Comment by sk2048** [comment]
We're trying to keep the issue tracker focussed on bugs, it's much easier if this kind of question is kept to the discord: https://discord.gg/darkosto

Plus you'll probably get an answer faster there!
