### ISSUE TITLE
Clay amber is not smeltable in the tinkers smeltery

### ISSUE THREAD

**Issue by matjojo** [Darkosto/SkyFactory4Issues#410]
## Bug Report

Cay Amber can not be smelted in the smeltery even though it can be made into clay pieces (4) and those can be smelted.

## Expected Behaviour

Clay amber can be smelted into 4 times the clay a clay piece gives

## World Information

* Preset: Flat

* Prestige: No

* Modpack Version world created in: 4.0.1

## Client Information

* Modpack Version: 4.0.1
* Launcher Used: twich
* Memory Allocated: 6 gigs

**Comment by sk2048** [comment]
See #752
