### ISSUE TITLE
[issue] Carry-on is locked and I can't see where

### ISSUE THREAD

**Issue by Layarion** [Darkosto/SkyFactory4Issues#418]
Logs: https://dl.dropboxusercontent.com/s/76l9eej5wk15tr5/logs.zip

## Bug Report
the mod "Carry On" seems to work when progression is disabled, but when enabled it doesn't. This suggest it's locked behind something, but when I press P and look, I don't see any prestige suggesting it has Carry On in it.

## Possible Solution
just make it more obvious which mods are locked away, and where.

**Comment by sk2048** [comment]
Carryon isn't locked, plenty of blocks are blacklisted as moving tile entities around often isn't expected and so causes bugs and crashes.

It also only works up to half your maximum reach, perhaps you were standing too far away.

I suggest you go to the discord for further support on this issue: https://discord.gg/darkosto
