### ISSUE TITLE
Using primitive crafting to craft a data model does not consume the items

### ISSUE THREAD

**Issue by darkphan** [Darkosto/SkyFactory4Issues#42]
Crafting a deep mob learning data model (for example a blaze one with the blank data model and blaze powder) using primitive crafting results in you getting the data model and as soon as you leave your inventory the blank data model is tossed on the ground and the item used to craft the data model is invisible in your inventory.

**Comment by Darkosto** [comment]
Just tested and this is fixed in the latest pack version. Thanks!
