### ISSUE TITLE
Prestige is disabled in LAN for other players

### ISSUE THREAD

**Issue by TrademarkTM** [Darkosto/SkyFactory4Issues#420]
## Bug Report
I recently opened a LAN game to play with a friend, and it seems like he can bypass all prestige blocks. For him, it seems like prestige is disabled, when for me it's not (world generated by me).

## Expected Behaviour
Prestige should be global?

## Steps to Reproduce (for bugs)
1. Generate a prestige world
2. Open to LAN
3. Ask someone to join, for them prestige will be disabled

## World Information
* Preset: Sky Factory 4
* Prestige: Yes
* Modpack Version world created in: 4.0.1

## Client Information
* Modpack Version: 4.0.1
* Java Version: 8
* Launcher Used: Twitch, new launcher
* Memory Allocated: 5 GB
* Server/LAN/Single Player: LAN
* Optifine Installed: Yes
* Shaders Enabled: No

I can't confirm what's the cause of the problem. I'm using ngrok to open the port, which is known to cause some IP issues (it redirects all IPs to local).

**Comment by sk2048** [comment]
LAN is generally a pain for mods to deal with and it's likely this can't be fixed. Try using a dedicated server; you might be able to run it on the same PC as your client if you have the spare resources.

**Comment by AriesStar1337** [comment]
You can manually fix this by doing this step by step
1.Use this command "/prestige force enabled" (Host doesn't have to)
2.Leave LAN (Host doesn't have to)
3.Host open saves folder / Your LAN world / playerdata / gamestages
4.Delete all .dat file except host (Check UUID before delete)
5.Tell your friend to join again!

Extra : Use "/tf" and "/prestige sync" to sync advancements and prestige

**Comment by jaredlll08** [comment]
Just going to say this now, I (prestige author) will not be supporting lan, so this won't be fixed.
