### ISSUE TITLE
aluminum truffle/resource hog missing

### ISSUE THREAD

**Issue by steelblueskies** [Darkosto/SkyFactory4Issues#424]
thought it odd, checked creative,still nothing.
checked the resource hogs config folder, no aluminum.json or similar verbiage.

i may be missing something, but it appears the quest for all truffles wants one thats missing the config file that adds it in.

**Comment by sk2048** [comment]
Aluminium was removed from the pack. The issue here is the advancement still wants it, not the hog missing.
