### ISSUE TITLE
The mulch upgrades are out of order in ADVANCEMENTS tab as well.  (not talking about prestige tab)

### ISSUE THREAD

**Issue by forshale** [Darkosto/SkyFactory4Issues#435]
## Bug Report
 So, as of 4.0.1, the prestige tab for mulch was out of order.  Turns out, it's also out of order for the Advancements tab. http://prntscr.com/necaou

## Expected Behaviour
  The order for mulch in the advancements should be fixed

## Possible Solution
 Fix the order for mulch item crafting in advancements tab as well

## Steps to Reproduce (for bugs)

1. Unlock mulch upgrades, for me until the ruby mulch (not including the ruby mulch prestige upgrade)
2. Check advancements tab (farming age) and look at the order.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
 
* Preset: SkyFactory 4

* Prestige: Yes

* Modpack Version world created in: 4.0.0, now in 4.0.1

* Additional Content Installed: Optifine

## Client Information

* Modpack Version: v4.0.1 , this bug is not listed in the 4.0.2 changelog as of yet
* Java Version: 1.8.0_51
* Launcher Used: Twitch
* Memory Allocated: 4gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by sk2048** [comment]
That's the correct order, the prestige descriptions and costs are wrong but the order is correct.
