### ISSUE TITLE
Compatched Storage chests items Disappear 

### ISSUE THREAD

**Issue by onlybentley** [Darkosto/SkyFactory4Issues#437]
## Bug Report
With Items in compatched chests, pulling an item out every item disappear and need to reopen for them to be visible again.  Anytime items are pulled or input into them from SSN, items also disappear.

## World Information

* Preset:Skylands

* Prestige: yes

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version:
* Launcher Used: multimc
* Memory Allocated: 8
* Server/LAN/Single Player: darkphans Test server
* Optifine Installed:
* Shaders Enabled:

**Comment by onlybentley** [comment]
Duplicate issue

**Comment by jumping-pig** [comment]
Issue here too, non prestige mode, standard preset

**Comment by nhoj187** [comment]
same here also, came to report started after 4.0.2 update

**Comment by sk2048** [comment]
Duplicate of #449, check for answers there
