### ISSUE TITLE
enderman seed advancement not triggering

### ISSUE THREAD

**Issue by billyty08** [Darkosto/SkyFactory4Issues#438]
## Bug Report

The animal seeds advancement under age of farming didn't trigger the advancement when crafting the enderman seed under age of farming
## Possible Solution

it asks for an endermen with an mEn and the actual seed is named enderman-mAn
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:village

* Prestige: yes

* Modpack Version world created in:4.0.1

* Additional Content Installed:

## Client Information

* Modpack Version:4.0.1
* Java Version:
* Launcher Used:twitch
* Memory Allocated:
* Server/LAN/Single Player:single
* Optifine Installed:no
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
This is just a typo in the criteria description. The advancement is looking for the item

`<animalcrops:seeds, nbt:{entity: "minecraft:enderman"}>`

Which is correct.

When I tested this it correctly detected me having an enderman seed.
