### ISSUE TITLE
JEI not showing all the pages?

### ISSUE THREAD

**Issue by Rakha030806** [Darkosto/SkyFactory4Issues#442]
## Bug Report

My JEI only shows about 54 pages.

## Expected Behaviour

In Chosen's playthrough, his's at 114 pages.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkyFactory 4

* Prestige: No

* Modpack Version world created in: Latest Version

* Additional Content Installed: 

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by jaredlll08** [comment]
Your screen size / gui scale is probably different than what he is playing on, if you actually counted how many items per row and column he has, it will be a lot less than what you have.
