### ISSUE TITLE
ComPatchedStorage - Chest GUI desync

### ISSUE THREAD

**Issue by BrainInBlack** [Darkosto/SkyFactory4Issues#449]
## Bug Report
Items visually disappear from the chest when clicking any slot inside the chest. This happens regardless of what kind of interaction is done, i.e. moving items in and out of the chest and so on.

## Expected Behaviour
Items to stay visible.

## Possible Solution
Re-opening the GUI

## Steps to Reproduce (for bugs)
Would love to reproduce the issue with a new chest, but i'm unable to craft a new chest (see #436)

## World Information

* Preset: Village

* Prestige: No

* Modpack Version world created in: 4.0.1

* Additional Content Installed: No

## Client Information

* Modpack Version: 4.0.2
* Java Version: 8
* Launcher Used: MultiMC/TwitchApp
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 8
* Operating System: Linux
* Hoster/Hosting Solution: MCProHosting
* Sponge (Non-Vanilla Forge) Server: No

**Comment by DingoX3** [comment]
![items sf4](https://user-images.githubusercontent.com/16032841/56449455-3e145c80-62e7-11e9-9796-ba2bb9f9f92b.gif)

**Comment by Drooski** [comment]
Seconded. I ended up downgrading the mod from 1.4 to 1.3, fixed it until they do :)

**Comment by Shadows-of-Fire** [comment]
Resolved as of compatched 1.4.1.

**Comment by BrainInBlack** [comment]
Confirmed fixed with version 1.5.1
