### ISSUE TITLE
Cottonwood Trees advancement triggers with breaking leaves, not using drying rack.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#45]
As the title said, the advancement for Cottonwood Trees triggers with breaking the leaves instead of using the leaves on the drying rack. 
Pack version 0.0.17

**Comment by JackRuby1** [comment]
Ah because the Cottonwood tree dropped string when I broke the leaves.

**Comment by Darkosto** [comment]
Added some additional text to help describe the process better.
