### ISSUE TITLE
Prestige Point not given while switching save between computers

### ISSUE THREAD

**Issue by jhardy82** [Darkosto/SkyFactory4Issues#450]
Bug Report

Prestige Point is not awarded while transferring single player save between computers.

Expected Behaviour

Should have 1 Prestige point while having YOU WIN! achievement
Possible Solution

Manually run command to add prestige point to player.

Steps to Reproduce (for bugs)

Start single player world on one computer and transfer the save folder to another computer

Logs

    Client/Server Log: I don't have access to the second computer riight now
    Crash Log: No Crash

World Information

    Preset: Sky Factory 4

    Prestige: Yes

    Modpack Version world: 4.0.2

    Additional Content Installed:

Client Information

    Modpack Version: 4.0.! && 4.0.2
    Java Version: 8
    Launcher Used: MultiMC
    Memory Allocated: 4096 - 6144
    Server/LAN/Single Player: Single Player
    Optifine Installed: No
    Shaders Enabled: No

**Comment by jaredlll08** [comment]
Prestige saves it's data in the /prestige folder, you need to move it along with the saves folder.
