### ISSUE TITLE
Stood on a Prismarine truffle while breaking it and crashed.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#453]
## Bug Report
Stood on a Prismarine truffle while breaking it and crashed.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/fAaY4dmS

## World Information

* Preset: Skiilands

* Prestige: Y

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: 402
* Java Version: Latest
* Launcher Used: Twitch
* Memory Allocated: 8
* Server/LAN/Single Player: Server
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by darkhax** [comment]
This issue is fixed in the next update. The original issue is produced as a race condition while looking at a truffle as it is broken.
