### ISSUE TITLE
Advancements

### ISSUE THREAD

**Issue by Explosivee** [Darkosto/SkyFactory4Issues#454]
I've updated my server to 4.0.2 and this started to happen
![image](https://user-images.githubusercontent.com/35429381/56450037-670a1100-632a-11e9-8bd1-4fa02829d649.png)

**Comment by ApolloMCC** [comment]
I have the same issue, basically some players can see their advancements, some don't and sometimes advancements come back

**Comment by Explosivee** [comment]
This is a real pain, please help

**Comment by ParkerMc** [comment]
Are you using sponge?

**Comment by ApolloMCC** [comment]
We've solved this thank you parker for responding. Me and explosive have the same server.
