### ISSUE TITLE
Acorn's forcing items into a furnace with a crafting station next to it.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#46]
A crafting station connect up next to a furnace will auto place whatever is in your upper right hand corner slot of your inventory into the furnace whether the item is cook-able or not. It seems to only be doing it when you hover over an acorn of some kind while pressing U, and selecting a recipe to put into the crafting station. You will be kicked out of the crafting station if the item will cook, and won't be if it's not.

Pack version 0.0.17

**Comment by Darkosto** [comment]
I removed the furnace from being on the connection list. This should help with that issue. Thanks!
