### ISSUE TITLE
AE2: Cobblestone Circuit Mold: not able to craft 

### ISSUE THREAD

**Issue by furbzy** [Darkosto/SkyFactory4Issues#463]
the chisel will not go in the inscriber so im confused idk if im doing it wrong nothing in the jei say i am

![4fb9428b67fe5c553ae84271fadde195](https://user-images.githubusercontent.com/49768639/56452978-079b0980-6308-11e9-8cb2-89be95a82346.png)

(GIF below)
[https://i.gyazo.com/57d79be204f4811d0b52be9a5a80ebcd.mp4](url)

**Comment by furbzy** [comment]
now it works after i make the bug report.

**Comment by AWDoBaun** [comment]
I saw this too on 4.0.1 shift click the chisel:chisel_diamond and it goes into the center slot of the inscriber not the top slot. And it cannot be manually moved to the top slot.

I was able to use chisel:chisel_iron and the stone and diamond chisel from chisel and bits fine though.

**Comment by mlegault55** [comment]
I ran into the same issue and found out that the inscriber only accept a brand new chisel for the circuit mold. Once a chisel that has been damaged, it can no longer be used in the recipe even if the chisel is fully repaired.

**Comment by Darkosto** [comment]
I changed this to use a chisel head cast from Tinkers' instead due to limitations on allowing damaged chisels. Should be a much easier item to use. Will be available in 4.0.6
