### ISSUE TITLE
Pressurized Reaction Chambers from Mekanism not Outputting Gases

### ISSUE THREAD

**Issue by forshale** [Darkosto/SkyFactory4Issues#464]
## Bug Report
 Pressurized Reaction Chambers won't output Gases, from what I've seen ethylene into Gas tanks, Other PRC's, and gas generators.  

Several screenshots: http://prntscr.com/neg0h3
http://prntscr.com/neg0va
Gas Tank from Electrolytic Separator: http://prntscr.com/neg0xr
Gas Tank from PRC http://prntscr.com/neg10m

## Expected Behaviour
 Nothing happens.  Even on the correct side of the PRC, the ethylene remains in the chamber instead of sourcing out to the tank, generator, or other chamber.

## Possible Solution

(edited, was missing before)  I genuinely don't know why itd be doing this, So sorry I cant be of much help here.  Maybe the output for gases file is messed up in the config for PRC's..?

## Steps to Reproduce (for bugs)

1. Setup water condenser by infinite water source and connect to back of Electrolytic Separator, do the same for the PRC
2. Supply the PRC and Separator energy via any generator/battery
3.  Connect the left side of the Separator to the left side of the PRC via Pressurized tube (any) 
4.  Input biofuel to the PRC, as it produces substrate, it also produces ethylene
5.  Connect the right side (output) of the PRC to a Gas Tank, Gas generator, or another PRC's left side.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkyFactory 4, tested in Flat 

* Prestige: Yes

* Modpack Version world created in: SkyFactory 4 - 4.0.0,  Flat - 4.0.2
 
* Additional Content Installed: Optifine

## Client Information

* Modpack Version: v4.0.2
* Java Version: 1.8.0_51 64 bit
* Launcher Used: Twitch
* Memory Allocated: 4gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

Edit: NOT A BUG FIXED ISSUE PLEASE CLOSE

**Comment by forshale** [comment]
This also has the side effect of once the ethylene gas bar maxes out, you cant input any biofuel

**Comment by Chip166** [comment]
I am still having this same issue. Have you been able to get it to work? and if so, could you please share.

**Comment by forshale** [comment]
One of the later updates fixed this, should probably close this.  Use a configurator on a pressurized pipe and set the pipe touching the right side of the machine to pull and the output end to push.  Should fix :D
