### ISSUE TITLE
can't use Topography in forge spigot server to run the starting commond 

### ISSUE THREAD

**Issue by JackMeds** [Darkosto/SkyFactory4Issues#472]
## Bug Report
i can't use Topography in forge spigot server to run the starting command 

## Logs
no log

## Server Information
* Java Version: 201
* Operating System: windows server 2019
* Hoster/Hosting Solution: Private Server
* Sponge (Non-Vanilla Forge) Server:
no sponge just catserver

**Comment by stevojhall** [comment]
if this is because of the generation not allowing spaces, check out my enhancement request "Servers not able to use all world types"

**Comment by JackMeds** [comment]
> if this is because of the generation not allowing spaces, check out my enhancement request "Servers not able to use all world types"

It's different from what I'm trying to say.OP can get starting items.

**Comment by stevojhall** [comment]
This seems like a permissions issue, if you have access you need to add yourself as a server op

**Comment by JackMeds** [comment]
> This seems like a permissions issue, if you have access you need to add yourself as a server op

thanks,i already fix it
