### ISSUE TITLE
where is ae2stuff?

### ISSUE THREAD

**Issue by jxdelta** [Darkosto/SkyFactory4Issues#476]
why ae2stuff not in modpack? its really great addon that make apllied more comfortable. i hope that you add that in next updates
https://minecraft.curseforge.com/projects/ae2-stuff

**Comment by Streamcyper** [comment]
It was in the pack but got removed due to a bug [Darko Explains](https://clips.twitch.tv/PiliablePrettiestWoodcockBloodTrail)
