### ISSUE TITLE
Add faster leaf decay

### ISSUE THREAD

**Issue by Czorio** [Darkosto/SkyFactory4Issues#477]
## Context
As this mod pack has replaced hammering and sieving blocks with growing trees to gather resources, you spend a lot of time growing and cutting down trees. An additional amount of time is spent waiting on the leaves to finally decay, so you can get their drops and free up the airspace for new trees, so you can start the process again with a different type of tree.

While it is possible to remove the leaf blocks by hand, this is a tedious process and easily doubles the amount of time spent on one batch of trees. I propose the inclusion of the Fast Leaf Decay mod to make this aspect of the pack a little more enjoyable/streamlined.

## Mod Details
* Name: Fast Leaf Decay
* CurseForge Link: https://minecraft.curseforge.com/projects/fast-leaf-decay

**Comment by DingoX3** [comment]
I believe this is intended to encourage people to unlock Ore Excavator in prestige mode. If your not in prestige mode then you can just vein mine them, no need to wait.

**Comment by Czorio** [comment]
Fair, I figured the Ore Excavator stuff was more intended for the trunk of the trees rather than the leaves.

**Comment by sk2048** [comment]
As DingoX3 said, this was considered and the decision was not to include it.
