### ISSUE TITLE
Enriched Iron is useless

### ISSUE THREAD

**Issue by FunnyMan3595** [Darkosto/SkyFactory4Issues#480]
As of 4.0.1, it's possible to create Enriched Iron in a Mekanism Metallurgic Infuser, but since that method for creating steel is disabled, it's a useless item.  Should be disabled.

**Comment by DingoX3** [comment]
I agree removing the recipe might cause less confusion when at the point your looking for steel.

**Comment by sk2048** [comment]
Believe this is fixed in 4.0.2, please update and open a new issue if you still find this to be an issue.
