### ISSUE TITLE
Forgiving Void is less forgiving

### ISSUE THREAD

**Issue by crazydud24** [Darkosto/SkyFactory4Issues#483]
## Bug Report

I began hosting my own server for me and a friend to play last night after enjoying the pack solo. I jump off the edge to show him the forgiving void mod and just end up dying, unlike my single player world where the mod acted normally.

## Expected Behaviour
upon falling into the void the player should reappear at the top of the world.

## Possible Solution
I tried poking around the server files for a fix in the configs but I am rather entry level at this whole thing and didn't want to break anything, my best guess would be in configs or prestige or world type.

## Steps to Reproduce (for bugs)

1. download server files for sky factory 4, follow the README file, and port forward
2. join server 
3. fall into void

## Logs
* Client/Server Log: https://pastebin.com/dSjtPJ9C
note, I jumped off intentionally at the very end 
* Crash Log: no crash

## World Information

* Preset: default

* Prestige: default (I believe not)

* Modpack Version world created in:  server pack 4.0.2

## Client Information

* Modpack Version: 4.0.2
* Java Version: "1.8.0_201" 
* Launcher Used: twitch
* Memory Allocated: my client: 10G (i know its stupid) server 4G
* Server/LAN/Single Player: personally hosted server
if needed the ip is 76.19.236.150 i host off my pc and may not always have it up
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: "1.8.0_201" 
* Operating System: windows 10
* Hoster/Hosting Solution: not fully sure what this means (I host the server)
* Sponge (Non-Vanilla Forge) Server: again don't know what this means, I am using the provided server files with no modification at all.

**Comment by sk2048** [comment]
Delete this report and repost without your public IP address.
