### ISSUE TITLE
Server files in 4.0.2 have sevtech mods instead of the sky factory 4 mods

### ISSUE THREAD

**Issue by R4smR** [Darkosto/SkyFactory4Issues#485]
### **ISSUE**
The server files have the Sevtech: Ages mods instead of the SkyFactory4 mods.

### Possible fix
Put the correct mod files into the download

### Steps to reproduce

1. Download the 4.0.2. server files
2. Look into the server mod folder
3. Compare the server mod files to the mod list

**Comment by sk2048** [comment]
This is not true, where did you get your server files from?
https://minecraft.curseforge.com/projects/skyfactory-4/files/2701281

**Comment by Autom3** [comment]
The zip file for updating servers on curseforge has not got any mods in the overrides folder for me.
There's also a missing mod update in the changelog: MekanismGenerators

**Comment by sk2048** [comment]
The server zip does not have an overrides folder, that download is for setting up a client using Twitch import or MultiMC. The `manifest.json` contains a list of mods that the launcher retrieves when you import it.

Use the link I gave above to get the server files complete with the mods, start and install scripts, example server.properties file and documentation.

**Comment by sk2048** [comment]
Thank you for pointing out the missing mod update from the changelog, I shall add that now.

**Comment by R4smR** [comment]
I have no idea why the server files were messed up, but I got the right files from the download link.
