### ISSUE TITLE
Spawners and silk touch

### ISSUE THREAD

**Issue by ghost** [Darkosto/SkyFactory4Issues#486]
The spawners would have to have a description that says "obtainable with silk touch".

I looked for the bag of holding (cyclic) and I did not find it, I went crazy thinking and searching for a spawner holder or something like that just to discover that you can silk touch it in a copy of my world

**Comment by darkphan** [comment]
If you look at the info tab of a spawner in JEI it will show you [this](https://i.imgur.com/M6QzBvj.png)
