### ISSUE TITLE
Leaves from Bonsai pots

### ISSUE THREAD

**Issue by GingerStud** [Darkosto/SkyFactory4Issues#488]
I'm just wondering if it would be possible to use a crook like an axe on bonsai pots for a higher chance to get leaves. It's not a big change but when you're trying to get leaves early game it would be a nice option.

**Comment by dewboy3d** [comment]
Seems trivial to manually plant a sapling and use shears to get leaves. Not sure modifying bonsai pots is the way to go for this.

**Comment by GingerStud** [comment]
Oh my goodness. I am an idiot. I didnt even think of sheers.i should remove this.
