### ISSUE TITLE
bug with compact storage chest disappearing items

### ISSUE THREAD

**Issue by bloodyraingaming** [Darkosto/SkyFactory4Issues#492]
## Bug Report
open my compact storage chest pull one item out all other items dissapear

## Expected Behaviour
grabbed 1 item out of compact storage chest all other items vanish till i re open the box

## Steps to Reproduce (for bugs)
place a max capacity compact storage chest put a bunch of items in and remove one
1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 
4.0.2
* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by DeciTM** [comment]
Already reported here https://github.com/Darkosto/SkyFactory4Issues/issues/468
