### ISSUE TITLE
[BDS&M] Metal crate has same storage limit as wood crate

### ISSUE THREAD

**Issue by DeciTM** [Darkosto/SkyFactory4Issues#493]
## Bug Report
The metal crate is showing the same storage limit as the wood crate.

## Expected Behaviour
I was expecting it to be a lot higher.

## Possible Solution
Increase set it to whatever the limit should be, otherwise outside of aesthetics I don't know a reason to use metal crates.

## Steps to Reproduce (for bugs)
1. Craft and place wood crate
2. Craft and place metal crate next to wood crate
3. Compare values

## World Information

* Preset: Default

* Prestige: No

* Modpack Version world created in: 4.0.2

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.2
* Java Version: jre1.8.0_192
* Launcher Used: ATLauncher
* Memory Allocated: 8192mb
* Server/LAN/Single Player: Seerver
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Don't know
* Operating System: Don't know
* Hoster/Hosting Solution: Sticky Piston
* Sponge (Non-Vanilla Forge) Server: No

![image](https://user-images.githubusercontent.com/31772276/56461151-d69bf280-6362-11e9-861a-1f5c8ccfb7c4.png)

**Comment by darkphan** [comment]
The metal ones can hold more upgrades than the wooden ones though, so they can end up holding a lot more items.

**Comment by DeciTM** [comment]
> The metal ones can hold more upgrades than the wooden ones though, so they can end up holding a lot more items.

Ahh okay, it's probably just my misunderstanding how the mod is intended to work. I expected it to have a larger base value.
