### ISSUE TITLE
[need help]update standalone 4.0.1 server to 4.0.2

### ISSUE THREAD

**Issue by Layarion** [Darkosto/SkyFactory4Issues#497]
Hey i'm trying to update my stand-alone server (just a folder, not some rented service) to the update, and everytime i try to copy and paste over the config, mods, prestige, server.properties, and world file - when i actually run server.bat it loads up...for a few seconds and then shuts down with no reason on the console as to why.

how do i update my already existing server and carry over my world and player prestige/teams?

**Comment by sk2048** [comment]
We use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please use our Discord for support. https://discord.gg/darkosto
