### ISSUE TITLE
Spelling Error in Advancements item for Cottonwood

### ISSUE THREAD

**Issue by ke4ktz** [Darkosto/SkyFactory4Issues#499]
## Bug Report
In the Advancements tree, first tab, the listing for the Cottonwood Sapling has a misspelling.  The entry states: Craft a Cottomwood Sapling

## Expected Behaviour
Entry should read: Craft a Cottonwood Sapling

## Steps to Reproduce (for bugs)
1. Hover over the entry in the Advancements tree.

## World Information

Default.  Running on Deadpine's subscriber server

* Prestige: No.

## Client Information
* Modpack Version: 4.0.1
* Java Version: 1.8.0
* Launcher Used: Native
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Server
* Optifine Installed: None.
* Shaders Enabled: None

**Comment by sk2048** [comment]
Fixed in 4.0.2, which is already out.
