### ISSUE TITLE
Picking up pairs of translocators and placing them crashes the game

### ISSUE THREAD

**Issue by observeroftime02** [Darkosto/SkyFactory4Issues#504]
Running vesion 4.0.2 in single player

* Place down two tanks and set up a pair of translocators between them
![2019-04-20_16 47 58](https://user-images.githubusercontent.com/43228249/56463584-14614100-638c-11e9-9b01-cf9f02579145.png)
* Shift+Right Click the plate of the translocator with empty hand
* You have now picked up the pair of translocators
![2019-04-20_16 48 34](https://user-images.githubusercontent.com/43228249/56463591-2c38c500-638c-11e9-9693-1ccfea928802.png)
* Placing it back in the original spot replaces the translocators without issue
* Placing them anywhere else crashes the game

Here's a [log of the crash](https://paste.ee/p/EJsFl) starting from the beginning. Any other relevant information is in the crash log.

**Comment by observeroftime02** [comment]
Which mod reports are needed, because I'm going to submit them. Looking at the log this seems to be a translocator specific bug, or is this related to the mod that lets you pick up everything (no idea which one that is).

**Comment by sk2048** [comment]
The mod that allows you to pick up tile entities is CarryOn, we'll blacklist the translocators from being picked up but if you send a report to CarryOn they'll include them in the default blacklist. It makes no sense to allow them to be picked up.

**Comment by observeroftime02** [comment]
Done
