### ISSUE TITLE
ComPatchedStorage

### ISSUE THREAD

**Issue by GamingWithFusion** [Darkosto/SkyFactory4Issues#509]
## Bug Report
 Chest Builder in ComPatched Storage not building chest

## Expected Behaviour
 I put in the needed items and press the crafting button and nothing happens nor does it take my items instead of it taking my items and making the chest

## Possible Solution
 It would be handy to have more storage so drops won't crash servers.

## Steps to Reproduce (for bugs)
 
1. Get needed items.
2. Put in chest builder and press craft.
3. No items get crafted or taken.

## Logs

* Client/Server Log: https://gist.github.com/GamingWithFusion/bf9e5e5b40c214b4491f6e45caebd936

## World Information
 
* Preset: Default SF4 Skyblock Map
 
* Prestige: Yes
 
* Modpack Version world created in 4.0.1

* Additional Content Installed: Default, no additional mods.

## Client Information

* Modpack Version: 4.0.2
* Java Version: Version 8 Update 201
* Launcher Used: Twitch
* Memory Allocated: 8000 MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version:  1.8.0_171
* Operating System:  Windows 10 Pro
* Hoster/Hosting Solution: Dedicated Server/ Self Hosted
* Sponge (Non-Vanilla Forge) Server: No

**Comment by DeciTM** [comment]
Related to https://github.com/Darkosto/SkyFactory4Issues/issues/468
