### ISSUE TITLE
[.19] Recipe conflict for DML.

### ISSUE THREAD

**Issue by Demlou6** [Darkosto/SkyFactory4Issues#51]
Twilight Swamp Data Model has duplicate recipes that prevent the 'basic' tier from being created in pacifist mode without work-arounds:

https://gyazo.com/908b6390cb04d697c0b3fb74d06805ad

**Comment by Demlou6** [comment]
Also applies to enderman:

https://gyazo.com/7cdbdb2bc0cbaf7bffe81dfe894b2e19

**Comment by Demlou6** [comment]
Blaze and Blue slime as well.

**Comment by justinrusso** [comment]
Need to assign non-passive worlds with a "non_passive" stage, and assign all default recipes to that stage.

**Comment by justinrusso** [comment]
Fixed in https://github.com/Darkosto/SkyFactory4/commit/06c55ba4ec596ba4afcf50a755a879c7a458859c
