### ISSUE TITLE
Feed the Chickens! & Egg Hunt -- Advancement Issues

### ISSUE THREAD

**Issue by AndrewUHD** [Darkosto/SkyFactory4Issues#511]
**## Bug Report**
Feed the Chickens! advancement and Egg Hunt advancement are not obtainable.

**## Expected Behaviour**
The item needed for Feed the Chickens (GM Chicken Feed from Mob_Grinding_Utils) is un-craftable.
Even after the item is achieved, when you click on a chicken with the feed in your hand, the chicken only gives feathers. This might be due to the chicken spawn egg (from Vanilla Minecraft) is not an attainable item in-game. (See attached video for proof)

**## Possible Solution**
Fix recipe for Chicken Feed, switch drop from event from Chicken Spawn Egg to Chicken Seeds.

**## Steps to Reproduce (for bugs)**
https://youtu.be/VUXikZZiPOo

**## Logs**
Client log: https://gist.github.com/AndrewUHD/8deb6d965827e17191b0d4f5c65deec7
Server Log: https://gist.github.com/AndrewUHD/130701274499c779f0b09a50eb2e3a80
No Crash Logs
MG Chicken Feed Recipe:
![image](https://user-images.githubusercontent.com/49825607/56464757-2eb01480-63b6-11e9-8b0d-9378f86e4605.png)

**## World Information**
Preset: **Skyblock**
Prestige: **Disabled**
Modpack Version world created in: **4.0.1**
Additional Content Installed:  **N/A**

**## Client Information**
Modpack Version: **4.0.1**
Java Version: **J8U191**
Launcher Used: **Twitch**
Memory Allocated: **8 GB**
Server/LAN/Single Player: **Server**
Optifine Installed: **No**
Shaders Enabled: **No**

**## Server Information**
Java Version: **J8U191**
Operating System: **Windows Server 2016**
Hoster/Hosting Solution: **Myself**
Sponge (Non-Vanilla Forge) Server: **forge-1.12.2-14.23.5.2831-universal**

**Comment by sk2048** [comment]
The advancement describes the recipe, it works:
<img width="236" alt="Screenshot 2019-04-21 at 14 16 08" src="https://user-images.githubusercontent.com/23245543/56470777-0c63d880-6442-11e9-8308-274f98711b72.png">

The chicken feed you spawned in did not have the NBT that tells it which mob to return the egg of.

Here is an example of how to carry out every step to get a chicken spawn egg from killing a chicken. Excuse the terrible quality, I have terrible upload rate.

![recording](https://user-images.githubusercontent.com/23245543/56470755-dcb4d080-6441-11e9-96e8-13cac822f8d8.gif)
