### ISSUE TITLE
There is no Hopping Bonsai Recipe (This Template is confusing btw)

### ISSUE THREAD

**Issue by UnderTracer** [Darkosto/SkyFactory4Issues#515]
## Bug Report
 There is no recipe for the Hopping Bonsai Pot (Its doesnt even exist in game for some reason)

## Expected Behaviour
 I cant craft a Hopping Bonsai Pot

## Possible Solution
 Fix it I guess.

## Steps to Reproduce (for bugs)

1. What?
2.

## Logs
 I do not understand

* Client/Server Log:
* Crash Log:

## World Information
 Normal Skyfactory 4 (Prestige)
* Preset:
 Yes
* Prestige: 

* Modpack Version world created in: 4.0.2
 Vein Miner which I disabled
* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version: Lastest
* Launcher Used: Native
* Memory Allocated:
* Server/LAN/Single Player: Single
* Optifine Installed: No
* Shaders Enabled: No

**Comment by darkphan** [comment]
Sounds like you are playing with prestige enabled, you will need to earn a prestige point and spend it on the Hopping Bonsai.
