### ISSUE TITLE
[.19] [Balancing] Simple Generator output for various items.

### ISSUE THREAD

**Issue by Demlou6** [Darkosto/SkyFactory4Issues#52]
I know you've done some with the ender dragon drops, here are a few more to look at:

I used 4 stacks of speed upgrades in each generator for the purpose of output generation, as they do not seem to decrease efficiency:

- Nether Star Generator and nether stars (look at the recipe from DML for nether stars, wither skeleton heads are easy to get from DML Wither skeleton model, both matter types are easy to get, soul sand isn't a thing, and the energy output profit is like 95% assuming Wither skeleton heads are the difficult part of the recipe)
- Culinary Generator foods (this is way too big to fix probably, but here are a few: hydra chops [dml > generator],  some XL foods that give 0 [salt, any of the drinks, diamond and emerald apples maybe, dominos special maybe)
- Combustion Generator fuels (alchemical fuel from projecte, though honestly i doubt this is a big deal; this generator is fairly balanced)
-Ender generator (It's ok, but honestly forgettable, this one could use some love/additions, or straight up remove the generator)
- Geothermal, Turbine and Fluid combustion (with full upgrades these things can produce a lot, but full upgrades starts causing it to bug out sometimes) https://gyazo.com/acad17257e80da7a328c2f9c62d55944

**Comment by Demlou6** [comment]
You also net gain from nether stars just using the wither too.

**Comment by Demlou6** [comment]
Better clarity with numbers on the liquid ones, the rate never changes so this is the max output.

https://gyazo.com/6898f15ae464585db2123106be5d248f

**Comment by Darkosto** [comment]
I'll get to re-balancing these this week.

**Comment by Demlou6** [comment]
[simplegenerators.zip](https://github.com/Darkosto/SkyFactory4Issues/files/2621833/simplegenerators.zip)

Here is an updated config with major changes to the culinary and combustion generators.

**Comment by Darkosto** [comment]
Adding onto this for later, Simple Generators allows for OreDict: 

OD for single value with that ore dictionary entry
OD_PREFIX for all with that prefix
