### ISSUE TITLE
Question about twilight forest 

### ISSUE THREAD

**Issue by Teslachu** [Darkosto/SkyFactory4Issues#525]
Hi! I'm playing on a server, version 4.0.1 and I made the cake to go to twilight forest... Is it suppose to be void? Cause I spawned on some Obsidian and could see a lich king castle, but there was no terrain or anything...so I'm wondering if this is as intended since I know one of the advancements talks about being able to get mats from there.

**Comment by JackRuby1** [comment]
The terrain is a void world yes, you need to either build to areas or fly there. The boss areas still spawn.

**Comment by Teslachu** [comment]
That makes no sense, considering under "Advancements - Age of Exploration" it says "Travel to the lost cities or twilight forest to locate ____ ore and mine it to acquire ____" ~ I mean if it is meant to be a void world, then the wording should be changed to "Travel to the lost cities to locate ____ ore and mine it to acquire ____"

**Comment by JackRuby1** [comment]
Yes, the terrain under the bosses is still there, just like the Lost Cities has ore gen inside of Domes.

**Comment by Teslachu** [comment]
Well not the one the server. An admin checked it out, there is no terrain there, like there is in Lost Cities.

**Comment by Dynamic1237** [comment]
In the prestige page (if prestige is enabled) it states that twilight forest is set in a void world when you go to unlock it
