### ISSUE TITLE
NBT folder crafting recipe requires uncraftable potion

### ISSUE THREAD

**Issue by Psyvana** [Darkosto/SkyFactory4Issues#526]
## Bug Report
Filing cabinet NBT folder requires an impossible item for survival :( 

## Possible Solution
Please swap to something accessible (to non-cheaters hehe)

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
Uncraftable potion is a placeholder for any potion. Usually this includes a plain old water bottle.
