### ISSUE TITLE
So I can't install it due to an add-on missing

### ISSUE THREAD

**Issue by TimBukTwo8462** [Darkosto/SkyFactory4Issues#527]
I try to install the pack on the twitch app on my computer and it gets to deleating the temporary folder but then it switches to canceling instillation. Then I get an error message saying "Cannot find addon dependency 61811". I have tried to install it 3 times now and it still gives me that issue.

**Comment by xcorvis** [comment]
I had a similar problem. Completely exit and restart twitch. If that doesn't work, repair the profile.

**Comment by sk2048** [comment]
Twitch issue, not a problem with the pack. Please go to the Discord for further support https://discord.gg/darkosto

**Comment by TimBukTwo8462** [comment]
Oh, so in case someone else finds the same issue, twitch is a little buggy and won't detect Java versions. So I installed the newest version and deleted the old ones. That fixed my issue.
