### ISSUE TITLE
World not loading stuck on loading terrain

### ISSUE THREAD

**Issue by BluuJayy** [Darkosto/SkyFactory4Issues#529]
I’ve changed the render distance, VBOs, i have 6gb allocated to minecraft and have reinstalled sky factory but it is still stuck on loading terrain. i just wanna join my world

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by justinrusso** [comment]
I'd recommend you trying to get help from people in the discord server.
