### ISSUE TITLE
Issues connecting to servers

### ISSUE THREAD

**Issue by carrick121203** [Darkosto/SkyFactory4Issues#534]
When i try to connect to a server I get a **"fatally missing registry entries"** error then if I try to connect again it says **"com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@51aaa9d4) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@281ca256)"** my log is at https://pastebin.com/ZADN5AWf

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
