### ISSUE TITLE
Simple storage network showing more

### ISSUE THREAD

**Issue by PaX101** [Darkosto/SkyFactory4Issues#536]
## Bug Report

Storage request table from Simple storage networks is showing 2x the amount of items that are in crates. When you take them out you only get half of what is showing on the screen.

## Expected Behaviour

When connecting more than 1 Storage link cable it should recognise it is comming from the same location.

## Steps to Reproduce (for bugs)

1. Create Simple storage network then connect to Shipping container with 2 or more Storage link cables.

## Logs

* Crash Log:
latest.log - https://gist.github.com/PaX101/d41811cd2ceadba7ceab4f64840a9b3d
debug.log - https://gist.github.com/PaX101/5779a8122167502b1397b23c14e06710

## World Information

* Preset: Lost Cities
* Prestige:  Disabled
* Modpack Version world created in: 4.0.2

## Client Information

* Modpack Version: 4.0.2
* Java Version: 1.8.0_201 64bit
* Launcher Used: Minecraft Launcher 1.6.91
* Memory Allocated: 8192 mb
* Server/LAN/Single Player: Single player

**Comment by darkphan** [comment]
This does not appear to be an issue. This will happen with other storage systems, such as AE2. It should be up to the user to make sure they only hook one Storage Link Cable, Storage Bus, etc to an inventory.
