### ISSUE TITLE
Inferium ore not spawning

### ISSUE THREAD

**Issue by StrangeSorcerer** [Darkosto/SkyFactory4Issues#539]
## Bug Report
Currently only finished age 1, tried searching for Inferium ore in the nether in order to make obsidian faster for tinkers, found none.
[latest.log](https://github.com/Darkosto/SkyFactory4Issues/files/3101659/latest.log)

## Expected Behaviour
I tried to find Inferium ore in the nether with no luck, even went into creative to try and find some.

## Steps to Reproduce (for bugs)

1. 
2.

## Logs

* Client/Server Log: https://gist.github.com/StrangeSorcerer/01d8f5fb9f4b512208229f8d70c0d7c9
* Crash Log:

## World Information

* Preset: Sky Factory 4

* Prestige: Disabled

* Modpack Version world created in: 4.0.2

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version: Version 8 Update 211, build 1.8.0_211-b12
* Launcher Used:
* Memory Allocated: 5196M
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by AshZification** [comment]
Do you have any ores spawning in the nether? 
Have you unlocked anything outside of the first tab of achievements?

**Comment by justinrusso** [comment]
Inferium Ore does not spawn as it was intended.

Search JEI for other methods to get started with Mystical Agriculture.
