### ISSUE TITLE
Mulitple Advancements not triggering 0.0.18

### ISSUE THREAD

**Issue by SupaSloth** [Darkosto/SkyFactory4Issues#54]
- Crafting a Dehydrator does not trigger advancement
- Pig Treadmill doesn't trigger advancement
- Crafting a Zombie Data Model does not trigger advancement
- Overworld Cake does not trigger advancement; Eaten in Twilight Forest
- Travelling to the Twilight Forest does not trigger advancement
- Crafting an Unbreakable Tinker's Tool does not trigger advancement

**Comment by Darkosto** [comment]
Just tested all of these and they all seem to work with no issue. Did they not go into your inventory?

**Comment by SupaSloth** [comment]
For whatever reason yesterday, they would not trigger. I tried multiple times and ways. Today, which I guess would included a relaunch and relog, they are all triggering as expected. The only thing that I can think of that I did yesterday was try to eat overworld cake while in the overworld. Not sure if that screwed with anything.

All good.

**Comment by justinrusso** [comment]
OH! Yeah that would be the issue. We've found the overworld cake bug already. Nothing you do during that time was syncing (try dropping an item and seeing how you cant pick it back up). This is fixed in dev if its not already sent out as an alpha.
