### ISSUE TITLE
Simple Storage not registering Stock upgrade.

### ISSUE THREAD

**Issue by forshale** [Darkosto/SkyFactory4Issues#541]
## Bug Report
 When inserting the stock upgrade item into a storage export cable, that cable does not register the stock upgrade item even though a chest or other container/inventory is displaying the items that it wants to keep.

## Expected Behaviour
 The stock upgrade should work to keep certain items in the export cable.  

## Possible Solution
 Something could be happening when the export cable registers the inventory to determine the item.  However I noticed that the Export cable simply won't allow anymore than a single item of a specific item at once.

## Steps to Reproduce (for bugs)

1. Set up export cable connected to Storage Network Master that is hooked up to an inventory with items
2.  When placed/connected to an inventory, fill the inventory with the amount of items, and put the stock upgrade into the export cable
3.  Witness how you aren't allowed to put more than 1 item of that item into the cable 

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkyFactory 4 and Flat

* Prestige:  Yes

* Modpack Version world created in: v4.0.0 and v4.0.2

* Additional Content Installed: Optifine

## Client Information

* Modpack Version: v4.0.2
* Java Version: 1.8.0_51 64 bit
* Launcher Used: Twitch
* Memory Allocated: 4gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by kobini2** [comment]
This seems to have been fixed in Simple Storage Network 1.7.4.
