### ISSUE TITLE
Parabox Prestige Distribution

### ISSUE THREAD

**Issue by Tomstah** [Darkosto/SkyFactory4Issues#543]
## Context
Upon prestiging on a server, all points are given to all members.  This allows members starting on their own seperate islands to skip past, even if they do not wish to.

## Intended Solution
Allow a server configuration to change whether or not prestige is awarded just to the people who are on during a collapse, team members of those who are on during a collapse, or everyone all-time.

**Comment by justinrusso** [comment]
Please suggest this request here: https://github.com/Shadows-of-Fire/Parabox/issues
