### ISSUE TITLE
What is the Command to Sync Achievements with Friend?

### ISSUE THREAD

**Issue by Kapyyy** [Darkosto/SkyFactory4Issues#544]
I can't remember what the command is.  If someone could leave a comment letting me know that would be great.

**Comment by justinrusso** [comment]
If you have questions like this please refer to the discord channels for SF4. There is a community there that will happily help you out.

`/togetherforever forcesync`

**Comment by Kapyyy** [comment]
What is the discord.

**Comment by justinrusso** [comment]
http://bit.ly/DarkostoDiscord
