### ISSUE TITLE
Server Lag then Crash after 60Sec tick

### ISSUE THREAD

**Issue by LucklyUnlucky** [Darkosto/SkyFactory4Issues#549]
Unable to narrow down the cause, I have 6gb Ram on my server that (at the time of crash) had 3 people on it, in total we have around 5/6 playing. Whenever we went to one of the players bases the lag would go down and when we left it came back. Here is a crash-log.

https://pastebin.com/XAuAXT2m

**Comment by Possemaster** [comment]
I had the same issue, In the Server.Properties I disabled by changing MaxTickTime to -1. 
I logged in no issues on the server, One other guy joins, the issue starts.
So rerun the test, I log in, fly to his base, Base pops in view get error message in Console;
`[ERROR] [HorsePower]: Error in config, could not find (pokefenn.totemic.entity.animal.EntityBaldEagle) mob class, mod for entity might not be installed

[ERROR] [HorsePower]: Error in config, could not find (pokefenn.totemic.entity.animal.EntityBuffalo) mob class, mod for entity might not be installed`
Server ticktime went to 93000ms

As I Turned off MaxTickTime the server kept running, I ran /profile e and saw the grindstone was causing the issue. removed the grindstone. Server went back to normal.

Placed back the grindstone, nothing happened.
No Clue....

**Comment by LucklyUnlucky** [comment]
> I had the same issue, In the Server.Properties I disabled by changing MaxTickTime to -1.
> Also installed TickProfiler mod on the server side.
> I logged in no issues on the server, One other guy joins, the issue starts.
> So rerun the test, I log in, fly to his base, Base pops in view get error message in Console;
> 
> **[ERROR] [HorsePower]: Error in config, could not find (pokefenn.totemic.entity.animal.EntityBaldEagle) mob class, mod for entity might not be installed
> 
> [ERROR] [HorsePower]: Error in config, could not find (pokefenn.totemic.entity.animal.EntityBuffalo) mob class, mod for entity might not be installed**
> Server ticktime went to 93000ms
> 
> As I Turned off MaxTickTime the server kept running, I ran /profile e and saw the grindstone was causing the issue. removed the grindstone. Server went back to normal.
> 
> Placed back the grindstone, nothing happened.
> No Clue....

I know nobody is using horse power yet on the server.
I'll see if someone has a grindstone though.
Glad to see i'm not the only one having this issue.
Will keep everyone posted.

**Comment by LucklyUnlucky** [comment]
Lag seems to be resolved now, Myself and another player had ItemDucts connected to Crates for our hopping bonsai's and he also had a itemduct with a servo connected to an autoclicker, upon testing  we found that if the itemduct is connected to a storage and has items to put there but the storage is full (In our case have 64 stacks of wood in a crate with no upgrades) it attempts to pull the item but can't and continues to do this until the server crashes.

Our fix:
We put void upgrades on our crates for those items that filled up (Wood and sticks) and for the autoclicker we just put it ontop of the cobble generator so it wouldn't cause lag with ItemDucts.
