### ISSUE TITLE
AE2: crystal seeds not growing 

### ISSUE THREAD

**Issue by furbzy** [Darkosto/SkyFactory4Issues#552]
## Bug Report

when i gut the seeds in any water source they dont grow i let it sit for 30 min like the wiki said for growing them with out the crystal growth acceptors. you need pure nether quartz crystal to make the calculation processor  

## Expected Behaviour
just not growing
## Possible Solution
 no idea
## Steps to Reproduce (for bugs)

1. put seed in water 
2. put 4 crystal growth accelerator around the 1x1 water source
3. put power to the accelerators with energy acceptor 

## World Information

* Preset: village 

* Prestige: no

* Modpack Version world created in: 4.0.2

* Additional Content Installed: no

## Client Information

* Modpack Version: 4.0.2
* Java Version: no idea
* Launcher Used: twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: single 
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: no idea 
* Operating System: 8.1 embedded 
* Hoster/Hosting Solution: n/a
* Sponge (Non-Vanilla Forge) Server :n/a

**Comment by jk1895** [comment]
Without the accelerator it needs hours to see something. Craft fife accelerator and power them. Without them it's not recommended.

**Comment by justinrusso** [comment]
You can also just put them in a Mekanism Enricher and it will do it far faster than in world growing.
