### ISSUE TITLE
server crashed

### ISSUE THREAD

**Issue by JackMeds** [Darkosto/SkyFactory4Issues#554]
## Bug Report
boom! world crashed

## Expected Behaviour
Archive cannot be opened

## Logs
* Client/Server Log:  https://paste.ubuntu.com/p/4tjwsfWjJN/
* Crash Log:  https://paste.ubuntu.com/p/h9ybXr82Ry/

## World Information
 Material Girl in a Material World:
generator-settings={"Topography-Preset":"Material Girl in a Material World"}
level-type=DEFAULT
* Modpack Version world created in:
4.0.2
* Additional Content Installed:
ftb mods

## Server Information
* Java Version:201
* Operating System:win 2019
* Hoster/Hosting Solution:Private Server
* Sponge (Non-Vanilla Forge) Server:no sponge it's 1.12.2 spigot forge server

**Comment by justinrusso** [comment]
This crash involves a mod that does not come with the pack.
