### ISSUE TITLE
Steel Blocks don't craft to thermal expansion steel bars

### ISSUE THREAD

**Issue by Mementh** [Darkosto/SkyFactory4Issues#556]
## Bug Report

Steel bars are currently crafting to item.tcomplement.materials.name which has the black and pink checkerboard texture 
This happens to bars to nuggests as well

## Expected Behaviour

It should make standard TC ingots.

## Possible Solution

unknown, NoMoreRecipeConflict-0.13(1.12.2) allows me to get around it

## Steps to Reproduce (for bugs)

1. make a steel block
2. uncraft it

## Logs

* Client/Server Log:
* Crash Log:
https://pastebin.com/nYXbwdLW ( if you need more you need to tell me where to upload a 11 meg file :/ )

## World Information

* Preset: village

* Prestige:  yes
 latest
* Modpack Version world created in: latest 

* Additional Content Installed: 
mekores-2.0.3
JustEnoughResources-1.12.2-0.8.5.27
JustEnoughEnergistics-1.12.2-1.0.6
NoMoreRecipeConflict-0.13(1.12.2)
LunatriusCore-1.12.2-1.2.0.42-universal
InventoryTweaks-1.63
NoFov-MC1.12-1.0.1

## Client Information

* Modpack Version: latest 
* Java Version:1.8.0.21 
arguments:-server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts
* Launcher Used: twitch/jar?
* Memory Allocated: 8602
* Server/LAN/Single Player: single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sk2048** [comment]
Latest isn't a version number, please confirm you are using 4.0.2 - this should have been fixed in that version.

**Comment by Mementh** [comment]
was using older version and said latest because there was no update prompt ? versions in twitch showed newer
