### ISSUE TITLE
Where are the libraries SF4 4.0.2

### ISSUE THREAD

**Issue by narrowascent** [Darkosto/SkyFactory4Issues#567]
The SF 4.0.2 Update.txt file says to: "6) Upload the entire libraries folder to the server also. As changes could of been made and you'll need them otherwise you'll have bad times."    This is the first time I update my server and no clue where these libraries are.  There is no folder that says that in the update files nor in the ones installed on my server already.  This is probably a super noob question but does anyone know what I need to do?

**Comment by sk2048** [comment]
Just a hint, did you run the installer jar before uploading? It should have created the folder.

If you get stuck again, checkout the discord for support https://discord.gg/darkosto

The issue tracker is for bugs, and you'll get faster support there :)
