### ISSUE TITLE
Can't do Deep Mob Learning trials in CompactSky world

### ISSUE THREAD

**Issue by winauer** [Darkosto/SkyFactory4Issues#570]
## Bug Report
The Trial Keystone from Deep Mob Learning says that it needs a 15x15x10 area but the max. compact machine is only 13x13.

## Expected Behaviour
Have a place where the Trials can be done

## Possible Solution
Add a place that is big enough

## Steps to Reproduce (for bugs)
* Place Trial Keystone.
* right click
* read text complaining about the area

## Logs
N/A

## World Information
* Preset: CompactSky

* Prestige: Yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed: No

## Client Information
* Modpack Version: 4.0.2
* Java Version: 1.8.0_202
* Launcher Used: MultiMC
* Memory Allocated: 7GB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Durandle** [comment]
i have not made a compact sky world but i do believe you can go to other dimensions from inside the compact machine

**Comment by winauer** [comment]
All other dimensions are just boxes that look like the insides of compact machines in different colors, surrounded by bedrock. None of those are bigger than 13x13 (unless I missed one).

**Comment by MaxBellc** [comment]
I'm having the same issue.

**Comment by tjd46** [comment]
have you tried the twilight forest cube im pretty sure its big enough at 19x19

**Comment by b3thanie** [comment]
> have you tried the twilight forest cube im pretty sure its big enough at 19x19

This is the solution, thank you !

**Comment by Darkosto** [comment]
To help further with this, I've increased the sizes of the Lost Cities and Hunting Dimension Compact Machine sizes. If you have already generated these dimensions in your world you would need to delete and regenerate to get the bigger size or use the Twilight dimension that was already 19x19x19. This fix went out with 4.0.5.
