### ISSUE TITLE
Block Duplication

### ISSUE THREAD

**Issue by JustThisPC** [Darkosto/SkyFactory4Issues#571]
## Bug Report

As of currently: One the Safe Island [base surrounded by concrete], when placing blocks and breaking them with a wooden tool[this is as far as I have progressed atm], the block stays in my inventory and I can continue to place an unlimited amount of that block, and break them to obtain more. I have recreated this four times after finding it now. 
Once with:
1. The concrete surrounding my island
2. The Crushing Tub
3. Normal chests
4. Bonsai pots

As far as I know, this isn't happening in Singleplayer. Only on servers.  After relogging multiple times, the duplicated items stay.

## Expected Behaviour

Instead of placing down the block and taking it from my inventory, it duplicates what I am placing and continues to let me place as though I were in creative.

## Steps to Reproduce (for bugs)

1. Break intended block with a wooden axe or pickaxe
2. Place and Duplicate

P.S. After a server restart, the bug seems to have disappeared, but I still have my duplicated items. If I can do it again I will try and post a video of it. **The server restart was not for my bug, but for a different issue.**

## Logs

* Client/Server Log:
* Crash Log: This does not cause crashing

## World Information

* Preset: Safe Island[concrete surrounded]

* Prestige: I'm not sure

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version: 1.12.2
* Launcher Used: AT
* Memory Allocated: unknown
* Server/LAN/Single Player: SERVER
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Yorkforce** [comment]
This was an issue caused by low TPS, its a server problem not a modpack issue. (occured on our server)

This can be closed.
