### ISSUE TITLE
RF Tools powercell crash

### ISSUE THREAD

**Issue by ThatGuy-peek** [Darkosto/SkyFactory4Issues#579]
## Bug Report

When two RF tools power cells are stacked, and you shift pickup the top block then place it back. and then take the info screen and placing it on the top power cell after shift picking it up crashes the game.
## Expected Behaviour

my game doesn't crash
## Possible Solution

Don't shift click the info screen onto power cells that are stacked that was previously shift clicked on.
## Steps to Reproduce (for bugs)

1. use 2 RF tools low power cell on top of each other
2. use RF tools information screen
3. shift right click the top power cell and replace it
4. shift right click the info screen and replace it on the top power cell
5. game and or server should crash

## Logs

* Client/Server Log: https://pastebin.com/5QwipgNg
* Crash Log: https://pastebin.com/v5DUBgFB (for server)

## World Information

* Preset: Default (regular skyfactory)

* Prestige:  No

* Modpack Version world created in: 4.0.1

* Additional Content Installed: N/A

## Client Information

* Modpack Version: 4.0.2
* Java Version: 1.8.0_201-b09
* Launcher Used: Twitch/curse
* Memory Allocated: 9216 MB
* Server/LAN/Single Player: server but applicable in both
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: build 1.8.0_201-b09
* Operating System: Windows 10
* Hoster/Hosting Solution: on pc

**Comment by DelfCo** [comment]
I had the same issue, except that I picked up and replaced the bottom cell of a stack of two rather than the top, and I had the face of the cell set to output when I placed the screen, which OP doesn't mention.

Here's my crash log: https://pastebin.com/LMC6fYUT
