### ISSUE TITLE
[Bugs/FR] SF4 tracking document for Dedlou.

### ISSUE THREAD

**Issue by Demlou6** [Darkosto/SkyFactory4Issues#58]
Instead of creating a bunch of tracked issues in the later version I'll start using this document, feel free to comment:

https://docs.google.com/document/d/1jqZJ2wttDphHgj03NrUbru9NtnwuR6XT1BNSflIna5c/edit?usp=sharing

**Comment by Darkosto** [comment]
This document is empty so I assume we're good on the suggestions, fixes, etc?

**Comment by Demlou6** [comment]
Yep, closing for now, if I have something I will send directly.
