### ISSUE TITLE
pres

### ISSUE THREAD

**Issue by aliyar15** [Darkosto/SkyFactory4Issues#581]
## Bug Report
used the prestige point and unlocked the zen garden, and got another point but i had to use it again to unlock the zen garden. how can i give myself 1 point to use it for something else

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
`/prestige add @p 1`

Use the discord for support in future https://discord.gg/darkosto
