### ISSUE TITLE
Can't Start Server

### ISSUE THREAD

**Issue by Adammild1** [Darkosto/SkyFactory4Issues#586]
## Bug Report

When I try to start a server through the StartServer.bat, I get an error that pops up for a fraction of a second and then the command prompt stops. I am able to start the server through the forge file but it is using a small amount of ram so it just stops (paste for the logs with the forge 
https://pastebin.com/JYJcNfKn) [Screenshot (29)](https://user-images.githubusercontent.com/37020680/56543364-44047a80-653f-11e9-92d8-55433862362f.png) I am not able to get the ServerStart.bat file to work so I cannot get logs for that file.

## How to reproduce.

1. Open install.bat
2. Open forge universal for eula and set to true. (I even tried creating an eula in a fresh server without using the forge file)
2. Open ServerStart.bat and it closes. If I use the forge file, it bottlenecks itself around 300MB of ram.

* Preset: skyfactory 4
* Prestige: no
* Modpack Version world created in: SkyFactory 4 - 4.0.2 -- Server
* Additional Content Installed: Nope

## Server Information

* Java Version: Java 8 update 201 build 1.8.0_201-b09
* Operating System: Windows 10
* Hoster/Hosting Solution: My computer?
* Sponge (Non-Vanilla Forge) Server: No

My client version for the 4.0.2 is working completely fine.
Thanks!

**Comment by aikidokanu10** [comment]
Same :(

**Comment by sk2048** [comment]
Support at https://discord.gg/darkosto

**Comment by willm132** [comment]
I have this issue too. Any fix yet?

**Comment by Adammild1** [comment]
Get the newest server file. Run the setup twice and change the eula and
that worked for me. I dont know if that is how you are supposed to do it
though. I would have replied with the answer a while ago but the thread was
already closed by someone.
