### ISSUE TITLE
Bonsai Trees texture messed up

### ISSUE THREAD

**Issue by dutok** [Darkosto/SkyFactory4Issues#587]
## Bug Report
Whenever I turn my Mipmap levels on using Optifine or use a texture pack, the sky orchard bonsai trees texture gets messed up and blocky.
* Imgur album of screenshots: https://imgur.com/a/LxkrIsR

## Expected Behaviour
I expected them to look normal, I guess. I'm trying to get rid of these flickering vertical lines on blocks far away by turning up my mipmap levels but I discovered the trees look really messed up. 

## Possible Solution
No clue.

## Steps to Reproduce (for bugs)
1. Turn Mipmap Levels in Optifine to 1 through 4 AND/OR enable a texture pack.
2. Return to the game.
3. Place a sky orchard tree in a Bonsai Pot.

## Logs
https://gist.github.com/dutok/5c36306cebb257cff35f414415a51067

## World Information

* Preset: Skyfactory 4 Tutorial

* Prestige: No

* Modpack Version world created in: 4.0.2
* Additional Content Installed: OptiFine 1.12.2 HD U E3   &  SEUS-Renewed 1.0.0

## Client Information

* Modpack Version: 4.0.2
* Java Version: Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
* Launcher Used: Twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Yes
* Shaders Enabled: SEUS-Renewed 1.0.0
* I'm also playing at 1440p if that makes a difference.

**Comment by sk2048** [comment]
Have you tried reloading the pack from the desktop after changing these settings?

**Comment by dutok** [comment]
> Have you tried reloading the pack from the desktop after changing these settings?

I feel dumb. I did what you said and it's all fixed. Sorry ya'll!
