### ISSUE TITLE
Applied Energstics Cant take out 64 items

### ISSUE THREAD

**Issue by Coaleb2** [Darkosto/SkyFactory4Issues#589]
After adding multiple import bus, export bus, and me interfaces the ae system wont allow removing or adding a stack of items. It will turn the system off and come right back. If you remove the multiple busses the system will allow adding 64 items or removing of them.

**Comment by sk2048** [comment]
The network does not have sufficient energy. Each device on the network adds a small amount of energy usage per tick. Every operation each of these devices perform also consumes energy.

Actions performed by the player, such as adding and removing items, also consumes energy.

If the network does not have sufficient energy stored for all the operations it is asked to do inside a tick then it will do as much as it can then shut down until it receives more energy.

Add the ME Energy storage blocks anywhere on your network to increase its buffer. Dense will store more energy than the standard energy cells.
