### ISSUE TITLE
Chest Builder doesn't work [CLONE]

### ISSUE THREAD

**Issue by omriherz** [Darkosto/SkyFactory4Issues#593]
## Bug Report

When you put the items neccesary for the chest in the chest builder and press 'build', nothing happens and the items get sort of glitched out sometimes.

## Expected Behaviour

it doesnt make a chest as expected.

## Possible Solution

update the mod, it works

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Sky factory 4

* Prestige: enabled
 
* Modpack Version world created in: 4.0.2

* Additional Content Installed: nope

## Client Information

* Modpack Version: 4.0.2
* Java Version: no idea
* Launcher Used: no idea
* Memory Allocated: no idea
* Server/LAN/Single Player: Server through hamachi
* Optifine Installed: no idea
* Shaders Enabled: nope

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by selbeyhan** [comment]
I have this glitch to
