### ISSUE TITLE
A prestige bug

### ISSUE THREAD

**Issue by Hexonex** [Darkosto/SkyFactory4Issues#594]
Hi,
There is eighter bug, or im doing something wrong

I choose prestige enabled for my world, and then after a few hours turned cheats on, and added points to unlock everything

I unlocked everything, but projectE and this dark matter one. I cant unlock them and they seems like "unavailable" 
I tried to create a new save and then there unlock this, but it's still "unavialable"
There is a picture of how does this look like.
![Base Profile Screenshot 2019 04 23 - 12 30 36 33](https://user-images.githubusercontent.com/49904897/56574494-a7d08700-65c3-11e9-9213-5a1d24cddf1b.png)
![Base Profile Screenshot 2019 04 23 - 12 30 41 13](https://user-images.githubusercontent.com/49904897/56574496-a8691d80-65c3-11e9-96ff-9b5c4fd28807.png)

**Comment by Streamcyper** [comment]
I do believe it says "Coming soon" on those because there is a bug that they are awaiting a fix for and has therefor been disabled for now until it gets fixed.

**Comment by Hexonex** [comment]
OMG. didn't notice a "comming soon!" :D 

Sorry, my faulth
