### ISSUE TITLE
Remove lava from Metal Barrel

### ISSUE THREAD

**Issue by ashcraven** [Darkosto/SkyFactory4Issues#595]
## Bug Report
Cannot extract lava from a a full Metal Barrel from Barrel's, Drums, Storage & More. Remove a bucket via Fluid Extraction Cable into some other container and can then bucket out lava from Metal Barrel.

## Expected Behaviour
Expecting to be able to bucket out lava from Metal Barrel if Metal Barrel is full.

## Steps to Reproduce (for bugs)

1. setup dropper with redstone clock to  drop cobblestone into cauldron
2. fluid extraction cable pulls lava into barrel until full
3. attempt to left click bucket of lava from barrel and it fails
4. add fluid extraction cable from barrel to tank and can then bucket out of barrel

## Logs
* Client/Server Log: Client Log
https://pastebin.com/LG2vZxKx

* Crash Log: No logs seeing logs for this error or crashes in regards to this bug

## World Information

* Preset: Village

* Prestige: No

* Modpack Version world created in: 4.0.1

* Additional Content Installed: No extra mods installed

## Client Information

* Modpack Version: currently 4.0.2
* Java Version: 1.8.0_211-b12
* Launcher Used: Twitch
* Memory Allocated: 8 gig
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Unknown
* Operating System: Unknown
* Hoster/Hosting Solution: CreeperHost
* Sponge (Non-Vanilla Forge) Server: Unknown

**Comment by sk2048** [comment]
See here Funwayguy/BarrelsDrumsStorageAndMore#10

Will be fixed in the next version, the test pack already has the updated mod in it so I'm closing this issue.
