### ISSUE TITLE
Prismarine

### ISSUE THREAD

**Issue by XperioR** [Darkosto/SkyFactory4Issues#596]
I'm playing classic SF4 (started with tree; not using Project E) and I don't know how I can get prismarine shards/crystals... There isn't any dimension with guardian temple or prismarine-related blocks, or I just can create them... but how?

**Comment by Wulwsten** [comment]
Use the mod Deep Mob Learning to get the matter, with which you can craft Shard, And the mod NuclearCraft or Integrated Dynamics to get Crystals. And yes, all this is visible in JEI.

**Comment by darkphan** [comment]
You can craft a Guardian Lily.

**Comment by Darkosto** [comment]
This information is found in JEI. It is obtainable.
