### ISSUE TITLE
Building gadget does not build with seared blocks

### ISSUE THREAD

**Issue by ozzeusz** [Darkosto/SkyFactory4Issues#604]
## Bug Report
Building gadget does not build with seared blocks. When shift clicking seared bricks or seared slabs it says: "Invalid Block".

## Expected Behaviour
It should switch building block in building gadget.

## Possible Solution
Add seared blocks to building gadget block list

## Steps to Reproduce (for bugs)
Shift right click on seared blocks

**Comment by sk2048** [comment]
All smeltery components are tile entities, the building gadget is hard coded not to accept these as valid blocks. There is nothing we can do about this.
