### ISSUE TITLE
Stone Factory - End Dimension

### ISSUE THREAD

**Issue by aomtte** [Darkosto/SkyFactory4Issues#606]
## Bug Report
Completion of "Where's the Boss" seems not working, assuming it's because of the world type (End world full of end stone)
Additionnal question : Is it possible to find Elytra in this world type ? If not, the "It Gives You Wings" isn't completable too.

## Expected Behaviour
Complete the requirement when entering the dimension

## World Information

* Preset: Stone Factory

* Prestige: Yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed: Updated CompatchedStorage manually

## Client Information

* Modpack Version: 4.0.2
* Java Version: 1.8.0_51 64Bit
* Launcher Used: Twitch
* Memory Allocated: 12Go
* Server/LAN/Single Player: Single

**Comment by ClaymooreEOC** [comment]
Same issue with preset: Chunk Norris, also prestige on.

**Comment by b3thanie** [comment]
Same Issue on CompactSky, Prestige on.

**Comment by chippydip** [comment]
I assume this was also the reason I didn't get an Overworld Cake when entering the end (got one for every other dimension).

**Comment by fsbn1** [comment]
Same issue here... prestige is off

**Comment by sk2048** [comment]
@fsbn1 You need to provide more information. This issue was fixed in 4.0.4, are you running an earlier version? If you are, then of course you're having the same issue. If not, then you need to open a new report describing your circumstances.

**Comment by fsbn1** [comment]
im running an 4.0.4 at the moment but world was made in 4.0.2
i did delete the dim1 but it didnt help
