### ISSUE TITLE
4.0.2: platinum recipe not working for mechanism metallurgic infuser

### ISSUE THREAD

**Issue by kyoujin** [Darkosto/SkyFactory4Issues#609]
In SkyFactory 4.0.2, attempting to use both the factory version as well as the low tier metallurgic infuser to produce platinum will not accept Silver Amber to infuse with diamond.

For both tests I used compressed diamond.  Neither silver dust nor ingots work either.

**Comment by MacAttack-UK** [comment]
It does work but what is not clear is that it needs 16x Diamond to 1x Silver Amber.

Hope this helps

**Comment by kyoujin** [comment]
Aha!  That makes sense and works.  Closed.
