### ISSUE TITLE
[4.0.2] Pack crashes during the loading

### ISSUE THREAD

**Issue by TonyMestre** [Darkosto/SkyFactory4Issues#611]
## Bug Report
The game crashes during the initial load.

## Expected Behaviour
It should load an open the initial menu

## Steps to Reproduce (for bugs)

1.Open the pack
2.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/kTeUrs59

## World Information

* Preset:Default

* Prestige: Yes

* Modpack Version world created in:4.0.1

* Additional Content Installed:No

## Client Information

* Modpack Version:4.0.2
* Java Version:1.8.0.51(64 bit)
* Launcher Used:Twitch launcher
* Memory Allocated:6400 MB
* Server/LAN/Single Player:Single player
* Optifine Installed:No
* Shaders Enabled:No

**Comment by Knoxxar** [comment]
Update your Java plz, should fix this problem.

**Comment by TonyMestre** [comment]
I updated java but the crash still happens

**Comment by Knoxxar** [comment]
it looks like that java use your cpu grafic not your dedicated, plz check this. If you use an dedicated graficcard you can disable the cpu grafic in the bios. How this works, can you read in the mainboard manual or search via google for your board.

**Comment by TonyMestre** [comment]
but the GPU isn't dedicated(intel hd graphics 520)

**Comment by Crackerhead22** [comment]
In the Twirptch Minecraft settings, tell it to use the latest Java version, might need to change the launcher type.

**Comment by TonyMestre** [comment]
Updated java to 1.8.0.211(64 bit) and changed launcher type to JAR launcher, the crash still happens

**Comment by TonyMestre** [comment]
I've updated the pack to 4.0.3 and now it is fixed
