### ISSUE TITLE
Lapis Sapling recipe does not return glass bottle

### ISSUE THREAD

**Issue by scollenburg** [Darkosto/SkyFactory4Issues#617]
## Bug Report
The resin recipe for Lapis Sapling uses a Water Bottle. Currently this recipe consumes the water bottle. Most recipes using a water bottle return the empty bottle as a by-product.

*P.S. - The Redstone Sapling recipe **does** return the bottle*

## Expected Behaviour
Return an empty glass bottle.

## Possible Solution
Update the [CRT] recipe.

## Steps to Reproduce (for bugs)
1. Craft Lapis Sapling using resin(s)

## Logs
No crash, so no log.

## World Information
As Seen In (tm): Chunk Norris & classic (1 dirt tree on dirt block)

## Client Information
SF4 4.0.1

**Comment by sk2048** [comment]
Closed in Darkosto/SkyFactory4@ffe76eb
