### ISSUE TITLE
Mekanism crusher jei issue.

### ISSUE THREAD

**Issue by misshaptat** [Darkosto/SkyFactory4Issues#629]
## Context
so jei says you can make sand in the crusher from gravel, this isn't possible for 4.0.2!

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
