### ISSUE TITLE
Mod request Extra glass for it's extra glass of course!

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#63]
I can't seem to find glass that blocks light, and I figured maybe a mod for just glass might be able to help us out.
https://minecraft.curseforge.com/projects/extra-glass

**Comment by darkhax** [comment]
We actually already have a "dark glass" in the pack. If you use a sneaky block and click on it with glass it will maintain it's normal properties but look like glass. This isn't the best pic of it, but this is what it looks like on my mob farm in the pack. 

![image](https://user-images.githubusercontent.com/2250798/50741296-85536300-11b8-11e9-816b-5f6c617bf9e3.png)

**Comment by JackRuby1** [comment]
That is an option yes, didn't realize that was one. Cyclic added in a light blocking glass in the latest update, so this feature request is irrelevant.
