### ISSUE TITLE
pigs not working

### ISSUE THREAD

**Issue by thasmallwar** [Darkosto/SkyFactory4Issues#630]
after putting a cobblestone pig on dirt it pooped out those egg things, I would say what they're called but I can't load into the game. I broke it and my game crashed.

**Comment by sk2048** [comment]
Probably related to Darkhax-Minecraft/Resource-Hogs#10 but you've given so little information I can't be sure. If you think this is something else, open a new issue and provide at least a crash report, preferably everything we ask for.
