### ISSUE TITLE
AE2 items missing from modpack?

### ISSUE THREAD

**Issue by DownloadingRam** [Darkosto/SkyFactory4Issues#634]
I am trying to set up auto-crafting using the ME system and compact machines. 
Correct me if I am just not seeing any other way of doing any of these tasks,
but why aren't these items included with the pack:
-Wireless ME crafting terminal (the one with a crafting table, not the normal wireless terminal)
-ME capability adapter (for connecting ME-related stuff through compact machines)
-Dense ME conduit (don't know if this one has any use but thought it might be helpful

It seems like a lot of items are missing from the AE2 mod and it's making it difficult for me to set up auto-crafting. With the mod being new and all, tutorials are hard to come by so I'm gonna leave this here and hope for the best.

**Comment by sk2048** [comment]
None of these items are part of AE2, they are all addons. You are welcome to submit feature requests for any of the relevant mods, though I know that both Wireless Crafting Terminal and EnderIO have previously been considered and will not be included.

With respect to accessing an ME system from with a compact machine, you can use a storage bus/interface combo to get access to the contents. To properly connect the network for autocrafting purposes you need to use a quantum bridge.

Are you aware that AE2 channels are disabled in this pack?
