### ISSUE TITLE
Wierding Gadget Tooltip

### ISSUE THREAD

**Issue by kugamer** [Darkosto/SkyFactory4Issues#635]
## Context
I would like a tooltip for the wierding gadget to tell you how many chunks it loads. Something like "Loads current chunk gadget is in"  or "Loads all adjacent chunks and current chunk the gadget is placed in".

**Comment by sk2048** [comment]
It's a 5x5 chunk area centred on the chunk the gadget is in, putting that in the tooltip though isn't a bad idea.
