### ISSUE TITLE
Magma Slime Dirt Prestige not unlocking Gamestage.

### ISSUE THREAD

**Issue by LezChap** [Darkosto/SkyFactory4Issues#647]
## Bug Report
Buying the Magma Slime Dirt Prestige doesn't unlock the oragne_slime_dirt gamestage, allowing access to the Magma Slime Dirt block/recipe.

## Expected Behaviour
Spending the prestige points gives access to the gamestage and relevant recipe.

## Possible Solution
Probably a typo somewhere in the configs/scripts that needs to be fixed.

## Steps to Reproduce (for bugs)
1. Purchase the Magma Slime Dirt.
2. Nothing happens.

Version 4.0.2 of the pack.

**Comment by sk2048** [comment]
Resolved in Darkosto/SkyFactory4@5f524f5
