### ISSUE TITLE
Missing Tinker's Smeltery Controller

### ISSUE THREAD

**Issue by Oxcidius** [Darkosto/SkyFactory4Issues#648]
Just started this pack up using 4.0.2 and am now at the stage where I want to make a seared smeltery. Found every other recipe for the smeltery except the controller! Has this been removed?
Do we have to stick to the melters only now?

**Comment by sk2048** [comment]
You're playing with prestige?

**Comment by Oxcidius** [comment]
Yes! Well that explains it! Seems I'm jumping the gun! Didn't expect the controller to be behind the prestige stages! Thanks for pointing out my failures! lol
