### ISSUE TITLE
Spawntacular advancement

### ISSUE THREAD

**Issue by martinschuberteu** [Darkosto/SkyFactory4Issues#649]
## Bug Report
Spawntacular advancement not completing after upgrading a spawner to 0 delay.

![2019-04-25_13 42 34](https://user-images.githubusercontent.com/19508559/56733631-097a2800-6761-11e9-909b-6b90393ba4c5.png)

![2019-04-25_13 42 45](https://user-images.githubusercontent.com/19508559/56733640-0f700900-6761-11e9-99d0-c346ca0aa2b5.png)

## Expected Behaviour
Spawntacular advancement should complete

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
Upgrade spawner to 0 delay.

## Logs
N/A

## World Information
* Preset: Sky Factory 4
* Prestige: Yes
* Modpack Version world created in: 4.0.2

## Client Information
* Modpack Version: 4.0.2
* Java Version:
* Launcher Used: Twitch/Native
* Memory Allocated: 10752
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment]
If you place it in the world and right click it does the advancement trigger?

**Comment by martinschuberteu** [comment]
> If you place it in the world and right click it does the advancement trigger?

Unfortunately not. I've tried picking it up and placing it again and it didn't trigger. I just noticed I have the same problem with the two Blackhole quests. I've had issues with advancements before, which could be resolved by restarting minecraft, but it doesn't work for these advancements.

**Comment by martinschuberteu** [comment]
Ah well, not it worked with right clicking the spawner... guess I'll restart a few more times to see if that also solves the Blackhole issue
