### ISSUE TITLE
I cant use optifine on the new update 

### ISSUE THREAD

**Issue by Lloyyd** [Darkosto/SkyFactory4Issues#654]
I cant use optifine in the new update , yet I could before without any problems heres the latest log 
[latest.log](https://github.com/Darkosto/SkyFactory4Issues/files/3117838/latest.log)

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
