### ISSUE TITLE
Moving rustic cabinets with CarryOn not working as expected

### ISSUE THREAD

**Issue by AlexejheroYTB** [Darkosto/SkyFactory4Issues#657]
## Bug Report
Moving rustic cabinets is very strange and doesn't always work as expected

- **Moving the top half of the cabinet to another location**
  - _The top half retains its `top: true` attribute and turns into an invisible block (unexpected)_
  - The bottom half loses its `bottom: true` attribute
- **Moving the invisible top half of the cabinet back to its original location**
  - The bottom half gains its `bottom: true` attribute back and the cabinet becomes a multiblock again
- **Moving the bottom half of the cabinet to another location**
  - The bottom half loses its `bottom: true` attribute
  - The top half loses its `top: true` attribute
- **Moving the bottom half of the cabinet back to its original location**
  - _The attributes are not changed and the two halves are not merged (unexpected)_
- **Moving the top half of the cabinet to the same location but rotated**
  - _The cabinet becomes a multiblock, but it can be opened only from the direction that each half is facing (unexpected)_

Here is a video showcasing all of these issues: https://youtu.be/AeH9_nI4oAA

## Client Information
* Modpack Version: 4.0.2
* Server/LAN/Single Player: singleplayer

**Comment by AlexejheroYTB** [comment]
Why did you add this in `Category: Config` and not in `Category: Mod`?

**Comment by sk2048** [comment]
Because if a tile entity does not expect to be moved and behaves weirdly if it is moved it should be blacklisted from being picked up using CarryOn, a config change.

**Comment by AlexejheroYTB** [comment]
I was guessing that was the case. Cabinets are very useful, especially in the early game. Not being able to move them would be a huge disadvantage. The cabinet states could be modified when a part of the multiblock is picked up, or Rustic could check for its own blocks to see if they are still there. Blacklisting the block in the config would not necessarily be the best option.

**Comment by sk2048** [comment]
This isn't as simple as you think it is, carry on just copies the block from one place to another. It implements no special handling for particular mods blocks (except a blacklist), and so far as I can tell gives the mod who's block is moved no dedicated way to respond to being moved. Maybe it gets a block update, but I would have to do some testing to find out.

The only way we can fix this as pack developers is to blacklist the blocks. You may contact the developer of Rustic and see if there is a way for them to handle this better, but until such a time as that is implemented all we can do is blacklist cabinets.

**Comment by AlexejheroYTB** [comment]
Could the item be manually unblacklisted on the client side? (Like the ore excavation tool blacklist)

**Comment by Darkosto** [comment]
Blacklisted the cabinets in dev. Will be out for 4.0.6
