### ISSUE TITLE
Game crashes on right clicking compact machine

### ISSUE THREAD

**Issue by IsaacWorkman** [Darkosto/SkyFactory4Issues#664]
## Bug Report
I can usually go back and forth between compact machiens a few times, but i think right clicking them too rapidly causes crashing. This is a problem for Compact Sky-type maps.

## Steps to Reproduce (for bugs)
Right click a compact machine to open its GUI. May need to right click a few different compact machines rapid-fire.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/ETZTtCN2

## World Information

* Preset: Compact Sky

* Prestige: Yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.3
* Java Version: 1.8
* Launcher Used: Twitch
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by MaxBellc** [comment]
Exact same issue, here's my crash report https://pastebin.com/SFM6Pgnb

**Comment by sk2048** [comment]
More accurately described by #675
