### ISSUE TITLE
flux network not let me hold any items from the mode or place

### ISSUE THREAD

**Issue by nicnacftw** [Darkosto/SkyFactory4Issues#674]
## Bug Report
flux network not letting me hold any items from the mod in my inventory it keeps throwing them on the floor -->

## Expected Behaviour
can not hold any items from flux network in my hand it throws it straight onto the floor
## Steps to Reproduce (for bugs)

1.https://prnt.sc/ngzzzr
2.http://prntscr.com/nh0063

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: no its on  a server

* Modpack Version world created in:4.0.3

* Additional Content Installed:

## Client Information

* Modpack Version:4.0.3
* Java Version:latest
* Launcher Used:twitch
* Memory Allocated:8
* Server/LAN/Single Player:
* Optifine Installed:yes
* Shaders Enabled:no

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by justinrusso** [comment]
`Prestige: no its on a server`

Servers could have prestige... is prestige enabled on the server or not?

**Comment by nicnacftw** [comment]
The server doesn’t have prestige on it ,I had flux network working before the update of the server I have flux plugs an point placed in my island just went to craft another item from flux an it was throwing on the floor saying unfamiliar item

**Comment by Yorkforce** [comment]
Just to confirm server config its occuring on:
B:"Prestige Enabled Default"=false

**Comment by justinrusso** [comment]
run `/gamestage info` and provide the output
