### ISSUE TITLE
Please add the mod: Refined Storage :)

### ISSUE THREAD

**Issue by RemiReins** [Darkosto/SkyFactory4Issues#678]
The addition of this storage mod will provide to an alternative storage system using power than the AE ME. It provides a lot of similar features. And works fine on servers [1.12.2]

 It's just amazing. Similar to AE ME. Blessing from heaven. And if AE ME is already added to the pack, the refined storage mod certainly aligns with the flow of the modpack. 

The main problem with AE ME is that due to its type limit of 63 types per drive, the me can easily be filled (even a 64k). For example, if I add 4 stacks of cobble to one drive and add another drive later, the next cobble I put in have a chance of occupying a type space in the 2nd drive. AKA instead of storing similar items under one type (which is the whole point of types) the ME wastes space filling up the drive. No new items can be added if the types are all filled even if storage space is leftover. And in order to fix this issue, you must check each drive one by one in order to find and sort similar items together so that they won't take up an extra type space. It's an incredibly frustrating part of the storage system. Refined storage acts the exact same as ME but does not include any type limits so that you can use your drives efficiently and without any frustration. I hope this will interest some research into possibly adding this mod to the pack. Right now the modpack only supports one powered storage system. An alternative would be very welcome. 

Also when it comes to the mod's stability on servers, I worked with it on revelations 1.12.2 perfectly fine server side for the past weeks/months. No issues.

It's beautiful, it's amazing, it's refined.

Refined Storage is a mass storage mod for Minecraft 1.10.2, 1.11 and 1.12 that offers the player a network-based storage system, allowing them to store items and fluids on a massively expandable device network.
* Name: Refined Storage
* CurseForge Link: https://minecraft.curseforge.com/projects/refined-storage

**Comment by sk2048** [comment]
Refined Storage has been considered previously and will not be added.
