### ISSUE TITLE
The "Plant Sugarcane on Snad" advancement is looking for Dirt and Wheat

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#68]
To trigger the advancement, sugarcane needs to be placed instead of seeds. It was a bit misleading from the progression of getting sugarcane seeds that you need to plant the seeds, grow sugarcane, and replant the cane to trigger the advancement.

Also, there is an unusual display for the requirements that leads one to think that dirt and wheat are needed:
![2018-12-15_21 03 39](https://user-images.githubusercontent.com/29290246/50049200-084b3700-00ad-11e9-8c55-72fbefba02b3.png)

SkyFactory4-0.1.2
SF4 world

**Comment by Darkosto** [comment]
I worked on the text a bit to clear up confusion and used seeds instead of just sugarcane. Thanks!
