### ISSUE TITLE
Parabox Timer Too Long

### ISSUE THREAD

**Issue by njw4227** [Darkosto/SkyFactory4Issues#689]
## Context

Currently the prestige timer is set for 10min, but in real time this ends up taking about 25-30min to actually complete the cycle. I'm not sure if this was intended but if cycles were intended to be only 10min long real time, perhaps changing the cycle time to 5min could be a fix?

Sitting around for hours just to get a few prestige points in my opinion doesn't make for too fun of gameplay.

**Comment by blacksythe** [comment]
Unfortunately this is often down to server performance and has negatives on both side. using ticktime guarentee's maximum input during the "10 minutes". Using real time based on your own numbers, 2-3 times less energy will be put into the parabox.

**Comment by sk2048** [comment]
This is indeed down to your system's performance. If you are playing multiplayer then it's a server issue and you should look at migrating hosts, if not your client is struggling to keep up. In either case, you'll probably see lots of "Can't keep up, skipping x ticks" in one of the logs.

The parabox is configurable and if you aren't able to migrate you can change the timing to suit your needs:
https://github.com/Darkosto/SkyFactory4/blob/master/src/config/parabox.cfg#L16
