### ISSUE TITLE
Carry-on works with the Tinkers' Complement melter stuff, but not with the seared Tinkers' Construct variants?

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#69]
You can use Carry-on with the Tinkers' Complement porcelain stuff, and the seared versions of the melter and alloy tank, but these do not work with it:
Seared glass
Seared window
Seared gauge
Seared basin
Seared tank
Seared table

Even if you don't add all of them is there a possibility that the seared basin, tank, and table can be added to the whitelist?

**Comment by Darkosto** [comment]
Tcon should be good to go minus the controller blocks, thanks!
