### ISSUE TITLE
Filing Cabinet from Real Filing Cabinets interacts poorly with Crafting Station

### ISSUE THREAD

**Issue by Guggerbunk** [Darkosto/SkyFactory4Issues#695]
## Bug Report
Crafting Stations initially do not seem to see the contents of a Filing Cabinet from Real Filing Cabinets, but upon attempting to interact with a slot that you know has a folder with contents the items contained in the folders temporarily appear in the interface in the slots.  Additional bugs present when attempting to interact with the items.  Emptied folders are destroyed instead of preserved at 0 items and graphical issues present on the cabinet if it is open during interaction with the station.  Full details with pictures in the Steps to Reproduce section.

## Expected Behaviour
The expected behavior is that the Crafting Station shouldn't be able to see the Filing Cabinet's inventory at all, removing the ability to interact with it from its interface.

## Possible Solution
I'm not sure how things are coded, but somehow preventing the Crafting Station from seeing the Filing Cabinet's inventory would likely solve all of the presented bugs.

## Steps to Reproduce (for bugs)
1.  Set up a Crafting Station next to a Filing Cabinet that has folders with items.  
![2019-04-26_15 49 31](https://user-images.githubusercontent.com/20852252/56832843-06536a80-683b-11e9-934e-73a94e7de093.png)

2.  Initially it seems the Crafting Station cannot interact with the Filing Cabinet.  It sees the folder slots but nothing else superficially.  
![2019-04-26_15 50 55](https://user-images.githubusercontent.com/20852252/56832906-28e58380-683b-11e9-85e5-5342449ce336.png)

3.  Clicking a slot, however, causes you to pick up the contained item and shows the contents of other non-mob non-fluid folders in the interface.  
![2019-04-26_15 51 48](https://user-images.githubusercontent.com/20852252/56833015-5af6e580-683b-11e9-9da1-a57c4b15cc0c.png)

4.  Looking in the cabinet with a Magnifying Glass a stack of iron has been removed.  
![2019-04-26_15 53 36](https://user-images.githubusercontent.com/20852252/56833082-84177600-683b-11e9-8b57-2acf6abf7298.png)

5.  Right clicking the iron here attempts to remove half of what is in the cabinet instead of half of a stack.  
![2019-04-26_15 55 13](https://user-images.githubusercontent.com/20852252/56833192-cccf2f00-683b-11e9-8fd9-37b95ac6400a.png)

6.  Additional graphical bug presents on the filing cabinet when interacting with the station while the drawer of the cabinet is open.  The blocks appear in the cabinet instead of the folders if the drawer was open while removing items from the cabinet via the station.  This graphical bug disappears upon using a magnifying glass on the cabinet, closing it, or attempting to put items in it whether they can be filed or not.
![2019-04-26_15 57 17](https://user-images.githubusercontent.com/20852252/56833272-0869f900-683c-11e9-8a0f-aa186fe74b55.png)

7.  Shift+Left Clicking a slot with items in a folder empties the folder into the crafting grid.  The now-empty folder, instead of remaining with 0 items in it, is destroyed.  
![2019-04-26_16 00 33](https://user-images.githubusercontent.com/20852252/56833446-81695080-683c-11e9-87bc-bbb314066f3e.png)

8.  The Mob Folder (with 8 sheep) and the Fluid Folder (with 1 bucket of water) cannot be interacted with with the crafting station.

9.  (New world) Causing the crafting station to want to put crafting results into an adjacent inventory due to a full player's inventory does not transfer the item and instead destroys the folder.  Checked with Iron Ingot 1x Folder and trying to craft 1x Iron Ingot with Iron Nuggets and shift+left clicking the result.
![2019-04-26_16 18 36](https://user-images.githubusercontent.com/20852252/56834374-3c92e900-683f-11e9-97cb-e58ec2d12915.png)

## Logs
* Client/Server Log: Unable to provide due to exceeding Pastebin size limit.
* Crash Log: Not applicable

## World Information
* Preset: topography, SkyFactory 4
* Prestige: No
* Modpack Version world created in: first noticed in 4.0.2, reproduced in 4.0.3
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.0.3
* Java Version: Uncertain
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Don't know what that is so probably not
* Shaders Enabled: None

**Comment by JackRuby1** [comment]
Yeah darko disabled this during stream on Friday.
