### ISSUE TITLE
Using an ME IO Port shuts down ME system

### ISSUE THREAD

**Issue by Vertalli** [Darkosto/SkyFactory4Issues#696]
## Bug Report

 When I place a ME storage cell in the io port, the ME system turns off and none of the items move from the storage cell into other storage cells in my me drive. Also, oddly if I put a cell in the port that has a low amount of items like a 64k drive with 5k bytes and 3 items used it works fine and nothing shuts down. If I place a 4k drive thats totally full in the port, the system shuts off and the port doesn't work. I updated to 4.0.3, but this bug was also happening in 4.0.2.
## Expected Behaviour

My whole ME system shouldn't shut down and I should be able to move items from cells by using the IO Port.

## Steps to Reproduce (for bugs)

1. Place an ME cell that has items in the left side of the io port. (it seems to only fail on cells with a lot of items in)
2. Watch the ME system shut down
3. Profit

## World Information

* Preset: standard skyfactory

* Prestige: no

* Modpack Version world created in: created in 4.0.1 I think

**Comment by Vertalli** [comment]
Update: this problem is solved if you have ae energy cells connected to your system. I only had an energy connector connected to a rftools powercell multiblock. You shouldn't need ae energy cells to run the system because in any other modpack using ae I never use energy cells and it runs just fine. So the bug should ideally still be fixed, but there's a way to get around it.

**Comment by justinrusso** [comment]
This is simply just a need for a higher buffer for the transfer rate of the IO Port. This is not a bug.
