### ISSUE TITLE
[Minor] Grass block cauldren recipe requires 4 leaf blocks but only shows one in JEI

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#7]
From JEI, it looks like this recipe should only require one leaf block. Not sure if this is a limitation in JEI.

**Comment by Darkosto** [comment]
This would be on @KnightMiner 's end to enhance if he wanted to.

**Comment by KnightMiner** [comment]
Should already do it, I do nothing different for it than beetroot stew which uses stacks. Could he something odd with oredictionary stack sizes though

**Comment by Darkosto** [comment]
![image](https://user-images.githubusercontent.com/10309699/46311908-6c636200-c578-11e8-9942-3f3f9c85bcac.png)
