### ISSUE TITLE
Can't make Obsidian with Clay water bucket in any cauldron

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#70]
Iron water buckets will make obsidian, but the clay one will not.

**Comment by Darkosto** [comment]
This is due to a limitation of the mod compat right now. It will not use up the water in the clay bucket and provides infinite obsidian. Maybe @KnightMiner could take a look?

**Comment by KnightMiner** [comment]
I would have to see the recipe you are using to do anything, I cannot find it from a quick look in the scripts.

Honestly, the clay bucket should not act any different than an iron one as long as its using a proper NBT check. I'd need more information about what you are trying

**Comment by KnightMiner** [comment]
I don't recall any discussion, it shouldn't act any different as it's just another item with a container. I could see it having issues with NBT, can't recall if I ever made it handle that, but that would have e different symptoms than you described

**Comment by Darkosto** [comment]
Works in dev now.
