### ISSUE TITLE
Server crash whilst crafting Tough Alloy ingot in Nucleacraft Alloy Smelter

### ISSUE THREAD

**Issue by MacAttack-UK** [Darkosto/SkyFactory4Issues#709]
## Bug Report
Crafting Tough Alloy Ingot with Ferroborn Ingot and Lithium Dust in Nuclearcraft Alloy Smelter crashes server.

## Expected Behaviour
Should produce Tough Alloy Ingot

## Possible Solution
Unknown

## Logs
https://pastebin.com/rdtUeVCW

## World Information

* Preset: Skyfactory 4 default

* Prestige: No

* Modpack Version world created in: 4.0.1

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.3
* Java Version: 1.8.0_211-b12
* Launcher Used: MultiMC
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 1.8.0_181-b13
* Operating System: CentOS 7 64bit
* Hoster/Hosting Solution: Private Server
* Sponge (Non-Vanilla Forge) Server: No

**Comment by MacAttack-UK** [comment]
#688

**Comment by MacAttack-UK** [comment]
Just built a basic server to test localy with only Forge, Nuclearcraft & JEI from the 4.0.3 server files zip and a basic client with the same, the crash does not happen and the ingot is produced.

Java Version: 1.8.0_211-b12

forge-1.12.2-14.23.5.2831-universal
NuclearCraft-2.16c-1.12.2
jei_1.12.2-4.15.0.278

**Comment by LezChap** [comment]
I have to disagree with MacAttack-UK...I was able to replicate the crash with a fresh install with only the mods listed.
Crashlog: https://pastebin.com/bAYgNRWa

Steps to replicate:
1. Have a powered Alloy Furnace (used Califwhatever RTGs on 5 sides)
2. Fully upgrade the Alloy Furnace with Speed and Energy Upgrades. (important, doesn't seem to crash without them)
3. Place Lithium DUST in the first slot. (doesn't seem to crash in the second slot)
4. Place Ferroborn Ingot in the second slot.
5. Crash almost always happens before the first ingot is produced.

**Comment by HyricanWHV** [comment]
I just had the same crash (in single player) and started to test to find the reason as it was working one just fine minutes before the crash. (also corupted the world) 
Finding was the same as from LezChap. If you put the Lithium in the first slot it causes a crash, Lithium in second slot works fine. Did not test this without upgrades.

**Comment by MacAttack-UK** [comment]
> 
> 
> I have to disagree with MacAttack-UK...I was able to replicate the crash with a fresh install with only the mods listed.
> Crashlog: https://pastebin.com/bAYgNRWa
> 
> Steps to replicate:
> 
>     1. Have a powered Alloy Furnace (used Califwhatever RTGs on 5 sides)
> 
>     2. Fully upgrade the Alloy Furnace with Speed and Energy Upgrades. (important, doesn't seem to crash without them)
> 
>     3. Place Lithium DUST in the first slot. (doesn't seem to crash in the second slot)
> 
>     4. Place Ferroborn Ingot in the second slot.
> 
>     5. Crash almost always happens before the first ingot is produced.

My bad, didn't try them the other way round. I shall be more vigilant next time.

**Comment by LezChap** [comment]
No criticism, you thought you did what you needed in a "clean" environment to replicate the bug and failed to do so...it happens, sometimes these things are weird edge cases with multiple interactions.  Sometimes it's something we don't think a certain factor (which item goes in which slot, or number of upgrades, etc) is important, and fail to fully test all the possible combinations...there's a lot to test, and all we can do is test what we can think of and report as much detail as possible to try to track the issue down. :)

**Comment by CookedPages** [comment]
I just had my game crash/corrupted world in 4.0.5. Same setup as the repo above, except my lithium dust WAS in the second slot. Crash Log pastebin below if that's helpful:

https://pastebin.com/n4Z8eNAt
