### ISSUE TITLE
Forgiving Void is less forgiving

### ISSUE THREAD

**Issue by crazydud24** [Darkosto/SkyFactory4Issues#711]
## Bug Report

I began hosting my own server for me and a friend to play last night after enjoying the pack solo. I jump off the edge to show him the forgiving void mod and just end up dying, unlike my single player world where the mod acted normally. 
Note; I had to re upload this because I included my personal server ip (my ip)not my proudest moment. But since then I have learned that only I am affected, my friend has your expected interactions with the mod on my server. I have reinstalled and updated and am still effected but the mod works normally for me on single player still.

## Expected Behaviour

upon falling into the void the player should reappear at the top of the world.

## Possible Solution

I tried poking around the server files for a fix in the configs but I am rather entry level at this whole thing and didn't want to break anything, my best guess would be in configs or prestige or world type.

## Steps to Reproduce (for bugs)

1. download server files for sky factory 4, follow the README file, and port forward
2. join server
3. fall into void

## Logs

* Client/Server Log: Client/Server Log: https://pastebin.com/dSjtPJ9C
note, I jumped off intentionally at the very end
* Crash Log: N/A

## World Information

* Preset:

* Prestige: Default

* Modpack Version world created in: 4.0.2

* Additional Content Installed: N/A

## Client Information

Modpack Version: 4.0.2
Java Version: "1.8.0_201"
Launcher Used: twitch
Memory Allocated: my client: 10G (i know its stupid) server 4G
Server/LAN/Single Player: personally hosted server* Optifine Installed: no
Shaders Enabled: no

## Server Information
Java Version: "1.8.0_201"
Operating System: windows 10
Hoster/Hosting Solution: not fully sure what this means (I host the server)
Sponge (Non-Vanilla Forge) Server: again don't know what this means, I am using the provided server files with no modification at all.

**Comment by sk2048** [comment]
Did something go wrong when you first connected to the server? A crash or time out?

It sounds like you're missing the game stage that enables forgiving void on a player by player basis. Run `/gamestage info` and if you're missing `non_pacifist` or `forgiving_void` add them by running `/gamestage add @p <stage_name>`

(If you're not an op, get an op to do it but replace `@p` with your player name)
