### ISSUE TITLE
Added ExtremeReactors to the modpack, Yellorium Ingot doesn't show up in JEI, No Furnace recipe for yellorium amber

### ISSUE THREAD

**Issue by MayusYT** [Darkosto/SkyFactory4Issues#715]
## Bug Report

* Additional Content Installed: Extreme Reactors

## Client Information

* Modpack Version: Latest
* Java Version: 8
* Memory Allocated: 3GB
* Server/LAN/Single Player: Single Player

## Description
I added the Extreme Reactors Mod to the Modpack. In order to obtain yellorium, I added a yellorium tree in the sky_orchards config, with "unused" as item name. My goal is to create Amber from the acorns and resins that can be molten in a furnace, just like any other metal (for example tin).
Where should I add the furnace recipe for amber_yellorium -> ingotyellorium? When I add it to /scripts/crafttweaker/recipes/furnace.zs, it just gets ignored:
```zenscript
<sky_orchards:amber_yellorium>: [<bigreactors:ingotyellorium>]
```

### Another issue I discovered:
The yellorium ingot doesn't show up in JEI. I searched in the JEI black list, but there is no yellorium blacklisted.

**Comment by sk2048** [comment]
Significant changes to the pack aren't really something we can help with, why not just use Uranium though - I believe all the recipes accept the uranium ore dictionary, and it's also accepted as fuel.
