### ISSUE TITLE
World reset completely after Parabox loop (server) 

### ISSUE THREAD

**Issue by lays24mc** [Darkosto/SkyFactory4Issues#716]
Hi, 

Whenever I use the Parabox Loop, the server is restarted and my world is set to zero completely. As if I would start a completely new world in default. No crash log is created. What am I doing wrong?

Skyfactory 4.0.3
World from 4.0.2
Java 8_191
No extra mods
5GB Ram
Prestige mode true

**Comment by sk2048** [comment]
The game may not crash, but there should still be a log. Check in your server folder there should be a folder called logs. Try to upload both the log where the time loop is closed and the server shuts down as well as the one where the server starts up again.

**Comment by lays24mc** [comment]
I'm sorry. I have make the wrong settings, after backup my world. Its not a modpack issue ^^
