### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by stepkrep** [Darkosto/SkyFactory4Issues#717]
## Logs
* Client/Server Log: https://pastebin.com/R8M57Lqf
* Crash Log: https://pastebin.com/Dqg6nH26

## World Information
* Preset: Sky Factory 4 Classic​
* Prestige:  Yes
* Modpack Version world created in: 4.0.2

## Server Information
* Java Version: Java 8
* Hoster/Hosting Solution: OMGServ

**Comment by Knoxxar** [comment]
Java Version: 1.8.0_72 is a little bit old for your Server .... update it

**Comment by justinrusso** [comment]
Check out the discord for help http://bit.ly/DarkostoDiscord
