### ISSUE TITLE
Tombstone crash when players dies while holding bad Carryon block

### ISSUE THREAD

**Issue by dualmoon** [Darkosto/SkyFactory4Issues#724]
## Bug Report
A player used carryon to pick up an Opencomputers server rack. This of course bugged out the block. As the player was trying to figure out what to do next, they ran into a cactus and died. When they tried to click Respawn, nothing happened. After a few seconds they were kicked from the server.

## Possible Solution
I get the feeling Opencomputers will just be blacklisted which is a damned shame, but it will probably fix the symptom. The cause will remain, however.

## Logs
This doesn't cause a crash of the client or server, but it does dump a massive number of traceback lines to the console. One such instance can be found here: https://gist.github.com/dualmoon/9b0ff92cecf2947395ceb9fbb8a82893

## Additional
In an attempt to resolve, I tried editing the player's dat file to reset the DeathTime per a StackExchange conversation I found. This didn't seem to help. I tried deleting all tombstone saves for the player, which didn't help either. Giving the player Op and Creative didn't change anything. Deleting (renaming) the player's entire data file caused them to just be unable to connect entirely. Ultimately we just rolled back the server.

## World Information

* Preset: Chunk Norris

* Prestige: No

* Modpack Version world created in: 4.0.1

* Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.2
* Java Version: JRE8
* Launcher Used: ATLauncher
* Memory Allocated: 4GB
* Server/LAN/Single Player: SMP
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Oracle JRE8
* Operating System: Ubuntu Server 18.10 VM on Proxmox host, dedicated hardware
* Hoster/Hosting Solution: self

**Comment by Corail31** [comment]
Hi dualmoon, i don't specially see a crash or tombstone specially mentioned in this issue, except it happened during death. (carryon is known to work improperly with OC)
NB : Tombstone makes passive saves of players allowing to restore them to a previous stage without the need to restore all your server. (tbrecovery)
