### ISSUE TITLE
Shift clicking items into Processing Cables crashes game

### ISSUE THREAD

**Issue by forshale** [Darkosto/SkyFactory4Issues#726]
## Bug Report
  When shift clicking an item into a processing cable, the process will crash the game

## Expected Behaviour
 Game crashes instead of that stack of items being placed into the processing cable

## Steps to Reproduce (for bugs)

1. Have processing cable and an item in inventory
2. Hold shift and click on an item while in the inventory of a processing cable

## Logs

* Client/Server Log:
* Crash Log:  https://gist.github.com/forshale/2066c47e85622e6ad13d4daecd89969c

## World Information

* Preset: Sky Factory 4

* Prestige: Yes

* Modpack Version world created in: v4.0.0

* Additional Content Installed: Optifine

## Client Information

* Modpack Version: v4.0.3
* Java Version: 1.8.0_51
* Launcher Used: Twitch
* Memory Allocated: 4gb
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by sk2048** [comment]
No crash report and your log indicates nothing but normal gameplay.
