### ISSUE TITLE
@Deep Mob Learning Mod Completely Useless Now

### ISSUE THREAD

**Issue by ArkavianX** [Darkosto/SkyFactory4Issues#730]
As of 4.0.3 the:
-- Deep Mob Learning Guide, referenced by some of the tools/items but no where to be found
-- Trial key cannot be attuned to the androids, mod actually acknowledges this. 
-- Trial key cannot attune to wither skeleton, despite killing over a dozen, some regular zombies and other vanilla mobs, the mod gives no message as to why/why not. 
-- Data modelonly has recipe to android and nether dragon 
-- Simulation Chamber has no recipe

**Comment by tjd46** [comment]
I was able to attune a key to wither skeletons https://i.imgur.com/MoU5Uhc.png and it shows a recipe for the sim chamber for me as well https://i.imgur.com/jq4tRsF.png don't know about the rest though.

**Comment by WhyNotCthulhu** [comment]
You're missing gamestage non-pacifist that's the cause of your recipe issues.

**Comment by justinrusso** [comment]
For further help please ask in the SF4 discord channels http://bit.ly/DarkostoDiscord

**Comment by ArkavianX** [comment]
Ok, WhyNotCthulhu solved the issue, thx
