### ISSUE TITLE
AE2 Crafting terminal doesnt replenish after crafting a stack

### ISSUE THREAD

**Issue by 016Nojr** [Darkosto/SkyFactory4Issues#733]
**Describe the bug**
When shift clicking a recipe in the crafting terminal to craft a stack the crafting table isnt replenished with more items after the stack is crafted.

**Expected behavior**
When a single stack was crafted the crafting table should be replenished to be able to craft more stacks/items

**Environment**
- Singleplayer
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2831

## Possible Solution
No clue, never had this issue before.

## Steps to Reproduce (for bugs)

1. Fill ME-System with enough items to craft more than a stack of (Tested with Redstone Blocks (From Acorns))
2. Shift click crafting recipe

## Logs

* Client/Server Log: [Client Log Gist](https://gist.github.com/016Nojr/79005a56eb66087eb0a99c2f67f492d3)
* Crash Log: None

## World Information

* Preset: Sky Factory 4

* Prestige: No

* Modpack Version world created in: 4.0.0

* Additional Content Installed: None when testing

## Client Information

* Modpack Version: 4.0.3
* Java Version: 8.201
* Launcher Used: Jar
* Memory Allocated: 7,5 GB
* Server/LAN/Single Player: Single Polayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Adam022695** [comment]
I have this same issue

**Comment by sk2048** [comment]
I cannot reproduce this if I give my ME network sufficient energy buffer. Put more Energy Cells or Dense Energy Cells on your network and this issue should go away.

**Comment by 016Nojr** [comment]
ah, didnt think of that, problem solved then. Thank you
@Adam022695 Solution to our problem ^^

**Comment by Thomas5738** [comment]
I have the same problem but not only AE2 it's also Simple Storage Network..
