### ISSUE TITLE
Astral Sorcery blocker due to missing constellation papers

### ISSUE THREAD

**Issue by dskw** [Darkosto/SkyFactory4Issues#736]
## Bug Report
Unable to progress in astral sorcery due to missing constellation papers / spawn structures.

## Expected Behaviour
Usually you would find constellation papers in Astral Sorcery temples and such, to gain knowledge of at least one constellation and use it later on for attunement and progressing in the mod. Papers are craftable later on, but require the knowledge of at least a single constellation for attunement and crafting.

## Possible Solution
Implement a way to gain the first constellation paper or even for the basic 5 constellations (Aevitas, Armara, Discidia, Evorsio, Vicio)

## Steps to Reproduce (for bugs)
Check the recipe for any of the constellation papers:
They require the Iridescent Altar, which requires an attuned crystal for its creation. Attunement requires you to know at least one constellation.

## World Information
* Preset: standard SF4 single tree topology
* Prestige: off

## Client Information
* Modpack Version: 4.0.1

**Comment by dskw** [comment]
I've seen that generation is enabled for lost cities (dim 111) but even after flying through >40 spheres there is nothing except for aquamarine to be found. No structures from Astral Sorcery.

**Comment by PyroBurnem** [comment]
you do not need constellation papers to get to the iridescent altar at all, attunement is just a thing to the side if you want upgraded stuff

the crafting recipes for the altars only require the unattuned celestial crystals at the very most until you can craft your own constellation papers

**Comment by dskw** [comment]
Damn.... how could I overlook that?!
You're right. Ok, I'll close this ticket as invalid then :)
Thanks a lot for pointing that out to me PyroBurnem!
