### ISSUE TITLE
Cyclic Packager - No recipe for Petrified Amber

### ISSUE THREAD

**Issue by pure-fire** [Darkosto/SkyFactory4Issues#737]
## Bug Report

The Cyclic Packager does not have a recipe for Petrified Amber.

## Expected Behaviour

I don't see a reason other than possible oversight this recipe isn't available.

## Possible Solution

Add the recipe in JEI

## Steps to Reproduce (for bugs)

1. Put 4 resin and 5 acorn into the Packager
2. The Packager does not craft the Petrified amber
3. Petrified Amber recipe is not visible in JEI for the Cyclic Packager either.

## World Information
 
* Preset: Chunk Norris

* Prestige: Yes
 
* Modpack Version world created in: 4.0.2

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.3
* Java Version: Current
* Launcher Used: Twitch
* Memory Allocated: 12GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: None

**Comment by sk2048** [comment]
Plenty of the ambers do not have packager recipes, instead with 4 acorns and 5 resin they make the resource directly. 4 Petrified Acorns + 5 Petrified Amber makes Cobblestone.
