### ISSUE TITLE
It wont let me launch a single player world

### ISSUE THREAD

**Issue by TimBukTwo8462** [Darkosto/SkyFactory4Issues#738]
So I launch the Modpack, I turn my Hotspot off after this, I play offline. I try launching a new world 3 times and I get this error message. "Connection Lost: Internal Exception: Java.nio.channels.ClosedChannelException"
Why do I need a connection to play on a single player world I just created, and I know it works cause I have another world I made and it worked fine.

**Comment by sk2048** [comment]
The connection it's referring to is between the two Minecraft threads - the internal server thread and the client thread. The connection is between two things on your computer.

Programming it like this made it simple to make Minecraft a multiplayer game.
