### ISSUE TITLE
Lapis Amber is not smeltable in Tinkers Smeltery

### ISSUE THREAD

**Issue by ICrowleyI** [Darkosto/SkyFactory4Issues#741]
## Current Behaviour
Lapis Amber can only be used for AE2 Cable Facades or in the NuclearCraft Melter.
No recipe to turn into Lapis Lazuli.

## Expected Behaviour
Lapis Amber should be smeltable in the TC Smeltery or crafted into Lapis Lazuli.

## Possible Solution
Add recipe for the Smeltery or Workbench.

## World Information
Preset: Sky Factory 4
Prestige: Disabled
Modpack Version world created in: 4.0.2
Additional Content Installed: None

## Maybe Related
#410 #621

**Comment by Xuhybrid** [comment]
You don't use Amber for lapis. Use the acorns to make a lapis block.

**Comment by sk2048** [comment]
See #752
