### ISSUE TITLE
SkyFactory 4 Normal World

### ISSUE THREAD

**Issue by CutePuppy871** [Darkosto/SkyFactory4Issues#743]
Whenever I start a SkyFactory 4 server, it goes to a normal world. Also, the /topography commands do not work.

![Not Working](https://user-images.githubusercontent.com/50084035/56868859-bc46c200-69bd-11e9-9a1b-cc2cddbadd59.PNG)

Extra Information: I use Scalacube to host my server, I use the Twitch Launcher to start SkyFactory 4

**Comment by sk2048** [comment]
Check out the discord! There's a channel called #sf4-server where plenty of people will be happy to help!

You're probably starting the wrong jar file, make sure your host knows to start `forge-1.12.2-14.23.5.2831-universal.jar`, and not the `minecraft-server.1.12.2.jar`

**Comment by CutePuppy871** [comment]
how do i change that? also, what is the discord?
