### ISSUE TITLE
Bounding Box pickup when using Carryon with Mekanism's Advanced Solar Panel

### ISSUE THREAD

**Issue by Daecher** [Darkosto/SkyFactory4Issues#748]
## Bug Report

When using carryon to pick up the Advanced Solar Panel (from Mekanism) from the top side you pick up a Bounding Block instead. 

## Expected Behaviour

You should pick up the Advanced Solar Panel.

## Possible Solution

Blacklist the Advanced Solar Panel from carryon.

## Steps to Reproduce (for bugs)

1. Shift+right click the top face of an Advanced Solar Panel.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Skyfactory 4

* Prestige: Yes

* Modpack Version world created in: 4.0.3

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.3
* Java Version: Java 8 update 211
* Launcher Used: Twitch
* Memory Allocated: 
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Java 8 update 211
* Operating System: Mac OS
* Hoster/Hosting Solution: Server files on own machine
* Sponge (Non-Vanilla Forge) Server: No

**Comment by heatseeker0** [comment]
A player on my server literally did the same about 2 hours ago. Ended up with a bunch of these bounding blocks that are unbreakable even in creative mode.

**Comment by justinrusso** [comment]
@heatseeker0 you could try using `/setblock` to replace the block with air. An update to Mek might also allow them to be broken but not sure.

**Comment by Masciguy** [comment]
You can also remove the block while you are carrying them with carry on by entering the command "/carryon clear"
