### ISSUE TITLE
Parabox shuts down server and does not restart it

### ISSUE THREAD

**Issue by observeroftime02** [Darkosto/SkyFactory4Issues#758]
Unless I'm missing something, using the parabox shuts down the dedicated server after hitting "Loop: Off", and I have to manually restart it. I'm not sure if this is a server problem or what, I just know that this mod is what shuts down my server and does not restart it. 

I'm using the SF4 4.0.3 server pack on Ubuntu if it matters. Do I have to set up a process watcher and call the StartServer.sh script when it detects that the server has quit, or are there simpler ways of ensuring the server starts back up after a loop has been completed?

**Comment by sk2048** [comment]
A mod cannot restart the server, but the way Parabox works means it must stop it.

You can add an infinite loop to the start script that makes this process pretty simple;

```sh
#!/bin/sh

# Read the settings.
. ./settings.sh

# Start the server.
start_server() {
    java -server -Xms${MIN_RAM} -Xmx${MAX_RAM} ${JAVA_PARAMETERS} -jar ${SERVER_JAR} nogui
}

while true
do
    echo "Starting Sky Factory 4 Server..."
    start_server
    echo "The server will reboot shortly, press ctrl+c now to terminate."
    echo -n "Rebooting in:"
    for i in 5 4 3 2 1
    do
            echo -n "$i..."
            sleep 1
    done
    echo "Rebooting now!"
done
```
