### ISSUE TITLE
(4.0.3) Can't make red dye and no auto bonsai - bug or feature removal?

### ISSUE THREAD

**Issue by Duke-Nukem-3D** [Darkosto/SkyFactory4Issues#759]
I have just starting play Skyfactory 4 (Minecraft 1.12.2) after watching SortaMaliciousGaming on Twitch play it. He played it not long after it was out so I assume an early version than 4.0.3. My problem is to make redstone sapling I need red dye which you get from poppies. However when I use bone meal on grass the only flower that appears is the blue orchid unless I'm missing something ?!?

Also SortaMaliciousGaming created a bonsai tray with a hopper to auto grow the trees. Has this been removed as it doesn't appear to be a recipe anymore. I get the notes for the version updates but there was no mention of this being removed.

Anyone got any ideas how to fix these problems?

**Comment by Snowgods** [comment]
you're in a swamp biome, you will need to get out of it in order to get poppies. This is normal vanilla behavior.

**Comment by Duke-Nukem-3D** [comment]
Ah that is annoying as there is no indication on what biome I'm in. I have however just managed to work it out though. Destroying the grass I managed to get beetroot seeds, beetroot works same as poppy and coverts straight to red dye. I now have redstone sapling :-)

Also there doesn't appear to be a controller for the full size smelter just the little one ?!?

**Comment by sk2048** [comment]
You're playing in prestige mode, which is why you don't have a hopping bonsai or a smeltery controller. Press `p` to see what is gated.
