### ISSUE TITLE
Add the Hopping bonsai pot in worlds with prestige mode enabled

### ISSUE THREAD

**Issue by ToXXiCPanda** [Darkosto/SkyFactory4Issues#760]
When I play in a world with prestige mode enabled I can't craft a Hopping Bonsai pot. It's annoying to harvest every single bonsai pot by hand.

World Information
Preset: Sky factory 4
Prestige: Yes
Modpack Version world created in: 4.0.3
Additional Content Installed: None

**Comment by SirioIlBe** [comment]
the hopping bonsai is locked behind the first prestige point...if im not wrong...im playing without prestige...too boring not having oreExcavator enabled...

**Comment by darkshadow005** [comment]
i have prestige and I unlocked the hopping bonsai I went to the lost cities when I came back I couldn't craft hopping bonsai anymore still have the 10 i'm using

**Comment by sk2048** [comment]
That's a different issue @darkshadow005 

Did you respec? If not, it didn't save that you had unlocked the game stage. Run `/gamestage add @p bonsai_trees`
