### ISSUE TITLE
Paraboxes not accepting power from thermal dynamics fluxducts

### ISSUE THREAD

**Issue by mendel3** [Darkosto/SkyFactory4Issues#764]
## Bug Report

Thermal expansion fluxducts do not connect to the parabox and don't give them any power

## Expected Behaviour

It should power the parabox

## Possible Solution

Make the parabox accept COFHRF? I don't really know
## Steps to Reproduce (for bugs)

1. Hook up any Fluxduct between a power source and a parabox
2. Fluxduct connects to power sorce

## Logs

* Client/Server Log: https://gist.github.com/mendel3/0b70fe21008a71371aa9c34007e28ed0
* Crash Log: No crashes

## World Information

* Preset: Original Sky Factory

* Prestige: Yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed:
None
## Client Information

* Modpack Version: 4.0.3
* Java Version: Java 8 201
* Launcher Used: JAR Launcher
* Memory Allocated: 8192mb
* Server/LAN/Single Player: Single Player with LAN enabled
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sk2048** [comment]
The parabox does not accept power until it is activated, as such fluxducts will render as disconnected.

As soon as you activate the parabox they will connect.
