### ISSUE TITLE
Crafting Charger Tier II, Tier III or Wireless Charger doesn't grant advancement

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#78]
Charger Tier I was correct. Placed the Tier II charger into the world and picked it up again and still no advancement, same with Tier III and wireless charger.

SkyFactory4-0.1.2

**Comment by Darkosto** [comment]
I just tried this out and can't replicate, mine all triggered correctly. Would you mind grabbing the update i sent out and trying it again?

**Comment by MongoTheElder** [comment]
This is working in the latest version 0.2.0, OK to close
