### ISSUE TITLE
Entering compact machine (in compact machine world) granting Enter the Nether achievement

### ISSUE THREAD

**Issue by mhykolcom** [Darkosto/SkyFactory4Issues#79]
Upon entering a compact machine from the hub in the compact machine world you are immediately given the entering the nether achievement.

**Comment by Darkosto** [comment]
I might need more testers on this one to confirm, I'm not able to get it to replicate.

**Comment by JackRuby1** [comment]
I just confirmed it happened to me on pack start up brand new world creation on 0.1.2

**Comment by Darkosto** [comment]
I think this issue isn't happening any longer or at least no reliable way to replicate?
