### ISSUE TITLE
Impossible to make pink slime ingot in pacifist mode

### ISSUE THREAD

**Issue by Davey876** [Darkosto/SkyFactory4Issues#797]
## Possible Solution

add a new crafting recipe for pink slime ingot using pink slime balls in pacifist
liquid pink slime in a fluid sieving machine requires about 1 slime and 1 iron for a slime ingot so a simple  shapeless crafting recipe for that would fix it for pacifist mode runs.

## Steps to Reproduce (for bugs)

1.  try to make blackhole controller, realize there's no recipe without killing pink slime with a slaughter house
2. 

## World Information

* Preset: pacifist

* Prestige: yes

* Modpack Version world created in: 4.0.1 playing in 4.0.3

* Additional Content Installed: 0

**Comment by Davey876** [comment]
pumpkins and ink sacks are also impossible to get in pacifist mode.

**Comment by Davey876** [comment]
in pacifist mode witherkill advancement should trigger when you get a netherstar and/or remove the advancement completely when in pacifist mode

**Comment by Davey876** [comment]
![image](https://user-images.githubusercontent.com/27825010/57116110-07940400-6d21-11e9-9c0a-4be6a2f8e3b5.png)

age of exploration doesn't require ardite and cobalt ore to be found.

**Comment by sk2048** [comment]
That last one is not a bug; they are not obtainable in all world types.

**Comment by Darkosto** [comment]
Pink Slime is very much available to the player, use Deep Mob Learning to obtain the pink slime ball.
