### ISSUE TITLE
Leaves in Ore Dictionary

### ISSUE THREAD

**Issue by timmit99** [Darkosto/SkyFactory4Issues#798]
I am on version 4.0.3 and noticed that the "Barrels, Drums, Storage & More" crate with an Ore Dictionary upgrade wont take multiple leaves even though they all have the Ore Dictionary Name "treeLeaves". Is this due to the fact that they each ALSO have a dictionary name of "treeLeavesCopper" or "treeLeavesNickel"

Is this intended behavior? It would be nice to have the leaves be able to be stored in one block as there aren't any unique uses for the separate leaves.

**Comment by Crackerhead22** [comment]
Currently leaves are on the ore dictionary blacklist for BDS&M, that should be changed in the next update.
