### ISSUE TITLE
Not being damaged at all after eating cyclic heart containers 

### ISSUE THREAD

**Issue by Hector-Glez** [Darkosto/SkyFactory4Issues#799]

**Comment by DeciTM** [comment]
> Please follow the templates, any issue which fails to provide the requested information will be closed.

Don't forget to fill out the form!

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/Darkosto/SkyFactory4Issues/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
