### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Drakma** [Darkosto/SkyFactory4Issues#80]
https://pastebin.com/W9exR37S

SF4 0.2.0 fresh install
Forge 2796 fresh install

**Comment by Darkosto** [comment]
Hey @Funwayguy it looks like you're calling client side code on the server? 

Temp fix Drakma, backport BDSM until it's fixed.

**Comment by Drakma** [comment]
Attempted to backport but it broke Triumph

**Comment by scottieboy1794** [comment]
I have the same issue with AE2 with title energy cell.[https://pastebin.com/B9qQWQx7](url)

**Comment by sk2048** [comment]
This is not the same issue, please open a new issue with all the required information.
