### ISSUE TITLE
Crash when loading the game: "Caught exception from Astral Sorcery"

### ISSUE THREAD

**Issue by lord-ne** [Darkosto/SkyFactory4Issues#802]
## Bug Report

My game first crashed upon trying to enter a compact machine. I assumed it was just because I'm using a laptop and not some beefy gaming PC, and I tried to relaunch the game. However, in the middle of loading the game, on the loading screen "Loading - Initializing mods Phase 1," the game crashed again with the following error message:

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Astral Sorcery (astralsorcery)"

I received this same error message every subsequent time I tried and relaunch the game.

## Logs

* Client/Server Log: 
[First Crash](https://privatebin.net/?970f133a2faf10ce#Z5lU1vM8THigzriFa6Xn0Ii7Sq80RPHJB3MTA38jHM0=)
[Second Crash](https://pastebin.com/sfCyfG3M)

* Crash Log: 
First Crash: I unfortunately did not save the crash report, and it does not appear to have been saved in the "crash reports" folder
[Second Crash](https://pastebin.com/UFp4kG4K)

## World Information

* Preset: Whatever the default is

* Prestige: No

* Modpack Version world created in: 4.0.3

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.3
* Java Version: "Version 8 Update 191"
* Launcher Used: Twitch Launcher
* Memory Allocated: 12 gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment]
Try reinstalling the pack, copy across your saves folder.

Also worth noting you aren't using the version of Java you say you are. Your crash report states you are using 1.8.0_51, which is several years old at this point, but Mojang still bundle it with the native launcher. You should tell Twitch to use that Jar launcher, which can use any version of Java you have installed.

For further help on this issue, please join the Discord - #sf4-client-support - https://discord.gg/darkosto

**Comment by lord-ne** [comment]
Reinstalling the pack fixed the issue. Thank you.
