### ISSUE TITLE
Can't disable prestige

### ISSUE THREAD

**Issue by VictorCodesseira** [Darkosto/SkyFactory4Issues#803]
## Bug Report

Can't disable Prestige Mode. Pressing P tells me it's off, but the prestige content is still locked behind prestige. Have tried updating Java, restarting Minecraft and the computer, updating the modpack, and doing a clean install through Twitch Launcher(removing backups).

## Expected Behaviour

Expected prestige to be disabled, but instead I have no access to content, and no prestige menu(if I enable prestige on a world, the menu comes back).

## Possible Solution

If I understood correctly, you are using the Ages locking mechanism, like in Sevtech. I'm not how to go about fixing it, but it's possible the Ages mechanism isn't being disabled when prestige is.

## Steps to Reproduce (for bugs)

1. 
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkyFactory 4

* Prestige: No

* Modpack Version world created in: 4.0.3

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.3
* Java Version: 1.8.0.211
* Launcher Used: Native
* Memory Allocated: 6400 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment]
How the system works: A bunch of recipes and items have their access gated using game stages, whether you are playing prestige or not these stages are present as recipes have to be registered during game start and cannot be modified while the game is running. When you start a world playing prestige you are given only the stages that correspond to rewards you've unlocked, plus a couple of others appropriate to the preset you're on. When you start a non-prestige world, you are given all the stages for all of the prestige rewards, plus a couple of others depending on preset.

Disabling prestige mode on a world that was already created does not give you all of the rewards. It shouldn't, so this is not a bug. Some of the rewards are for players playing prestige only - the starting items, the ProjectE map.

So if you start a map using prestige and then later decide to disable it there is a bit of manual work that has to be done for existing players. Whilst they are online you must run `/execute <player> ~ ~ ~ function triumph:classic_mode` to grant all stages for a named player from the server console or as an op or `/function triumph:classic_mode` for yourself (assuming you are opped).

**Comment by VictorCodesseira** [comment]
I understand how the system works. But as I said, prestige stays on(locking OreExcavation, for instance). Even if I create a completely new world.

**Comment by sk2048** [comment]
Describe the series of events there for me please - when you create the new world, does prestige start enabled regardless of what you set it to in the world creation screen?

Do you crash/timeout during world creation? This can interrupt the initial scripts and leave you in a state with Prestige disabled but no unlocks.

**Comment by VictorCodesseira** [comment]
Whenever I create a world:
If prestige is enabled, works properly
If prestige is disabled, and I press P, it does say I don't have it enabled, but content is still locked.

No crashes or timeouts. The initial scripts sounds like the problem. Any way I can run them manually after world generation?

**Comment by sk2048** [comment]
Last paragraph of my first comment gives a command you can use to grant all prestige locked gamestages. Before you do that though, can you tell me the output of `/gamestage info`

**Comment by VictorCodesseira** [comment]
Don't have my pc right now, will do as soon as I get home.

**Comment by VictorCodesseira** [comment]
So, I executed the command, and the output i got was:
non_pacifist, forgiving_void

The command did work, but it is still very weird that it's not happening on its own. Just did a fresh install of the modpack, but nothing changed. If anything else is needed to debug, I'd be happy to help.
