### ISSUE TITLE
Inscriber JEI Issues

### ISSUE THREAD

**Issue by Krameht** [Darkosto/SkyFactory4Issues#807]
## Bug Report

JEI claims iChisel works within AE2 Inscriber, but it doesn't

## Client Information

* Modpack Version: 4.0.3
* Launcher Used: ATL
* Memory Allocated: 8Gb
* Server/LAN/Single Player: SP
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment]
It does, the inscriber is just fussy about NBT and meta. It must be fully charged and freshly crafted.
