### ISSUE TITLE
Full lava source block from wooden cauldron with 1 cobblestone worth of lava

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#81]
When making lava with a wooden cauldron, you can gain a full source block of lava with just 1 block of cobblestone.
https://clips.twitch.tv/PlumpWittyShrimpStinkyCheese

**Comment by Darkosto** [comment]
Yeah, not sure if we can do something about this? 🤔 What do you think @KnightMiner ?

**Comment by KnightMiner** [comment]
This is actually on @Mrbysco side, he adds the code which makes wooden ones break from hot fluids. My code for dropping fluids (which it seems is disabled in SF4 anyways) only happens when the iron one is manually broken and has a full check.

**Comment by Mrbysco** [comment]
I've uploaded an update that makes it actually listen to the config. Somehow I overlooked that part.

**Comment by Darkosto** [comment]
Fixed in new version.
