### ISSUE TITLE
ItemDuct from Thermal Dynamics

### ISSUE THREAD

**Issue by eeeeeeeeeeeeeeeeeex** [Darkosto/SkyFactory4Issues#811]
When i use itemducts to transfer items from hopping bonsai pots into crates with resin and acorns the items dont seem to go in, it cycled about 10 times and i didn't get a single thing in the crates, i even had an empty crate so i should have atleast gotten one oak wood or something.
If you have any suggsstions on any other item conduits/ducts/pipes i could use that would be very helpful thank you.
~ Alex

**Comment by sk2048** [comment]
https://discord.gg/darkosto for gameplay support :)
