### ISSUE TITLE
Pristine Ghast Matter not detected

### ISSUE THREAD

**Issue by RobertLSnead** [Darkosto/SkyFactory4Issues#814]
The Pristine Ghast Matter is not being detected in the achievements.

**Comment by RobertLSnead** [comment]
Some how it fixed it self, please disregard unless others have the same issue.

**Comment by sk2048** [comment]
For some reason we've yet to track down, advancements sometimes stop tracking until you logout and login again. I've been told it's a vanilla issue though I haven't looked into it myself.
