### ISSUE TITLE
Animal Crops very rarely spawn in grass in Default Terrain world gen, yielding a random animal seed

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#82]
I've so far found 2 random Animal Crops plants in the Over-world on a Default world terrain gen, it gives a random animal seed when broken. I don't know if this is a good thing to have or not. The plants themselves are very rare from my experience and it took about 10 minutes of flying in creative to even find a second one to confirm it was a random drop.

**Comment by Darkosto** [comment]
I probably turned them down a bunch to be honest. Although, you have animal spawns in normal world gen? Is it needed to have seeds and animals both?

**Comment by Darkosto** [comment]
Turned up from 1 out of 20 to 1 out of 15.
