### ISSUE TITLE
Update deletes save data.

### ISSUE THREAD

**Issue by Xantippus** [Darkosto/SkyFactory4Issues#821]
When the game updated to the latest version, it deleted all the files before updating, which caused my game data be be deleted. Very frustrating issue.

**Comment by sk2048** [comment]
Whilst I'm sorry that's happened to you, it's not an issue with the pack but with whichever launcher you are using. If it's Twitch, it does take backups of the profile before updating - check for a folder called Backups in Documents/Curse/Minecraft.
