### ISSUE TITLE
Squeezer from Integrated Dynamics doesn't work.

### ISSUE THREAD

**Issue by Scheigy** [Darkosto/SkyFactory4Issues#822]
## Bug Report
The Squeezer doesn't throw any items after being jumped on. Tested with a poppy, a dandelion and a bone.

## Expected Behaviour
JEI is giving recipes for these three items with the Squeezer. It should give the expected output.

## Possible Solution
Might be linked with [#505](https://github.com/Darkosto/SkyFactory4Issues/issues/505)

## Steps to Reproduce (for bugs)
No steps, just the regular use of the Squeezer.

## Logs
There's no trace of a debug log in the log file, neither on the server or the client.

## World Information
* Preset: Skyfactory 4 (standard one)
* Prestige: Yes
* Modpack Version world created in: 4.0.3
* Additional Content Installed:
Quark just for the "Merge to chest button", everything else is disabled. The current issue was already happening before this mod was installed.

## Client Information
* Modpack Version: 4.0.3
* Java Version: 1.8.0.171
* Launcher Used: Twitch
* Memory Allocated: 6144mb
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 1.8.0_212
* Operating System: Ubuntu
* Hoster/Hosting Solution: Dedicated Server

**Comment by sk2048** [comment]
Is your squeezer next to an inventory? If so it will try to insert the items there. Not sure what it will do if it fails.

**Comment by Scheigy** [comment]
I'm ashamed, you are right! I wasn't aware of this behaviour and didn't notice the results were directly sent to my storage system.

Thanks for your help.

**Comment by sk2048** [comment]
No worries, glad it was so simple! :)
