### ISSUE TITLE
Modifier Master achievement(s?) is not registering some Modifiers

### ISSUE THREAD

**Issue by forshale** [Darkosto/SkyFactory4Issues#825]
## Bug Report
  Even with a tool that has a modifier, in this case Embossment (which doesn't actually register for the advancement) it will not count towards the dadvancement even though it requires it.

## Expected Behaviour
 The Modifier Master advancement, possibly YoYo and Armory Master as well, should count the modifiers correctly

## Possible Solution
 It may be because of Embossment, there was a select type of embossment modifier that does apply in the code, as there are several types of emobbsment modifiers, the manyullyn version does not seem to apply.  The fact that fortified also doesn't work as it also has different types also implies that this is the reason.

## Steps to Reproduce (for bugs)

1. Take any Tinker's construct tool and put it in a tool forge 
2. Try to apply the modifiers, including embossment and fortify, and check to see if the Advancement Modifier master will register, same with YoYo Master and Armory Master.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkyFactory 4

* Prestige: Yes

* Modpack Version world created in: 4.0.,0

* Additional Content Installed: Optifine

## Client Information

* Modpack Version: v4.0.5 beta
* Java Version: 1.8.0_51
* Launcher Used: Twitch
* Memory Allocated: 4gb
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by mckulich** [comment]
I have same issue, achievement just dont register Embossment and Fortify, btw i was still able finish yoyo master (i obtain sticky via knightslime body part)

**Comment by speakerman36** [comment]
I am having the same issue for the Embossment on both the tools/weapons and armor achievement and Fortify for the tool/weapon achievement. Are we doing something wrong or is it broken?
