### ISSUE TITLE
World broken with updated 4.0.5

### ISSUE THREAD

**Issue by RobertLSnead** [Darkosto/SkyFactory4Issues#827]
Not sure what happened?
Loading into the world with the update has seemed to freeze all inventories.
Unable to open chest, furnace, break objects, etc.

Not sure what to do here?
Even tried removing wierding gadgets to see if that would help.

SkyFactory_4_Server_4.0.5

**Comment by RobertLSnead** [comment]
It seems to only affect certain chunks, which happen to be a critical area in my skyblock world.

**Comment by RobertLSnead** [comment]
Reverting back does not fix the issue, I'd hate to have to restart the world.

**Comment by RobertLSnead** [comment]
Might have been my fault on the update that caused the issue.
Should have removed my loaded chunks first, rolling back to a working update and will try again.
Going to close this!

**Comment by RobertLSnead** [comment]
Figured out the issue!
It appears to be an issue with spawn-protection in the server-properties file.
It was missing on the server install packs such as the server control panel.
The spawn protection when not specified activated it by default.

Recommend adding the following line to prevent this issue in the future:

#Disable Spawn Protection
spawn-protection=0

**Comment by sk2048** [comment]
Spawn protection is set to 0 already in the server files available from CurseForge.

**Comment by RobertLSnead** [comment]
I use Nitrous for my server and I used the control panel and used that to update my server.
I can tell you that the server.properties file was indeed missing the spawn-protection, had to manually add it.

Thanks for your time!
Love the pack btw! :D

**Comment by sk2048** [comment]
Glad you got it figured out, we'll keep it in mind when other people experience similar issues.

Unfortunately, we have no control over the files provided by server hosting companies.
