### ISSUE TITLE
Some advancements not triggering until world reload

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#83]
This has happened on a couple of advancements. Crafting the trigger item doesn't show any progress but closing the world and reloading brings it up to date. If you had crafted multiple items when progress is not being updated then reload, it seems to unblock updates. For example, I crafted a paper pickaxe and applied 5 reinforcements to make it unbreakable. This should have triggered "Tinkers' Modifier" and "Unbreakable Tinkers' Tool". Since neither updated, I added lapis to another tool (as a test) and put the paper pick in a chest. When I reloaded the world with the second pick (lapis upgrade) in my inventory, the "Tinkers' Modifier" advancement triggered but I had to get the paper pick from the chest to trigger "Unbreakable Tinkers' Tool".

SkyFactory4-0.2.0

**Comment by Darkosto** [comment]
I'll dig into this on Thursday. I thought we had nailed down all these particular issues with @Blargerist but it might be something that slipped by.

**Comment by Darkosto** [comment]
I think these are all resolved. If you continue to have this issue in newer versions let me know.
