### ISSUE TITLE
No prestige points for completed Ages after updating Version in Twitch client

### ISSUE THREAD

**Issue by Goralein** [Darkosto/SkyFactory4Issues#831]
## Bug Report
After updating the current Version of SF4 to version 4.0.5 and importing (copying) the designated save for a local singleplayer, there were no prestige points (spent and available) for completed ages (Sky Factory 4 and Age of Farming). 

## Expected Behaviour
The Hopping Bonsais where available as if the prestige points were spent normally. The spare prestige point for Age of Farming was not avalailable, even after clicking respec. After updating the modpack to the newest available Version, I expected to find the pp's in my save.  

## Possible Solution
Are the current gained points saved somewhere in the modpack configuration and not in the save? Maybe its a mistake by the user(me) and I missed to copy a modpack configuration after updating the modpack.

## Steps to Reproduce (for bugs)
- Updated Sky Factory 4 to the Version 4.0.5 in Twitch Launcher
- Copied Save from old Mod package to new mod Package
- Started the application from Twitch Launcher and after that opened the existing Single Player game

## World Information

* Preset: Sky Factory 4, Survival Mode, Cheats

* Prestige: enabled

* Modpack Version world created in: Uhm... I think 4.0 -> the first Version available for public

* Additional Content Installed: Optifine for Minecraft 1.12.2

## Client Information

* Modpack Version: Uhm yeah...?
* Java Version: java version "1.8.0_211, Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: true
* Shaders Enabled: false

**Comment by justinrusso** [comment]
The points are saved in the prestige directory in the root of your minecraft instance.
