### ISSUE TITLE
Metal drum does not work properly with More Buckets

### ISSUE THREAD

**Issue by oliverjanik** [Darkosto/SkyFactory4Issues#844]
When I try to grab liquid (lava) from a Metal Drum using a More Bucket (Golden bucket) I can only grab it once (1000mb).

**Comment by mklprudence** [comment]
@oliverjanik 
For metal drum and all storage containers from that mod, single clicking is get 1 item / fluid, double clicking is get a stack

In order to fill up the whole MoreBucket, double click the drum

**Comment by oliverjanik** [comment]
Thanks, I can confirm that double clicking works to fill the bucket up.
