### ISSUE TITLE
Mega Torch not stopping Matter Overdrive mobs from spawning

### ISSUE THREAD

**Issue by andrecruz24** [Darkosto/SkyFactory4Issues#849]
## Bug Report
<Matter Overdrive mobs are spawning even though there is a mega torch, I've put it on top an bellow and they still spawned. No other mob spwaned .The difficulty is on normal
![Untitled  2](https://user-images.githubusercontent.com/50302029/57198680-6ea5f880-6f6d-11e9-87dd-39a380b5a348.png)
![Untitled](https://user-images.githubusercontent.com/50302029/57198681-6ea5f880-6f6d-11e9-9642-b4b2c0636a04.png)

>

## Steps to Reproduce (for bugs)

1.I only have the mega torch placed, I've put it on top an bellow and they spawned right next to it

## World Information

* Preset: Sky Factory 4

* Prestige: Yes

* Modpack Version world created in: 4.0.1

* Additional Content Installed: OptiFine_1.12.2_HD_U_E3 and JSTR_Modded_Universal (resource pack)

## Client Information

* Modpack Version: 4.0.5
* Java Version: 8 update 211 (build 1.8.0_211-b12)
* Launcher Used: ATlaucnher
* Memory Allocated: 6144 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by justinrusso** [comment]
253
