### ISSUE TITLE
Dandelions

### ISSUE THREAD

**Issue by Lurchness** [Darkosto/SkyFactory4Issues#855]
## Bug Report

If starting a Compact Sky world in a Swampland biome, you are unable to get yellow dye to make the gold amber to progress. Dandelions do not spawn with bone meal on grass.  Unless you grind out a nether portal to kill pigmen. 

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
You can grow magic beans, which have a crafting recipe. (You can buy cactus from the market for 8 vines.)

Magic beans drop a random item from a selection on harvest, which includes all vanilla flower types.

**Comment by Lurchness** [comment]
OK how do you get the red dye to make the market. Poppies don't spawn in a Swampland biome?
