### ISSUE TITLE
Sapphire Ores give dust instead of gem. There is no recipe in JEI to get Sapphire Gem.

### ISSUE THREAD

**Issue by MalikAliMushtaq** [Darkosto/SkyFactory4Issues#860]

**Comment by sk2048** [comment]
Confirmed in 4.0.5, Sapphire Gem requires a resource hog to obtain, which is only obtainable using hog products. The ore cannot be used to obtain a sapphire, only the dust.
Both Dust and Gem are major crafting components used in Practical Logistics 2.

**Comment by Almighty404** [comment]
I had a similar problem. I found out that sapphire gems ARE obtainable, but only by digging the ore with a pickax. There is no other method than that to obtain them without using a resource hog.

**Comment by MalikAliMushtaq** [comment]
Am I a dumbass? Playing Modded Minecraft for a long time made me dumb. I forgot that gems are drpped when you crush ore with pickaxe. thanks.
