### ISSUE TITLE
Can not complete the "baby got backpack" achievement 

### ISSUE THREAD

**Issue by lavicgs** [Darkosto/SkyFactory4Issues#862]
<
Sorry I know this will probably be deleted but Im new to all of this and don't know how to find any of the stuff you are asking for.  I am playing Sky factory 4 and there is no recipe for the backpack for the achievement  its in the JEI but will not show the recipe to be created I do not have prestige on

**Comment by sk2048** [comment]
Make a Chest Builder

For further gameplay related questions, try out the discord https://discord.gg/darkosto
