### ISSUE TITLE
the skyfactory dirt and tree in the sky is not loading.

### ISSUE THREAD

**Issue by alexibacon** [Darkosto/SkyFactory4Issues#866]
when i spawned on my server it seemed like normal modded survival fix?

**Comment by DeciTM** [comment]
> Please follow the templates, any issue which fails to provide the requested information will be closed.

**Comment by sk2048** [comment]
Please go to the #sf4-server-support channel on Darkosto's Discord for help with this kind of issue

https://discord.gg/darkosto
