### ISSUE TITLE
Shift clicking items into a porcelain melter with pre-existing items resets the progress

### ISSUE THREAD

**Issue by jaredlll08** [Darkosto/SkyFactory4Issues#87]
Gif showing it off:
https://i.blamejared.com/e3vuZ.gif

**Comment by jaredlll08** [comment]
Nope, not visual, the actual process gets reset

**Comment by Darkosto** [comment]
This may be something for @KnightMiner to take a look at then?

**Comment by KnightMiner** [comment]
I'm pretty sure this is a vanilla bug as its pretty dumb when it comes to shift click. I remember trying to fix this awhile back without progress. I will look into it again when I next look at Complement

**Comment by jaredlll08** [comment]
Just tested, seems to be working!
