### ISSUE TITLE
unable craft Navigation Upgrade, opencomputer

### ISSUE THREAD

**Issue by HearthunterPro** [Darkosto/SkyFactory4Issues#874]
how to find uncraftable potion,how do i find it?

https://i.imgur.com/s0vcnQ7.png

**Comment by sk2048** [comment]
It's a placeholder, literally any potion will work including water bottles.

**Comment by HearthunterPro** [comment]
i cant craft this
https://i.imgur.com/Vc7EEcq.png

**Comment by sk2048** [comment]
In the centre of the crafting grid you need a filled map that determines the coordinate system used. Read more on the wiki: https://ocdoc.cil.li/item:navigation_upgrade

**Comment by HearthunterPro** [comment]
Thank you very much.
