### ISSUE TITLE
merging single player save into multiplayer world

### ISSUE THREAD

**Issue by huberistichub** [Darkosto/SkyFactory4Issues#876]
i am trying to merge my single player world into multiplayer. i have transferred my save and renamed it "world" after deleting the original "world" file. not the saves file but my actual save. when launching the world no moded items are able to be loaded and i am not able to place modded items from creative. also advancements
![Screenshot_110](https://user-images.githubusercontent.com/50377035/57320954-10f1e780-70f8-11e9-81e8-af91fb4219d9.png)
 are broken and ruined. works fine on my single player world.

**Comment by sk2048** [comment]
You've started a vanilla server with a modded world.

Please go to https://dicord.gg/darkosto #sf4-server-support for help with creating a server. The pinned messages include a guide. Ensure you can successfully start a modded server before transplanting your world in.
