### ISSUE TITLE
Tinkers modifers

### ISSUE THREAD

**Issue by MrStatman80** [Darkosto/SkyFactory4Issues#884]
Hi there

I am trying to do Tinker's quests for the modpack but when i put embossment and fortify modifiers  on a tool it doesn't count on the quest but it does on the tool.

So is there a command to complete the quest/advancement?

**Comment by LeSwede** [comment]
This will give you the Advancement for the Armor modifiers: /advancement grant YOURUSERNAME only sf4:age_allthethingsomglol/armormodifiers 

And this is for the tool modifiers: /advancement grant YOURUSERNAME only sf4:age_allthethingsomglol/modifiermaster
