### ISSUE TITLE
Bonsai trees mention the drop chance twice

### ISSUE THREAD

**Issue by jaredlll08** [Darkosto/SkyFactory4Issues#89]
![image](https://user-images.githubusercontent.com/5553605/50542114-5ab44980-0bbd-11e9-94a0-22cb5240cf14.png)

**Comment by justinrusso** [comment]
It only displays when hovering over the mulch in the Bonsai Trees JEI tab. In JEI itself (or anywhere else for that matter) it will only show the single-line version.

**Comment by Darkosto** [comment]
This is not something I can fix unless we are able to add a tooltip based on certain criteria: i.e. Only show when Bonsai Trees is open.

I cannot remove the tooltip added by Bonsai and I'm not able to remove my custom or else players will not have the information they need.
