### ISSUE TITLE
Filing Cabinets convert any resin/acorn to any other resin/acorn with ore dictionary upgrade

### ISSUE THREAD

**Issue by Marioluigi7896** [Darkosto/SkyFactory4Issues#893]
## Bug Report

filing cabinets can convert resins and acorns to any other type using the ore dictionary upgrade, so you can turn dirt into diamonds. While this was considered for BDS&M, filing cabinets seem to not be changed
## Expected Behaviour

Probably not have them convert
## Possible Solution

Blacklist the items or ore dictionaries to convert in
## Steps to Reproduce (for bugs)

1. Place a filing cabinet and give it an ore dictionary upgrade
2. Make a folder for a resin or acorn and put it in the filing cabinet
3. try to put another acorn or resin in the folder and see it convert

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by JackRuby1** [comment]
It was half added to BDSM- only the resin was, so either the acorns need to be allowed or removed from RFC

**Comment by sk2048** [comment]
Pretty sure Crates are supposed to be able to convert Acorns too - but the `food.*` oredict being blacklisted prevents that.

If so change that line to `^food((?!Acorn).)*$` to match any food ore dictionary except the Acorn ones.

**Comment by justinrusso** [comment]
The conversion is intended. See https://github.com/Darkosto/SkyFactory4Issues/issues/318#issuecomment-487209291
