### ISSUE TITLE
Sky Orchards mod recipes not working

### ISSUE THREAD

**Issue by acoskuner500** [Darkosto/SkyFactory4Issues#907]
## Bug Report

Out of the blue the crafting recipes for sky orchards saplings and amber have stopped showing up, and when I try to craft by memory what the recipe should be it doesn't give an output. There was an error screen briefly but there is no trace of a crash report that I can provide here.

## Expected Behaviour

The recipe just doesn't show or give output in crafting interfaces.

## Steps to Reproduce (for bugs)

1. Open and close player inventory, game froze randomly.
2. Some kind of error screen pops up that I didn't know what it was for.
3. When the world loads back none of the crafting recipes work.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkyFactory 4 (default)

* Prestige: Yes

* Modpack Version world created in: 4.0.5

* Additional Content Installed: None

## Client Information

* Modpack Version:
* Java Version: 1.8.0.51 (64 bit)
* Launcher Used: Twitch
* Memory Allocated: 3228 MB
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by justinrusso** [comment]
Please upload your `crafttweaker.log` file to pastebin. You will find this in the root of your minecraft instance.

**Comment by acoskuner500** [comment]
https://gist.github.com/acoskuner500/6173e47264b21ca9043ee1e3c290fc6d

@justinrusso

**Comment by sk2048** [comment]
It doesn't seem able to find items from Chisel for some reason, have you removed that mod?

**Comment by justinrusso** [comment]
Did you disable chisel? Looks like some mods are missing from your instance. If thats the case, try re-installing the modpack (be sure to keep your save data).

**Comment by acoskuner500** [comment]
Just to make sure, I can just go to the saves folder and copy my world
folder onto somewhere else, then I delete the mod profile from Twitch
entirely and reinstall like that? And if I put the copied folder back in it
should work right?

**Comment by acoskuner500** [comment]
Yes reinstalling the modpack did the job somehow. I have no idea why disabling a mod, especially one seemingly unrelated to the issue, had the effect that it did. Thanks guys!
