### ISSUE TITLE
Item Translocator crash the game

### ISSUE THREAD

**Issue by papadiablo** [Darkosto/SkyFactory4Issues#909]
Hi, i work a lot with this kind of item and when input iron on place of redstone it crashes my game and i can't reload the party :'( 

I let you here the crash report i think is more simple to you to understand the problem ;)

[crash-2019-05-10_20.51.28-server.txt](https://github.com/Darkosto/SkyFactory4Issues/files/3167787/crash-2019-05-10_20.51.28-server.txt)

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
