### ISSUE TITLE
Mekanism Lithium Dust

### ISSUE THREAD

**Issue by Silencfuul** [Darkosto/SkyFactory4Issues#914]
I don't understand why the Lithium Dust from Mekanism isn't in the - "dustLithium Ore Dictonary".
Because some things in Mekanism use Lithium Dust and then i always have to optain the dust from the NuclearCraft mod.

![image](https://user-images.githubusercontent.com/8363719/57561141-5f1e1980-738a-11e9-8327-779636e7c220.png)
![image](https://user-images.githubusercontent.com/8363719/57561154-67765480-738a-11e9-9b64-1bc6eab15d86.png)

**Comment by MickGeraerds** [comment]
Caused a crashloop for me using Lithium Dust in the nuclearcraft alloy maker
