### ISSUE TITLE
Any Item Duplication

### ISSUE THREAD

**Issue by almondjoys93** [Darkosto/SkyFactory4Issues#915]
## Bug Report
<Compact Sky-Cyclic Item Transfer Node, GPS Marker and Real Filing Cabinet Cabinet's>

## Expected Behaviour
Duplication of any item when using Cyclic Item Transfer Node with GPS Marker and Real Filing Cabinets Filing Cabinets

## Possible Solution
<>
## Steps to Reproduce (for bugs)

1. 2 Small Compact Machines, GPS Marker, Cyclic Transfer Node, Real Filing Cabinet Cabinet, Folder, "any item"
2. Set 1 room with the Transfer Node
3. Set Room 2 with Cabinet, with a folder with "any item"
4. Set GPS to Cabinet
5. Go to Room 1, Insert item with selected item in folder
6. Place item in transfer node, and GPS marker

## Logs
No Log

## World Information
<Compact Sky>
* Preset:
<No>
* Prestige: 
<None>
* Modpack Version world created in:
<4.0.5->
* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by LezChap** [comment]
duplicate report of https://github.com/Darkosto/SkyFactory4Issues/issues/548
