### ISSUE TITLE
Prestige Locked Items Not Available With Prestige Turned Off.

### ISSUE THREAD

**Issue by BadsyEdgecat** [Darkosto/SkyFactory4Issues#917]
## Bug Report
i have prestige turned off, yet the recipes for the hopping bonsai, mulches, and other do not exist. i have checked, the game stages for these items ARE on.

## Expected Behaviour
the expected behavior is that these items would have a recipe when prestige is turned off.

## Steps to Reproduce (for bugs)
i don't know? its just not working.

## World Information
* Preset: Default Skyfactory 4
* Prestige: No, this bug has to do with prestige being off.
* Modpack Version world created in: 4.0.2
* Additional Content Installed: None.

## Client Information
* Modpack Version: 4.0.2
* Java Version: I don't know
* Launcher Used: Twitch
* Memory Allocated: 10GB
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: No

**Comment by LeSwede** [comment]
Run all the commands found here: https://pastebin.com/nfvvUa8R 

For example: /gamestage silentadd @p mega_torch would make the Mega Torch recipe to appear.

**Comment by sk2048** [comment]
`/function triumph:classic_mode` runs all of these at once.
