### ISSUE TITLE
Skyfactory 4.0.5 crashing on startup

### ISSUE THREAD

**Issue by medic370z** [Darkosto/SkyFactory4Issues#920]
## Bug Report
Skyfactory crashing on startup. Will not load any menus or screens past initial startup. Has happened every time. Restarted with avail. Updated everything to my ability. Help pleeze.

## Expected Behaviour
not crashing on startup.

## Possible Solution
unsure of changes needed to correct situation.

## Logs
https://pastebin.com/qjRw2pU5
Log

* Modpack Version:
* Java Version: Version 8.211
* Launcher Used: Minecraft Launcher 1.6.91
* Memory Allocated: 7gb

**Comment by sk2048** [comment]
Failing to extract a zip file is normally an indication of a corrupted install.

For support on this or similar issues, use https://discord.gg/darkosto #sf4-client-support
