### ISSUE TITLE
compact machines 3 maximum compact machine

### ISSUE THREAD

**Issue by rodknightuk** [Darkosto/SkyFactory4Issues#923]
## Bug Report

if you look at jei the number of blocks too make the maximum compact machine is wrong and can not be made as is shows 98 compact machine wall and 1 block of emerald

its a too fix all need too do is more 1 block on the compact machine wall too 99 then that makes a 5x5x.
## Steps to Reproduce (for bugs)

1.look up maximum compact machine, large compact machine and giant compact machine.
2.just need too add 1 more block too maximum and large then need 2 blocks too need too be add too large compact machine

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.5
* Java Version: 1.12.2 forge-14.23.5
* Launcher Used:twitch launcher
* Memory Allocated: 
* Server/LAN/Single Player:
* Optifine Installed: no
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
A 5x5x5 cube is made up of `25*2 = 50` for the two solid faces plus 16 for each of the hollow layers `3*16 = 48`.

This is a total of 98 blocks, the recipe is correct.
