### ISSUE TITLE
Yellow Die Impossible in CompactSky World if in Swamp

### ISSUE THREAD

**Issue by desagas** [Darkosto/SkyFactory4Issues#925]
## Bug Report
There needs to be a way to craft yellow dye. My compact 4x4 grid spawned entirely in a swampland, which means no dandelions can be bonemealed, ever. They are required when I need gold amber in order to craft a gold sapling. Because all compact machines take on the biome of the spot they are placed in, all machines placed will always be swampland, including each machine and hunting dimensions compact machine areas. I believe I was extremely unlucky with this spawn, but it is something to be aware of.

## Expected Behaviour
I should be able to find some way to get yellow dye to use for gold amber regardless of what biome or compact machine I spawn in.

## Possible Solution
Add yellow dye for seeds to market, the same for all flowers, and matching eggs. Or, make it for carrots, like some of the other market items.

## Steps to Reproduce (for bugs)
Spawn initial grid entirely in a swampland. Enter any compact machine, and play. Every machine and cake will lead you to a swampland. This can not be changed. 

## Logs
NA

## World Information
* Preset: CompactSky
* Prestige: Yes
* Modpack Version world created in: 4.0.5
* Additional Content Installed: Inventory Tweaks added, Inventory Sorter removed.

## Client Information
NA

**Comment by sk2048** [comment]
Make a market -> Buy Cactus -> Craft Magic Beans -> Grow Magic Beans -> Get Flowers (among other things from the random drop table)

**Comment by desagas** [comment]
Is there a way to add the drops from magic beans to JEI, or something to say otherwise? Just Incase it happens to anyone else.

Denver Leman

On May 11, 2019, at 8:16 PM, Sam Kirby <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #925<https://github.com/Darkosto/SkyFactory4Issues/issues/925>.
