### ISSUE TITLE
Matter Overdrive Hunger Bar (Sorry, not actually an issue - not sure how to delete it)

### ISSUE THREAD

**Issue by 112358314** [Darkosto/SkyFactory4Issues#928]
## Bug Report

In game, I've become a MatterOverdrive android, but it still shows the hunger bar, and the hunger bar still goes down.

## Expected Behaviour

The hunger bar shouldn't be visible.

## Possible Solution

I'm not quite sure, but I expect that this is a conflict with MatterOverdrive and Hunger Overhall.

## Steps to Reproduce (for bugs)

1.Take the red pill
2.The hunger bar is still there afterward.,

## Logs

* Client/Server Log: https://paste.atlauncher.com/view/38638eec
* Crash Log: n/a

## World Information

* Preset: SkyFaktory 4

* Prestige: Yes

* Modpack Version world created in: 4.0.3

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.9? The current one, I always keep stuff up to date
* Java Version: Java 8 Update 11
* Launcher Used: ATLauncher
* Memory Allocated: 4096MB
* Server/LAN/Single Player: LAN
* Optifine Installed: No
* Shaders Enabled: No

**Comment by AlexejheroYTB** [comment]
You need to make an Android Station and unlock the No food requirement upgrade
