### ISSUE TITLE
Inspirations pipes have the same recipe has Thaumcraft plates

### ISSUE THREAD

**Issue by jaredlll08** [Darkosto/SkyFactory4Issues#93]
![image](https://user-images.githubusercontent.com/5553605/50567513-916d9980-0d4e-11e9-936f-875e4037b559.png)
![image](https://user-images.githubusercontent.com/5553605/50567517-ad713b00-0d4e-11e9-8a71-4c0919c21e23.png)

**Comment by Darkosto** [comment]
Will change.

**Comment by Darkosto** [comment]
Fixed!
