### ISSUE TITLE
Inventory Sorter prevents middle click crafting in AE2 terminal

### ISSUE THREAD

**Issue by thermotto** [Darkosto/SkyFactory4Issues#939]
## Bug Report

Inventory Sorter middle click conflicts with crafting requests in AE2 terminals. Nothing happens when middle clicking.

## Expected Behaviour

Middle clicking item in AE2 terminal should bring up GUI to chose amount to be crafted.

## Possible Solution

Either:
1. Blacklist all AE2 terminals in Inventory Sorter config.
2. Replace Inventory Sorter with Inventory Tweaks.

## Steps to Reproduce (for bugs)

1. Open AE2 terminal.
2. Middle click item to be crafted (assuming the crafting pattern is in the appropriate interface).
3. Nothing happens.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: ObservaTree

* Prestige: Yes

* Modpack Version world created in: 4.0.5

* Additional Content Installed: Just Enough Energistics

## Client Information

* Modpack Version: 4.0.5
* Java Version: 8u211
* Launcher Used: Twitch
* Memory Allocated: 6144 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

I confirmed that it was Inventory Sorter that was causing the conflict by temporarily removing its sort keybind. The AE2 crafting request GUI appeared correctly after that momentary fix. Without changing the keybinds I would have to switch the terminal to show only craftable items and use left click to craft.

Just to verify that it wasn't caused by Just Enough Energistics, I ran it without that mod. The issue was still present.

**Comment by MuteTiefling** [comment]
You can also shift + middle click to work around this.

**Comment by thermotto** [comment]
> 
> 
> You can also shift + middle click to work around this.

Thanks for that. I guess it's muscle memory from using AE2 since its introduction, so I always just used middle click instinctively.

However, Inventory Sorter should still be blacklisted in AE2 terminals. It serves no purpose when AE2 handles the sorting automatically.

In the meantime I reassigned the IS keybind to a different key to fix the problem. Most likely I'll switch to Inventory Tweaks anyway since it has some very useful features that I'm missing.

**Comment by Darkosto** [comment]
This works using shift-middle click. Some packs/mod combinations are going to be a bit different from what you're used to.
