### ISSUE TITLE
Tesslocator additional Mod 

### ISSUE THREAD

**Issue by Knoxxar** [Darkosto/SkyFactory4Issues#940]
Good morning from germany,

can you plz add the mod "Tesslocator"? It is better for some Server performances und have not so much particles like Translocators. 

Greets Knoxxar

## Mod Details
* Name: Tesslocator
* CurseForge Link: https://minecraft.curseforge.com/projects/tesslocator?gameCategorySlug=mc-mods&projectID=314814

**Comment by Darkosto** [comment]
Thank you for the suggestion, I am happy with the mod choices we have already made.
