### ISSUE TITLE
AE2 an nuclear not working together plus nuclear machine eating upgrades an locking you out

### ISSUE THREAD

**Issue by nicnacftw** [Darkosto/SkyFactory4Issues#948]
## Bug Report

AE2 wont export or import if you hook an ex/inport in to a nuclear craft machines  just stops all traffic in an out going from  anything that exports or inports  things .
## Expected Behaviour

disconnect inport an export busses from nuclear machine an everything works normal again
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: tree an dirt

* Prestige: no

* Modpack Version world created in:

* Additional Content Installed:optfine tried without same thing

## Client Information

* Modpack Version:4.0.5
* Java Version:
* Launcher Used:twitch
* Memory Allocated:6gb
* Server/LAN/Single Player:server 
* Optifine Installed:yes
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:sponge

**Comment by nicnacftw** [comment]
also the machines from nuclear craft eats the speedy an energy upgrades

**Comment by i9hdkill** [comment]
Can you reproduce this in singleplayer? If not, open an issue at SpongeForge
