### ISSUE TITLE
Server constantly crashing after updating to 4.0.5 (from 4.0.3)

### ISSUE THREAD

**Issue by joshrpg** [Darkosto/SkyFactory4Issues#949]
## Bug Report

After we have updated our server to 4.0.5 from 4.0.3 the server crashes after a few minutes of running. 

## Logs

* Client/Server Log: [Click Me!](https://drive.google.com/open?id=1bUvPbOaU2ZwpcouTPwdCCoJHVOmOu2bc)
* Crash Log: [Click Me!](https://drive.google.com/open?id=1Jw1IC6_g0NTYek3-4mNGiMzQEDo38web)

## World Information

* Preset: {"Topography-Preset":"Skiiiilands"}

* Prestige: No

* Modpack Version world created in: 4.0.0

* Additional Content Installed: None

## Server Information
* Java Version: Latest-ish (I'll find out from the person running the server)
* Operating System: Windows
* Hoster/Hosting Solution: Self Hosted

**Comment by LeSwede** [comment]
Looks to me like there is a problem with the Formulaic Assembler from Mekanism. (I reserve the right to be wrong) Maybe open the map in MCEdit and delete that machine, if you know exactly where it is.

**Comment by joshrpg** [comment]
I don't think it is, these crash logs don't say anything about Mekanism.

Server Log: [Click Me!](https://drive.google.com/open?id=1NfwM1gtKI5q0C4esK1MaP_TMZz39J3SY)
Crash Log: [Click Me!](https://drive.google.com/open?id=16dgoVZMh43T9wL9hKC3Jx8U5UdbQJ0EB)

**Comment by zrattz** [comment]
[Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog]: A single server tick took 60.00 seconds (should be max 0.05)
[18:30:12] [Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog]: Considering it to be crashed, server will forcibly shutdown.

Your server is lagging so watchdog shuts down your server 

Get mod LagGoggles install it on client and server side. and scan your server for blocks that lags your server and brake/replace them. check mob farms to see if the storage is full and alot of items on ground

**Comment by JayJay1989** [comment]
you can try to change ```max-tick-time=-1``` in your server.properties to disable the watchdog. This helps if you're running skyfactory 4 on older server hardware.

**Comment by zrattz** [comment]
> you can try to change `max-tick-time=-1` in your server.properties to disable the watchdog. This helps if you're running skyfactory 4 on older server hardware.

Shure he can do that but server gona be so slow later on, it'st gona take ages to do stuff..
finding the blocks that makes the server slow/lag works better in the long run

**Comment by joshrpg** [comment]
Yeah apparently someone created a lag tower. We set the tick time to -1 and now they are rebuilding it.
