### ISSUE TITLE
End Cake issue

### ISSUE THREAD

**Issue by DashPallvax** [Darkosto/SkyFactory4Issues#954]
If I use the end cake to get to the end and then use the overworld cake to get back I am unable to then use any cake to transport to another dimension. This has occurred multiple times in the same world. Only closing the world will fix it but resets me back to before I clicked on the end cake the first time.

**Comment by DeciTM** [comment]
> Please follow the templates, any issue which fails to provide the requested information will be closed.

That form you erased gives the developers the information they need to look into your issue.

**Comment by Darkosto** [comment]
The reason we ask you follow the form is so we can get logs of what's going on in your instance. Since you haven't provided this and I can't replicate your issue, there's not really much I can do. Next time fill out the information so we can help.
