### ISSUE TITLE
I can't come in my world

### ISSUE THREAD

**Issue by TheLoreGamer** [Darkosto/SkyFactory4Issues#956]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log: No crash log

## World Information

* Preset: Standard

* Prestige: No

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: Latest
* Java Version:
* Launcher Used: standard minecraft
* Memory Allocated: 8mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: 
* Shaders Enabled: No

## Server Information
* Java Version:
* Operating System: windows 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by TheLoreGamer** [comment]
The game remain in the loading world phase. I can't enter in the world

**Comment by LeSwede** [comment]
I hate to sound rude but this isnt easy to fix with 0 information. At least post the latest log found in your installation folder. That would perhaps tell us what the game was doing when it froze.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/Darkosto/SkyFactory4Issues/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
