### ISSUE TITLE
Simple Storage Hitboxes

### ISSUE THREAD

**Issue by CoolDCB** [Darkosto/SkyFactory4Issues#958]
The Simple Storage cable hitboxes take up the whole box meaning if you go up close to a importer or exporter and try to interact with another block it will open the cable GUI. Also when trying to break a block on the other side of the cable the blocks hitbox blocks you and starts breaking the cable.

MORE:  Another glitch with the Simple Storage Cables is that when you stand on them they cause a glitch where the hitbox glitches the player around.

**Comment by DeciTM** [comment]
> Please follow the templates, any issue which fails to provide the requested information will be closed.

Additionally, if you are concerned about a single specific mod, you may want to take issues up with the mod maker themselves instead of for the pack.
