### ISSUE TITLE
Wishing Well not unlocked on higher tier cauldrons

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SkyFactory4Issues#96]
I tried to get the wishing well advancement using a brick cauldron and it didn't work. I had to use the oak/wood one.

**Comment by Darkosto** [comment]
These most likely need to be added to the OreDict @justinrusso ?

**Comment by Darkosto** [comment]
This works just fine for me. Was there actually water in the Cauldron?

**Comment by darkhax** [comment]
Yes the Cauldron had 4/4 bottles of water. The cauldron was also bubbling with a torch underneath it, maybe that's a factor?

**Comment by Darkosto** [comment]
Fixed, now works on boiling and non-boiling cauldrons

**Comment by Darkosto** [comment]
Nvm, I fixed it.
