### ISSUE TITLE
Project E items don't have a EMC value 406 Beta 2

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#960]
## Bug Report
Unlocked Project E, and noticed none of the items from the mod have EMC values when they should from the base mod.
https://gyazo.com/0fd24425545f0fb038577f40c1e3b4f1

## Expected Behaviour
Project E items to have EMC values.

## Steps to Reproduce (for bugs)
1. Unlock Project E
2. Search in JEI
3. No EMC values
4. ???
5. Profit!

## Logs
* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkiiLands

* Prestige: Yes
 
* Modpack Version world created in: 400

* Additional Content Installed: CCI

## Client Information

* Modpack Version: 406 Beta 2
* Java Version: Latest
* Launcher Used: Twitch
* Memory Allocated: 8 gb
* Server/LAN/Single Player: Server
* Optifine Installed: N
* Shaders Enabled: N

## Server Information
* Java Version: Ask Darkphan :P
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Vercalos** [comment]
It's not that they don't have an EMC values, it's that they don't have a _visible_ EMC values.

Project E has yet to be integrated in this modpack, for all that the mod is part of the pack.

I was able to test this by adding a different mod that makes use of Project E's API, and adds new transmutation tables/tablets, Namely, Project EX, and it was able to function, despite the EMC values being invisible.

**Comment by sk2048** [comment]
@Vercalos JackRuby1 is a beta tester and has a version in which ProjectE has been enabled. However the updated version of the mod that fixes the issue we were having was not included in the beta.

**Comment by Vercalos** [comment]
Ah.  Whoops.  Sorry.
