### ISSUE TITLE
Cant find aredite or cobalt

### ISSUE THREAD

**Issue by lavicgs** [Darkosto/SkyFactory4Issues#964]
## Bug Report
The bug I am experiencing is I can't find ardite or cobalt in my world. I have searched probably over 8000 blocks and have not been able to find them in the nether or the lost cities dimensions

## Expected Behaviour
from what I understand I should be able to find them in the nether or lost cities dimensions.

## Possible Solution
possibly not in the version I am playing. Im playing the factree map or whatever the one with the giant dirt tree is called

## Steps to Reproduce (for bugs)

1. load the factree version of sky factory 4 not there that I have been able to find
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: factree

* Prestige: no

* Modpack Version world created in: 4.0.4 I think

* Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.5 now
* Java Version:1.8.0_211
* Launcher Used: twitch launcher
* Memory Allocated: 6400
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: just whatever maybe in the mod pack

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by JackRuby1** [comment]
Certain world types don't have those ore spawns, but there is a recipe for a sapling that doesn't require them or you can use the laser drill to get the ore.

**Comment by Darkosto** [comment]
This is a bug, that world type does not have ardite or cobalt ore in the nether. You need to create those saplings through crafting instead. To fix this on your end so the advancements do not show up, run the following command in chat: 

"/gamestage add @p default_ores"
