### ISSUE TITLE
parabox get stuck at 2.147.483.647 energy

### ISSUE THREAD

**Issue by jensgames** [Darkosto/SkyFactory4Issues#966]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by GleoLP** [comment]
Because, it reached the maximum value from Java int.

**Comment by jensgames** [comment]
So it is impossible to get the paradox working?

**Comment by GleoLP** [comment]
Is the parabox in a loop? Maybe yes, otherwise you won't see the energy value. Have you a screenshot form the parabox' interface?

**Comment by jensgames** [comment]
https://imgur.com/a/KKkIeiI

**Comment by GleoLP** [comment]
Ok, you should wait until the next cycle. You will collect every 10 Minutes 1 prestige point.

**Comment by jensgames** [comment]
Then i cant use the loop 😢?

**Comment by jensgames** [comment]
And duplicate items?

**Comment by GleoLP** [comment]
Yes, you can duplicate items, if you are in loop. Turn off the loop you will have the items in your inventory and on your world.
