### ISSUE TITLE
Hog Tied not part of "You Win! Prestige Off"

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SkyFactory4Issues#97]
I re-obtained the "You win! Prestige Off" advancement, but I don't have the Hog Tied advancement. 

![image](https://user-images.githubusercontent.com/2250798/50569626-23fa4280-0d27-11e9-921a-5ae3cadaaa0f.png)

**Comment by Darkosto** [comment]
These completion advancements are more of a WIP at the moment and feature testing. They are planned to be completed and have all advancements for release.
