### ISSUE TITLE
Deep mob learning

### ISSUE THREAD

**Issue by TheLoreGamer** [Darkosto/SkyFactory4Issues#971]
## Bug Report

I can't obtain pristine matter because i can't craft the respective data models

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: no
* Crash Log: no

## World Information

* Preset: Skyfactory 4

* Prestige: No

* Modpack Version world created in: 4.0.5

* Additional Content Installed: No

## Client Information

* Modpack Version: 4.0.5
* Java Version:
* Launcher Used: twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by Arch-it-12** [comment]
Why can't you craft the data models?  Does it just not show up as a result when you put in the items?  Be specific.

**Comment by TheLoreGamer** [comment]
it doesn't give me a result when i put in the items and the jei doesn't give me the crafting

**Comment by SirioIlBe** [comment]
look if the mod is locked behind prestige points (if you have prestige enabled).

**Comment by TheLoreGamer** [comment]
I haven't prestige enabled

**Comment by Kynotzib** [comment]
You are probably missing the pacifist or non_pacifist gamestage.

**Comment by TheLoreGamer** [comment]
> You are probably missing the pacifist or non_pacifist gamestage.

What is this?

**Comment by woshikie** [comment]
try /gamestage <name> <pacifist/non_pacifist>
use "pacifist" if you're on Peace Out mode, "non_pacifist" otherwise

**Comment by TheLoreGamer** [comment]
Your solution worked but what mean pacifist or non pacifist stage. I can unlock this stage without command?

**Comment by woshikie** [comment]
@TheLoreGamer 
The game stages should be unlocked automatically when you first join the server or SP map, maybe something happened and it did not unlock for you?

**Comment by fasmat** [comment]
@woshikie Manually unlocking non_pacifist allowed me to craft the items required for deep mob learning but some others (e.g. Compact Storage Backpack) are still not available via JEI.

**Comment by sk2048** [comment]
@fasmat Compact Storage does not have a JEI plugin and so its custom recipe handlers do not display in JEI.

The Backpack and Compact Storage Chest are both made using the Chest Builder block.

**Comment by guyjadlo** [comment]
how do I get deep mob learning in prestige mod??
