### ISSUE TITLE
Can't Install Skyfactor 4 Through Twitch Launcher Due To Astral Sorcery

### ISSUE THREAD

**Issue by JosephFuge** [Darkosto/SkyFactory4Issues#972]
When I attempt to install the Skyfactor 4 modpack through the Twitch launcher, it starts downloading each of the mods one a time. When it reaches mod 81 out of like 209 or something, Astral Sorcery, it sits on it for a long while and then ends the install with this error message popping up: 

Timeout attempting to download: https://edge.forgecdn.net/files/2701/235/astralsorcery-1.12.2-1.10.17.jar

Anything I can do to fix this? Is the pack available elsewhere? Thanks.

**Comment by JackRuby1** [comment]
It's also available on ATLauncher or you can download the zip file from CurseForge directly and use an app like MultiMC. The alternative is to just keep trying the download from the Twitch App, maybe closing and reopening it fully.

**Comment by sk2048** [comment]
Closing as this isn't a pack issue and JackRuby1 has given a suitable answer
