### ISSUE TITLE
Server is not loading in the trees from SkyOrchards

### ISSUE THREAD

**Issue by broscolotos** [Darkosto/SkyFactory4Issues#977]
## Bug Report
The bug I am having is I load in, but there is no tree(have tried multiple different new saves) and when I try to JEI a tree/sapling in, it says that the item doesn't exist on the server. With the same files, I can spawn in the saplings in a single player world.

I downloaded the server from the Curse forge, followed the instructions, and this started happening.

## Steps To Reproduce Bug
1. Download the server from Curse forge,
2. follow steps to set up server for windows
3. launch server

* Client/Server Log:(nothing shows up in server logs)
* Crash Log:(There is no crash involved in this)

## World Information
* Preset: {"Topography-Preset"\:"Sky Factory 4"}
* Prestige: Enabled
* Modpack Version world created in: 4.0.5

## Client Information
* Modpack Version: 4.0.5
* Java Version: Java 8
* Launcher Used: Twitch
* Memory Allocated: 4gb
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: Java 8
* Operating System: Windows 10
* Hoster/Hosting Solution: Home Hosted

**Comment by sk2048** [comment]
Please use the appropriate channel on Discord for support requests of this nature: https://discord.gg/darkosto
