### ISSUE TITLE
disabling iron jetpacks prevents me from using sapling recipes

### ISSUE THREAD

**Issue by petesalzl** [Darkosto/SkyFactory4Issues#978]
im trying to disable iron jetpacks from the pack so its not active on my server as there is no config/disable in the mod options that does this i set the jar file to disabled. however for some reason this effects a number of recipes, specifically anything to do with crafting using saplings, acorns, or resin. is there a way around this? or is iron jetpacks mandatory?

**Comment by Streamcyper** [comment]
Disabling the mod causes some of the scripts to break and then nothing will work right. Why do you want to remove the mod? If you don't like it you can easily just not use it.

**Comment by sk2048** [comment]
See #962
