### ISSUE TITLE
Achievement: All the Trees missing one tree - Prosperity

### ISSUE THREAD

**Issue by VallenFrostweaver** [Darkosto/SkyFactory4Issues#979]
## Bug Report
"All the Trees" achievement lists 28 saplings when there are 29. Prosperity sapling is missing.
## Expected Behaviour
29 saplings including Prosperity for achievement

## Steps to Reproduce (for bugs)
1. Start game, go to Age of Farming tab and hover mouse over "All the Trees" achieve and see that one is missing (above)
2. That's it. You are now awesome.

## World Information
* Preset: Lost Cities
* Prestige: No
* Modpack Version world created in: 4.0.2 but now running 4.0.5
* Additional Content Installed: LagGoggles

## Client Information
* Modpack Version: 4.0.5
* Java Version: 8 update 211 (build 1.8.0_211-b12)
* Launcher Used: Twitch
* Memory Allocated: 6656
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
I do not have this information to provide. :(

**Comment by sk2048** [comment]
This is deliberate - the prosperity sapling is unobtainable to those playing prestige who have not unlocked Mystical Agriculture and so the advancement does not require it.
