### ISSUE TITLE
Chargers' Chargers charge past their capacity(?)

### ISSUE THREAD

**Issue by jaredlll08** [Darkosto/SkyFactory4Issues#98]
https://i.blamejared.com/1GGaF.gif

**Comment by Darkosto** [comment]
This might be something @GoryMoon could take a look at?

**Comment by GoryMoon** [comment]
Yeah, found the issue.
Was using the default`detectAndSendChanges` way for client data, missed it used shorts for the value. (could not be larger then 32767, that's why the weird numbers)
Fixed this and will have an update soon.

**Comment by GoryMoon** [comment]
The fix and additional fixes and additions are now available on curse at: https://minecraft.curseforge.com/projects/chargers/files/2656250
