### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by ShotzFired13Gaming** [Darkosto/SkyFactory4Issues#989]
I was in the game doing absolutley nothing and then all of a sudden my game crashed and now it wont let me back into that server. [Game Crash Report](https://pastebin.com/ZNfRuQFJ)

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template (which you have ignored and deleted) any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
