### ISSUE TITLE
Cyclic Packager not crafting Industrial Foregoing Dry Rubber

### ISSUE THREAD

**Issue by MongoTheElder** [Darkosto/SkyFactory4Issues#99]
The Packager is missing a recipe to combine 9 Tiny Dry Rubber into 1 Dry Rubber

![2019-01-01_14 20 37](https://user-images.githubusercontent.com/29290246/50575669-78a5c800-0dd0-11e9-8aa3-d08f7efa3da9.png)

SkyFactory4-0.2.1

**Comment by Darkosto** [comment]
Added!
