### ISSUE TITLE
Can't access inventory crafting table while having Handy bag in inventory

### ISSUE THREAD

**Issue by badfeet** [Darkosto/SkyFactory4Issues#990]
## Bug Report
If you have the Handy Bag (Ender Utilities) in your inventory you cannot access the Inventory Crafting Table (Cyclic)

## Expected Behaviour
You should be able to access the 3x3 Inventory Crafting Grid (the C located above the player image) when in the inventory.

## Steps to Reproduce (for bugs)
1. Eat Cyclic Inventory Crafting Table
2. Confirm you can access the 3x3 table from inventory
3. Have a Handy Bag in inventory
4. Open inventory again.  No C to click on to to access Cyclic inventory grid

## Logs
N/A

## World Information
* Preset: Sky Village
* Prestige: No
* Modpack Version world created in: 4.0.5
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.0.5
* Java Version: v8.171
* Launcher Used: Twitch
* Memory Allocated: 7168
* Server/LAN/Single Player: SP
* Optifine Installed: no
* Shaders Enabled: no

**Comment by GleoLP** [comment]
press shift and at the same time e, then you got the "normal" inventory.

**Comment by Darkosto** [comment]
The tooltip gives this information: Holding Sneak while opening inventory will open the normal inventory.
