### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ShotzFired13Gaming** [Darkosto/SkyFactory4Issues#991]
## Bug Report

The Server Randomly Crashed and doesnt let me get back into my single player server.
## Expected Behaviour

I wasn't doing anything other than watching Bacon Donuts Stream and then i went back and it wasn't responding.

## Possible Solution

The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Ticking block entity

## Steps to Reproduce (for bugs)

1. https://youtu.be/AaCKVoR20yU?t=50
2.

## Logs

* Client/Server Log: https://pastebin.com/JmZfZMw6
* Crash Log: https://pastebin.com/ZNfRuQFJ

## World Information

* Preset:Normal SkyFactory

* Prestige: Nope

* Modpack Version world created in: 4.0.5

* Additional Content Installed: N/a

## Client Information

* Modpack Version:4.0.5
* Java Version:1.12.2
* Launcher Used:Twitch and MC
* Memory Allocated:
* Server/LAN/Single Player:Single Player
* Optifine Installed:No
* Shaders Enabled:No

**Comment by justinrusso** [comment]
Duplicate of #565

**Comment by ShotzFired13Gaming** [comment]
Will this problem ever get resolved??

**Comment by justinrusso** [comment]
You can follow the other issue for the status of it.
