### ISSUE TITLE
Just Enough Items (JEI) not showing all items 

### ISSUE THREAD

**Issue by vesko128** [Darkosto/SkyFactory4Issues#993]
JEI doesn't show all the items that are available in the game. In fact, I know that spawn eggs or the ultimate universal cable are things that exist, yet they are nowhere to be seen in JEI? Are they just removed due to issues with other mods or just for being too op?

**Comment by Skavies** [comment]
This is intended.

Spawn eggs are crafted in world, so they won't show up in JEI. (DNA swab a mob, make chicken feed and use that to feed an adult chicken to make it lay a spawn egg.  JEI does have the chicken feed recipe...)

Universal cables (and several other common items) have been removed or not included to make us use different mods to do common tasks.

**Comment by vesko128** [comment]
Thank you for the info, with my questions answered I will close this thread.
