### ISSUE TITLE
Server Crash - 'wyld's Head' in inventory accessed by player

### ISSUE THREAD

**Issue by Dugoth** [Darkosto/SkyFactory4Issues#997]
## Bug Report

On a player opening an inventory containing the item 'wyld's Head' the server would crash consistently. The inventory could be Simple Storage (direct interaction or block) or just a trapped chest in this case. The item was able to be viewed and pulled out by a player from a ComPatchedStorage chest. Unable to determine if it's a problem with the item as a whole or if there was a specific issue of corruption with that item in this instance.

## Expected Behaviour

I would expect the server not to instantly crash when opening an inventory with a specific item inside :)

## Possible Solution

Pulling out the item from the ComPatchedStorage chest after disconnecting it from Simple Storage seemed to resolve the issue. Server crashed again while subsequently setting up a trash filter on the mob farm where the item could be generated from and dropping the item into the buffer chest to be sent to trash. Item was gone following server restart so it appears player interaction with the inventory containing the item may also be a required component. Very quantum.

## Steps to Reproduce (for bugs)

1. While 'wyld's Head' was in a chest connected to Simple Storage any attempt to view the Simple Storage inventory immediately crashed the server, either direct or remote. Additionally crashed when manually putting the item into a trapped chest.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/QN95F1dY

## World Information

* Preset: {"Topography-Preset"\:"Sky Factory 4"}

* Prestige: No

* Modpack Version world created in: 4.05

* Additional Content Installed:

## Client Information

* Modpack Version: 4.05
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed:
* Shaders Enabled: Yes

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution: ServerMiner
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
The stack trace indicates Random Patches is calling a client only class from the server.

Random Patches is not a component of SF4, so you're on your own here. However, may I suggest you update that mod if you actually need it, see TheRandomLabs/RandomPatches#31
