### ISSUE TITLE
Scrambled text in chat window when first loading Sky Factory 4

### ISSUE THREAD

**Issue by sbrocket** [Darkosto/SkyFactory4Issues#998]
See attached screen recording. Two lines of text in the chat window are scrambled and rapidly changing. Using MultiMC 0.6.5-1243 on OS X, with Sky Factory 4 4.0.5 downloaded from Curseforge and a fresh instance created from the zip archive.

[SkyFactory4 Scrambled Text.m4v.zip](https://github.com/Darkosto/SkyFactory4Issues/files/3210513/SkyFactory4.Scrambled.Text.m4v.zip)

**Comment by sk2048** [comment]
They're meant to be, as a way of drawing the eye and highlighting the block of text they surround
